# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.ns0 as ns0

class ARGB32ColorType(ns0.datatypes.Structure):
    @property
    def value(self) -> o6.UInt32: ...
    @value.setter
    def value(self, value: _Integer) -> None: ...
    @property
    def name(self) -> list[o6.String]: ...
    @name.setter
    def name(self, value: Sequence[o6.String]) -> None: ...

class IdBaseDataType:
    pass

class CrimpBarrelType(enum.IntFlag):
    OPEN = 0
    CLOSED = 1

class ExtendableElement(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ConfigurableElement(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ItemVersion(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def companyName(self) -> list[o6.String]: ...
    @companyName.setter
    def companyName(self, value: Sequence[o6.String]) -> None: ...

class PartVersion(ItemVersion):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def companyName(self) -> list[o6.String]: ...
    @companyName.setter
    def companyName(self, value: Sequence[o6.String]) -> None: ...
    @property
    def partNumber(self) -> o6.String: ...
    @partNumber.setter
    def partNumber(self, value: o6.String) -> None: ...

class PrimaryPartType(enum.IntFlag):
    ANTENNA = 0
    BATTERY = 1
    BOLT_MOUNTED_FIXING = 2
    BOLT_TERMINAL = 3
    BRIDGE_TERMINAL = 4
    CABLE_DUCT = 5
    CABLE_TIE = 6
    CAPACITOR = 7
    CAVITY_ACCESSORY = 8
    CAVITY_PLUG = 9
    CAVITY_SEAL = 10
    CONNECTOR_HOUSING = 11
    CONNECTOR_HOUSING_CAP = 12
    CONNECTOR_HOUSING_COVER = 13
    CORRUGATED_PIPE = 14
    DIODE = 15
    EDGE_MOUNTED_FIXING = 16
    EE_COMPONENT = 17
    FERRITE = 18
    FITTING = 19
    FIXING = 20
    FUSE = 21
    GROMMET = 22
    HOLE_MOUNTED_FIXING = 23
    MULTI_CAVITY_PLUG = 24
    MULTI_CAVITY_SEAL = 25
    MULTI_FUSE = 26
    OTHER = 27
    OPEN_WIRE_END_TERMINAL = 28
    OPEN_WIRE_END = 29
    PART_STRUCTURE = 30
    PLUGGABLE_TERMINAL = 31
    POTENTIAL_DISTRIBUTOR = 32
    RELAY = 33
    RING_TERMINAL = 34
    SHRINKABLE_TUBE = 35
    SPLICE_TERMINAL = 36
    STRIPE = 37
    TAPE = 38
    TERMINAL = 39
    TUBE = 40
    WIRE = 41
    WIRE_END_ACCESSORY = 42
    WIRE_PROTECTION = 43

class RoutableElement(ConfigurableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class Specification(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...

class DocumentVersion(ItemVersion):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def companyName(self) -> list[o6.String]: ...
    @companyName.setter
    def companyName(self, value: Sequence[o6.String]) -> None: ...
    @property
    def documentNumber(self) -> list[o6.String]: ...
    @documentNumber.setter
    def documentNumber(self, value: Sequence[o6.String]) -> None: ...
    @property
    def documentVersion(self) -> list[o6.String]: ...
    @documentVersion.setter
    def documentVersion(self, value: Sequence[o6.String]) -> None: ...
    @property
    def digitalRepresentationIndex(self) -> list[o6.String]: ...
    @digitalRepresentationIndex.setter
    def digitalRepresentationIndex(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specification(self) -> list[Specification]: ...
    @specification.setter
    def specification(self, value: Sequence[Specification]) -> None: ...

class PartOrUsageRelatedSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...

class ResourceVersion(ItemVersion):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def companyName(self) -> list[o6.String]: ...
    @companyName.setter
    def companyName(self, value: Sequence[o6.String]) -> None: ...
    @property
    def resourceNumber(self) -> o6.String: ...
    @resourceNumber.setter
    def resourceNumber(self, value: o6.String) -> None: ...
    @property
    def resourceVersion(self) -> o6.String: ...
    @resourceVersion.setter
    def resourceVersion(self, value: o6.String) -> None: ...

class CavityPartSpecification(PartOrUsageRelatedSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...

class CavitySealSpecification(CavityPartSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...

class ConductorType(enum.IntFlag):
    RIGID = 0
    STRANDED = 1
    FOIL = 2
    BRAIDED = 3

class Role(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...

class OccurrenceOrUsage(ConfigurableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> o6.String: ...
    @identification.setter
    def identification(self, value: o6.String) -> None: ...
    @property
    def role(self) -> list[Role]: ...
    @role.setter
    def role(self, value: Sequence[Role]) -> None: ...

class CavityPartRole(Role):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...

class PartOccurrence(OccurrenceOrUsage):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> o6.String: ...
    @identification.setter
    def identification(self, value: o6.String) -> None: ...
    @property
    def role(self) -> list[Role]: ...
    @role.setter
    def role(self, value: Sequence[Role]) -> None: ...
    @property
    def part(self) -> list[PartVersion]: ...
    @part.setter
    def part(self, value: Sequence[PartVersion]) -> None: ...

class CompositionSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def component(self) -> list[PartOccurrence]: ...
    @component.setter
    def component(self, value: Sequence[PartOccurrence]) -> None: ...

class Material(ns0.datatypes.Structure):
    @property
    def key(self) -> o6.String: ...
    @key.setter
    def key(self, value: o6.String) -> None: ...
    @property
    def referenceSystem(self) -> o6.String: ...
    @referenceSystem.setter
    def referenceSystem(self, value: o6.String) -> None: ...

class Tolerance(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def lowerBoundary(self) -> o6.Double: ...
    @lowerBoundary.setter
    def lowerBoundary(self, value: SupportsFloat) -> None: ...
    @property
    def upperBoundary(self) -> o6.Double: ...
    @upperBoundary.setter
    def upperBoundary(self, value: SupportsFloat) -> None: ...

class ValueWithUnit(ns0.datatypes.Structure):
    @property
    def unitComponent(self) -> ns0.datatypes.EUInformation: ...
    @unitComponent.setter
    def unitComponent(self, value: ns0.datatypes.EUInformation) -> None: ...

class NumericalValue(ValueWithUnit):
    @property
    def unitComponent(self) -> ns0.datatypes.EUInformation: ...
    @unitComponent.setter
    def unitComponent(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def valueComponent(self) -> o6.Double: ...
    @valueComponent.setter
    def valueComponent(self, value: SupportsFloat) -> None: ...
    @property
    def tolerance(self) -> list[Tolerance]: ...
    @tolerance.setter
    def tolerance(self, value: Sequence[Tolerance]) -> None: ...

class ConductorSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def crossSectionArea(self) -> list[NumericalValue]: ...
    @crossSectionArea.setter
    def crossSectionArea(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def type(self) -> list[ConductorType]: ...
    @type.setter
    def type(self, value: Sequence[_Integer]) -> None: ...

class CoreSpecification(ConductorSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def crossSectionArea(self) -> list[NumericalValue]: ...
    @crossSectionArea.setter
    def crossSectionArea(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def type(self) -> list[ConductorType]: ...
    @type.setter
    def type(self, value: Sequence[_Integer]) -> None: ...
    @property
    def outsideDiameter(self) -> list[NumericalValue]: ...
    @outsideDiameter.setter
    def outsideDiameter(self, value: Sequence[NumericalValue]) -> None: ...

class InsulationSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def baseColor(self) -> ARGB32ColorType: ...
    @baseColor.setter
    def baseColor(self, value: ARGB32ColorType) -> None: ...
    @property
    def firstIdentificationColor(self) -> list[ARGB32ColorType]: ...
    @firstIdentificationColor.setter
    def firstIdentificationColor(self, value: Sequence[ARGB32ColorType]) -> None: ...
    @property
    def secondIdentificationColor(self) -> list[ARGB32ColorType]: ...
    @secondIdentificationColor.setter
    def secondIdentificationColor(self, value: Sequence[ARGB32ColorType]) -> None: ...
    @property
    def thickness(self) -> list[NumericalValue]: ...
    @thickness.setter
    def thickness(self, value: Sequence[NumericalValue]) -> None: ...

class WireElementSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def outsideDiameter(self) -> list[NumericalValue]: ...
    @outsideDiameter.setter
    def outsideDiameter(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def conductorSpecification(self) -> list[ConductorSpecification]: ...
    @conductorSpecification.setter
    def conductorSpecification(self, value: Sequence[ConductorSpecification]) -> None: ...
    @property
    def insulationSpecification(self) -> list[InsulationSpecification]: ...
    @insulationSpecification.setter
    def insulationSpecification(self, value: Sequence[InsulationSpecification]) -> None: ...

class WireElement(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def wireElementSpecification(self) -> WireElementSpecification: ...
    @wireElementSpecification.setter
    def wireElementSpecification(self, value: WireElementSpecification) -> None: ...
    @property
    def subWireElement(self) -> list[WireElement]: ...
    @subWireElement.setter
    def subWireElement(self, value: Sequence[WireElement]) -> None: ...

class WireSpecification(PartOrUsageRelatedSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...
    @property
    def wireElement(self) -> WireElement: ...
    @wireElement.setter
    def wireElement(self, value: WireElement) -> None: ...

class WireEnd(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def positionOnWire(self) -> o6.Double: ...
    @positionOnWire.setter
    def positionOnWire(self, value: SupportsFloat) -> None: ...
    @property
    def strippingLength(self) -> list[NumericalValue]: ...
    @strippingLength.setter
    def strippingLength(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def insulationPullbackLength(self) -> list[NumericalValue]: ...
    @insulationPullbackLength.setter
    def insulationPullbackLength(self, value: Sequence[NumericalValue]) -> None: ...

class Size(ns0.datatypes.Structure):
    @property
    def width(self) -> NumericalValue: ...
    @width.setter
    def width(self, value: NumericalValue) -> None: ...
    @property
    def height(self) -> NumericalValue: ...
    @height.setter
    def height(self, value: NumericalValue) -> None: ...

class CrimpDetail(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def size(self) -> list[Size]: ...
    @size.setter
    def size(self, value: Sequence[Size]) -> None: ...

class InsulationCrimpDetail(CrimpDetail):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def size(self) -> list[Size]: ...
    @size.setter
    def size(self, value: Sequence[Size]) -> None: ...
    @property
    def pullOffForce(self) -> list[NumericalValue]: ...
    @pullOffForce.setter
    def pullOffForce(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def appliesTo(self) -> InsulationSpecification: ...
    @appliesTo.setter
    def appliesTo(self, value: InsulationSpecification) -> None: ...

class CoreCrimpDetail(CrimpDetail):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def size(self) -> list[Size]: ...
    @size.setter
    def size(self, value: Sequence[Size]) -> None: ...
    @property
    def appliesTo(self) -> ConductorSpecification: ...
    @appliesTo.setter
    def appliesTo(self, value: ConductorSpecification) -> None: ...
    @property
    def insulationCrimpDetails(self) -> list[InsulationCrimpDetail]: ...
    @insulationCrimpDetails.setter
    def insulationCrimpDetails(self, value: Sequence[InsulationCrimpDetail]) -> None: ...
    @property
    def pullOffForce(self) -> list[NumericalValue]: ...
    @pullOffForce.setter
    def pullOffForce(self, value: Sequence[NumericalValue]) -> None: ...

class ValueRange(ValueWithUnit):
    @property
    def unitComponent(self) -> ns0.datatypes.EUInformation: ...
    @unitComponent.setter
    def unitComponent(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def minimum(self) -> o6.Double: ...
    @minimum.setter
    def minimum(self, value: SupportsFloat) -> None: ...
    @property
    def maximum(self) -> o6.Double: ...
    @maximum.setter
    def maximum(self, value: SupportsFloat) -> None: ...

class WireReceptionSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def insulationDisplacementLength(self) -> NumericalValue: ...
    @insulationDisplacementLength.setter
    def insulationDisplacementLength(self, value: NumericalValue) -> None: ...
    @property
    def conductorCrimpLength(self) -> list[NumericalValue]: ...
    @conductorCrimpLength.setter
    def conductorCrimpLength(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def crimpConnectionLength(self) -> NumericalValue: ...
    @crimpConnectionLength.setter
    def crimpConnectionLength(self, value: NumericalValue) -> None: ...
    @property
    def insulationCrimpLength(self) -> list[NumericalValue]: ...
    @insulationCrimpLength.setter
    def insulationCrimpLength(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def wireTipProtrusion(self) -> list[ValueRange]: ...
    @wireTipProtrusion.setter
    def wireTipProtrusion(self, value: Sequence[ValueRange]) -> None: ...
    @property
    def coreCrimpDetails(self) -> list[CoreCrimpDetail]: ...
    @coreCrimpDetails.setter
    def coreCrimpDetails(self, value: Sequence[CoreCrimpDetail]) -> None: ...
    @property
    def crimpBarrelType(self) -> CrimpBarrelType: ...
    @crimpBarrelType.setter
    def crimpBarrelType(self, value: _Integer) -> None: ...

class WireReception(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def rotation(self) -> list[NumericalValue]: ...
    @rotation.setter
    def rotation(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def wireReceptionSpecification(self) -> WireReceptionSpecification: ...
    @wireReceptionSpecification.setter
    def wireReceptionSpecification(self, value: WireReceptionSpecification) -> None: ...

class TerminalSpecification(PartOrUsageRelatedSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...
    @property
    def connectionALength(self) -> list[NumericalValue]: ...
    @connectionALength.setter
    def connectionALength(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def overallLength(self) -> NumericalValue: ...
    @overallLength.setter
    def overallLength(self, value: NumericalValue) -> None: ...
    @property
    def wireReception(self) -> list[WireReception]: ...
    @wireReception.setter
    def wireReception(self, value: Sequence[WireReception]) -> None: ...

class PluggableTerminalSpecification(TerminalSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...
    @property
    def connectionALength(self) -> list[NumericalValue]: ...
    @connectionALength.setter
    def connectionALength(self, value: Sequence[NumericalValue]) -> None: ...
    @property
    def overallLength(self) -> NumericalValue: ...
    @overallLength.setter
    def overallLength(self, value: NumericalValue) -> None: ...
    @property
    def wireReception(self) -> list[WireReception]: ...
    @wireReception.setter
    def wireReception(self, value: Sequence[WireReception]) -> None: ...

class BoundingBox(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def x(self) -> NumericalValue: ...
    @x.setter
    def x(self, value: NumericalValue) -> None: ...
    @property
    def y(self) -> NumericalValue: ...
    @y.setter
    def y(self, value: NumericalValue) -> None: ...
    @property
    def z(self) -> NumericalValue: ...
    @z.setter
    def z(self, value: NumericalValue) -> None: ...

class GeneralTechnicalPartSpecification(PartOrUsageRelatedSpecification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def specialPartType(self) -> list[o6.String]: ...
    @specialPartType.setter
    def specialPartType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def describedPart(self) -> list[PartVersion]: ...
    @describedPart.setter
    def describedPart(self, value: Sequence[PartVersion]) -> None: ...
    @property
    def colorInformation(self) -> list[ARGB32ColorType]: ...
    @colorInformation.setter
    def colorInformation(self, value: Sequence[ARGB32ColorType]) -> None: ...
    @property
    def boundingBox(self) -> list[BoundingBox]: ...
    @boundingBox.setter
    def boundingBox(self, value: Sequence[BoundingBox]) -> None: ...

class ContactPointIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ContactingSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireMountingIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireMountingDetailIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ConfigurableElementIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class DocumentVersionIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ExtendableElementIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ItemVersionIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class PartOrUsageRelatedSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class PartVersionIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class RoutableElementIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class SpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ResourceVersionIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CavitySealSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CavitySealRole(CavityPartRole):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def cavitySealSpecification(self) -> CavitySealSpecificationIdDataType: ...
    @cavitySealSpecification.setter
    def cavitySealSpecification(self, value: CavitySealSpecificationIdDataType) -> None: ...

class ConductorSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CoreSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class GeneralTechnicalPartSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class InsulationSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class PluggableTerminalSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class TerminalSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireElementIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireElementReference(RoutableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def referencedWireElement(self) -> WireElementIdDataType: ...
    @referencedWireElement.setter
    def referencedWireElement(self, value: WireElementIdDataType) -> None: ...
    @property
    def wireEnd(self) -> list[WireEnd]: ...
    @wireEnd.setter
    def wireEnd(self, value: Sequence[WireEnd]) -> None: ...
    @property
    def wireLength(self) -> list[NumericalValue]: ...
    @wireLength.setter
    def wireLength(self, value: Sequence[NumericalValue]) -> None: ...

class WireElementSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireReceptionIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireReceptionReference(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def wireReception(self) -> WireReceptionIdDataType: ...
    @wireReception.setter
    def wireReception(self, value: WireReceptionIdDataType) -> None: ...

class TerminalRole(Role):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def terminalSpecification(self) -> TerminalSpecificationIdDataType: ...
    @terminalSpecification.setter
    def terminalSpecification(self, value: TerminalSpecificationIdDataType) -> None: ...
    @property
    def wireReceptionReference(self) -> list[WireReceptionReference]: ...
    @wireReceptionReference.setter
    def wireReceptionReference(self, value: Sequence[WireReceptionReference]) -> None: ...

class PluggableTerminalRole(TerminalRole):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def terminalSpecification(self) -> TerminalSpecificationIdDataType: ...
    @terminalSpecification.setter
    def terminalSpecification(self, value: TerminalSpecificationIdDataType) -> None: ...
    @property
    def wireReceptionReference(self) -> list[WireReceptionReference]: ...
    @wireReceptionReference.setter
    def wireReceptionReference(self, value: Sequence[WireReceptionReference]) -> None: ...

class WireReceptionSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireRole(Role):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def wireSpecification(self) -> WireSpecificationIdDataType: ...
    @wireSpecification.setter
    def wireSpecification(self, value: WireSpecificationIdDataType) -> None: ...
    @property
    def wireElementReference(self) -> list[WireElementReference]: ...
    @wireElementReference.setter
    def wireElementReference(self, value: Sequence[WireElementReference]) -> None: ...

class CavityPartSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class InsulationCrimpDetailIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CoreCrimpDetailIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CrimpDetailIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class OccurrenceOrUsageIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class RoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CavitySealRoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class PluggableTerminalRoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class TerminalRoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireElementReferenceIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireEndIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireRoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireReceptionReferenceIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class WireMountingDetail(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def coreCrimpSize(self) -> list[Size]: ...
    @coreCrimpSize.setter
    def coreCrimpSize(self, value: Sequence[Size]) -> None: ...
    @property
    def insulationCrimpSize(self) -> list[Size]: ...
    @insulationCrimpSize.setter
    def insulationCrimpSize(self, value: Sequence[Size]) -> None: ...
    @property
    def wireTipProtrusion(self) -> list[ValueRange]: ...
    @wireTipProtrusion.setter
    def wireTipProtrusion(self, value: Sequence[ValueRange]) -> None: ...
    @property
    def contactedWireReception(self) -> WireReceptionReferenceIdDataType: ...
    @contactedWireReception.setter
    def contactedWireReception(self, value: WireReceptionReferenceIdDataType) -> None: ...
    @property
    def referencedWireEnd(self) -> list[WireEndIdDataType]: ...
    @referencedWireEnd.setter
    def referencedWireEnd(self, value: Sequence[WireEndIdDataType]) -> None: ...
    @property
    def absoluteSealPosition(self) -> NumericalValue: ...
    @absoluteSealPosition.setter
    def absoluteSealPosition(self, value: NumericalValue) -> None: ...
    @property
    def corePullOffForce(self) -> list[NumericalValue]: ...
    @corePullOffForce.setter
    def corePullOffForce(self, value: Sequence[NumericalValue]) -> None: ...

class WireMounting(ExtendableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def mountedCavitySeal(self) -> list[CavitySealRoleIdDataType]: ...
    @mountedCavitySeal.setter
    def mountedCavitySeal(self, value: Sequence[CavitySealRoleIdDataType]) -> None: ...
    @property
    def referencedWireEnd(self) -> list[WireEndIdDataType]: ...
    @referencedWireEnd.setter
    def referencedWireEnd(self, value: Sequence[WireEndIdDataType]) -> None: ...
    @property
    def wireMountingDetail(self) -> list[WireMountingDetail]: ...
    @wireMountingDetail.setter
    def wireMountingDetail(self, value: Sequence[WireMountingDetail]) -> None: ...

class ContactPoint(ConfigurableElement):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def mountedTerminal(self) -> list[TerminalRoleIdDataType]: ...
    @mountedTerminal.setter
    def mountedTerminal(self, value: Sequence[TerminalRoleIdDataType]) -> None: ...
    @property
    def wireMounting(self) -> list[WireMounting]: ...
    @wireMounting.setter
    def wireMounting(self, value: Sequence[WireMounting]) -> None: ...

class ContactingSpecification(Specification):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def identification(self) -> list[o6.String]: ...
    @identification.setter
    def identification(self, value: Sequence[o6.String]) -> None: ...
    @property
    def contactPoint(self) -> list[ContactPoint]: ...
    @contactPoint.setter
    def contactPoint(self, value: Sequence[ContactPoint]) -> None: ...

class CavityPartRoleIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CompositionSpecificationIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class PartOccurrenceIdDataType(IdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
