# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.ns0 as ns0

class ISA95PropertyDataType(ns0.datatypes.Structure):
    """A subtype of OPC UA Structure that defines two linked data items: an ID, which is a unique identifier for a property within the scope of the associated resource, and the value, which is the data for the property."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def subproperties(self) -> list[ISA95PropertyDataType] | None: ...
    @subproperties.setter
    def subproperties(self, value: Sequence[ISA95PropertyDataType] | None) -> None: ...

class ISA95ParameterDataType(ns0.datatypes.Structure):
    """A subtype of OPC UA Structure that defines three linked data items: the ID, which is a unique identifier for a property, the value, which is the data that is identified, and an optional description of the parameter."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def subparameters(self) -> list[ISA95ParameterDataType] | None: ...
    @subparameters.setter
    def subparameters(self, value: Sequence[ISA95ParameterDataType] | None) -> None: ...

class ISA95EquipmentDataType(ns0.datatypes.Structure):
    """Defines an equipment resource or a piece of equipment, a quantity, an optional description, and an optional collection of properties."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def equipmentUse(self) -> o6.String | None: ...
    @equipmentUse.setter
    def equipmentUse(self, value: o6.String | None) -> None: ...
    @property
    def quantity(self) -> o6.String | None: ...
    @quantity.setter
    def quantity(self, value: o6.String | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def properties(self) -> list[ISA95PropertyDataType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[ISA95PropertyDataType] | None) -> None: ...

class ISA95StateDataType(ns0.datatypes.Structure):
    """Defines the information needed to schedule and execute a job."""

    @property
    def browsePath(self) -> ns0.datatypes.RelativePath: ...
    @browsePath.setter
    def browsePath(self, value: ns0.datatypes.RelativePath) -> None: ...
    @property
    def stateText(self) -> o6.LocalizedText: ...
    @stateText.setter
    def stateText(self, value: o6.LocalizedText) -> None: ...
    @property
    def stateNumber(self) -> o6.UInt32: ...
    @stateNumber.setter
    def stateNumber(self, value: _Integer) -> None: ...

class ISA95WorkMasterDataType(ns0.datatypes.Structure):
    """Defines a Work Master ID and the defined parameters for the Work Master."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def parameters(self) -> list[ISA95ParameterDataType] | None: ...
    @parameters.setter
    def parameters(self, value: Sequence[ISA95ParameterDataType] | None) -> None: ...

class ISA95MaterialDataType(ns0.datatypes.Structure):
    """Defines a material resource, a quantity, an optional description, and an optional collection of properties."""

    @property
    def materialClassID(self) -> o6.String | None: ...
    @materialClassID.setter
    def materialClassID(self, value: o6.String | None) -> None: ...
    @property
    def materialDefinitionID(self) -> o6.String | None: ...
    @materialDefinitionID.setter
    def materialDefinitionID(self, value: o6.String | None) -> None: ...
    @property
    def materialLotID(self) -> o6.String | None: ...
    @materialLotID.setter
    def materialLotID(self, value: o6.String | None) -> None: ...
    @property
    def materialSublotID(self) -> o6.String | None: ...
    @materialSublotID.setter
    def materialSublotID(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def materialUse(self) -> o6.String | None: ...
    @materialUse.setter
    def materialUse(self, value: o6.String | None) -> None: ...
    @property
    def quantity(self) -> o6.String | None: ...
    @quantity.setter
    def quantity(self, value: o6.String | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def properties(self) -> list[ISA95PropertyDataType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[ISA95PropertyDataType] | None) -> None: ...

class ISA95PersonnelDataType(ns0.datatypes.Structure):
    """Defines a personnel resource or a person, a quantity, an optional description, and an optional collection of properties."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def personnelUse(self) -> o6.String | None: ...
    @personnelUse.setter
    def personnelUse(self, value: o6.String | None) -> None: ...
    @property
    def quantity(self) -> o6.String | None: ...
    @quantity.setter
    def quantity(self, value: o6.String | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def properties(self) -> list[ISA95PropertyDataType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[ISA95PropertyDataType] | None) -> None: ...

class ISA95PhysicalAssetDataType(ns0.datatypes.Structure):
    """Defines a physical asset, a quantity, an optional description, and an optional collection of properties."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def physicalAssetUse(self) -> o6.String | None: ...
    @physicalAssetUse.setter
    def physicalAssetUse(self, value: o6.String | None) -> None: ...
    @property
    def quantity(self) -> o6.String | None: ...
    @quantity.setter
    def quantity(self, value: o6.String | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...
    @property
    def properties(self) -> list[ISA95PropertyDataType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[ISA95PropertyDataType] | None) -> None: ...

class ISA95JobOrderDataType(ns0.datatypes.Structure):
    """Defines the information needed to schedule and execute a job."""

    @property
    def jobOrderID(self) -> o6.String: ...
    @jobOrderID.setter
    def jobOrderID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> list[o6.LocalizedText] | None: ...
    @description.setter
    def description(self, value: Sequence[o6.LocalizedText] | None) -> None: ...
    @property
    def workMasterID(self) -> list[ISA95WorkMasterDataType] | None: ...
    @workMasterID.setter
    def workMasterID(self, value: Sequence[ISA95WorkMasterDataType] | None) -> None: ...
    @property
    def startTime(self) -> o6.DateTime | None: ...
    @startTime.setter
    def startTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def endTime(self) -> o6.DateTime | None: ...
    @endTime.setter
    def endTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def priority(self) -> o6.Int16 | None: ...
    @priority.setter
    def priority(self, value: _Integer | None) -> None: ...
    @property
    def jobOrderParameters(self) -> list[ISA95ParameterDataType] | None: ...
    @jobOrderParameters.setter
    def jobOrderParameters(self, value: Sequence[ISA95ParameterDataType] | None) -> None: ...
    @property
    def personnelRequirements(self) -> list[ISA95PersonnelDataType] | None: ...
    @personnelRequirements.setter
    def personnelRequirements(self, value: Sequence[ISA95PersonnelDataType] | None) -> None: ...
    @property
    def equipmentRequirements(self) -> list[ISA95EquipmentDataType] | None: ...
    @equipmentRequirements.setter
    def equipmentRequirements(self, value: Sequence[ISA95EquipmentDataType] | None) -> None: ...
    @property
    def physicalAssetRequirements(self) -> list[ISA95PhysicalAssetDataType] | None: ...
    @physicalAssetRequirements.setter
    def physicalAssetRequirements(self, value: Sequence[ISA95PhysicalAssetDataType] | None) -> None: ...
    @property
    def materialRequirements(self) -> list[ISA95MaterialDataType] | None: ...
    @materialRequirements.setter
    def materialRequirements(self, value: Sequence[ISA95MaterialDataType] | None) -> None: ...

class ISA95JobResponseDataType(ns0.datatypes.Structure):
    """Defines the information needed to schedule and execute a job."""

    @property
    def jobResponseID(self) -> o6.String: ...
    @jobResponseID.setter
    def jobResponseID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def jobOrderID(self) -> o6.String: ...
    @jobOrderID.setter
    def jobOrderID(self, value: o6.String) -> None: ...
    @property
    def startTime(self) -> o6.DateTime | None: ...
    @startTime.setter
    def startTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def endTime(self) -> o6.DateTime | None: ...
    @endTime.setter
    def endTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def jobState(self) -> list[ISA95StateDataType]: ...
    @jobState.setter
    def jobState(self, value: Sequence[ISA95StateDataType]) -> None: ...
    @property
    def jobResponseData(self) -> list[ISA95ParameterDataType] | None: ...
    @jobResponseData.setter
    def jobResponseData(self, value: Sequence[ISA95ParameterDataType] | None) -> None: ...
    @property
    def personnelActuals(self) -> list[ISA95PersonnelDataType] | None: ...
    @personnelActuals.setter
    def personnelActuals(self, value: Sequence[ISA95PersonnelDataType] | None) -> None: ...
    @property
    def equipmentActuals(self) -> list[ISA95EquipmentDataType] | None: ...
    @equipmentActuals.setter
    def equipmentActuals(self, value: Sequence[ISA95EquipmentDataType] | None) -> None: ...
    @property
    def physicalAssetActuals(self) -> list[ISA95PhysicalAssetDataType] | None: ...
    @physicalAssetActuals.setter
    def physicalAssetActuals(self, value: Sequence[ISA95PhysicalAssetDataType] | None) -> None: ...
    @property
    def materialActuals(self) -> list[ISA95MaterialDataType] | None: ...
    @materialActuals.setter
    def materialActuals(self, value: Sequence[ISA95MaterialDataType] | None) -> None: ...

class ISA95JobOrderAndStateDataType(ns0.datatypes.Structure):
    """Defines the information needed to schedule and execute a job."""

    @property
    def jobOrder(self) -> ISA95JobOrderDataType: ...
    @jobOrder.setter
    def jobOrder(self, value: ISA95JobOrderDataType) -> None: ...
    @property
    def state(self) -> list[ISA95StateDataType]: ...
    @state.setter
    def state(self, value: Sequence[ISA95StateDataType]) -> None: ...
