# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.amb as amb

import o6.ns.di as di

import o6.ns.ia as ia

import o6.ns.machinery as machinery

import o6.ns.machinery_result as machinery_result

import o6.ns.ns0 as ns0

class CalibrationDataType(ns0.datatypes.Structure):
    """This structure contains the Calibration information. It is used as an input argument in SetCalibration method.
    Note: The input data sent in SetCalibration shall be updated in the respective parameters of the asset under Maintenance/Calibration."""

    @property
    def lastCalibration(self) -> o6.DateTime: ...
    @lastCalibration.setter
    def lastCalibration(self, value: o6.DateTime) -> None: ...
    @property
    def calibrationPlace(self) -> o6.String | None: ...
    @calibrationPlace.setter
    def calibrationPlace(self, value: o6.String | None) -> None: ...
    @property
    def nextCalibration(self) -> o6.DateTime | None: ...
    @nextCalibration.setter
    def nextCalibration(self, value: o6.DateTime | None) -> None: ...
    @property
    def calibrationValue(self) -> o6.Double | None: ...
    @calibrationValue.setter
    def calibrationValue(self, value: SupportsFloat | None) -> None: ...
    @property
    def sensorScale(self) -> o6.Double | None: ...
    @sensorScale.setter
    def sensorScale(self, value: SupportsFloat | None) -> None: ...
    @property
    def certificateUri(self) -> o6.String | None: ...
    @certificateUri.setter
    def certificateUri(self, value: o6.String | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...

class ResultCounterDataType(ns0.datatypes.Structure):
    """This structure is used to provide various types of counters associated to a Result. These counters are related to a joining process with sub-processes."""

    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def counterValue(self) -> o6.UInt32: ...
    @counterValue.setter
    def counterValue(self, value: _Integer) -> None: ...
    @property
    def counterType(self) -> o6.Int16: ...
    @counterType.setter
    def counterType(self, value: _Integer) -> None: ...

class ErrorInformationDataType(ns0.datatypes.Structure):
    """This structure represents the errors occurred in the system which are outside the boundaries of the given program."""

    @property
    def errorType(self) -> o6.Byte: ...
    @errorType.setter
    def errorType(self, value: _Integer) -> None: ...
    @property
    def errorId(self) -> o6.String | None: ...
    @errorId.setter
    def errorId(self, value: o6.String | None) -> None: ...
    @property
    def legacyError(self) -> o6.String | None: ...
    @legacyError.setter
    def legacyError(self, value: o6.String | None) -> None: ...
    @property
    def errorMessage(self) -> o6.LocalizedText | None: ...
    @errorMessage.setter
    def errorMessage(self, value: o6.LocalizedText | None) -> None: ...

class ResultValueDataType(ns0.datatypes.Structure):
    """It is used to report measurement values of the joining operation. Those are meant to characterize the quality of the process. It is used in JoiningResultDataType and StepResultDataType."""

    @property
    def measuredValue(self) -> o6.Double: ...
    @measuredValue.setter
    def measuredValue(self, value: SupportsFloat) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def resultEvaluation(self) -> machinery_result.datatypes.ResultEvaluationEnum | None: ...
    @resultEvaluation.setter
    def resultEvaluation(self, value: machinery_result.datatypes.ResultEvaluationEnum | None) -> None: ...
    @property
    def valueId(self) -> o6.String | None: ...
    @valueId.setter
    def valueId(self, value: o6.String | None) -> None: ...
    @property
    def valueTag(self) -> o6.Int16 | None: ...
    @valueTag.setter
    def valueTag(self, value: _Integer | None) -> None: ...
    @property
    def tracePointIndex(self) -> o6.Int32 | None: ...
    @tracePointIndex.setter
    def tracePointIndex(self, value: _Integer | None) -> None: ...
    @property
    def tracePointTimeOffset(self) -> o6.Double | None: ...
    @tracePointTimeOffset.setter
    def tracePointTimeOffset(self, value: SupportsFloat | None) -> None: ...
    @property
    def parameterIdList(self) -> list[o6.String] | None: ...
    @parameterIdList.setter
    def parameterIdList(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def violationType(self) -> o6.Byte | None: ...
    @violationType.setter
    def violationType(self, value: _Integer | None) -> None: ...
    @property
    def violationConsequence(self) -> o6.Byte | None: ...
    @violationConsequence.setter
    def violationConsequence(self, value: _Integer | None) -> None: ...
    @property
    def sensorId(self) -> o6.String | None: ...
    @sensorId.setter
    def sensorId(self, value: o6.String | None) -> None: ...
    @property
    def lowLimit(self) -> o6.Double | None: ...
    @lowLimit.setter
    def lowLimit(self, value: SupportsFloat | None) -> None: ...
    @property
    def highLimit(self) -> o6.Double | None: ...
    @highLimit.setter
    def highLimit(self, value: SupportsFloat | None) -> None: ...
    @property
    def targetValue(self) -> o6.Double | None: ...
    @targetValue.setter
    def targetValue(self, value: SupportsFloat | None) -> None: ...
    @property
    def resultStep(self) -> o6.String | None: ...
    @resultStep.setter
    def resultStep(self, value: o6.String | None) -> None: ...
    @property
    def physicalQuantity(self) -> o6.Byte | None: ...
    @physicalQuantity.setter
    def physicalQuantity(self, value: _Integer | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...

class KeyValueDataType(ns0.datatypes.Structure):
    """This structure is similar to 0:KeyValuePair which uses 0:TrimmedString instead of 0:QualifiedName."""

    @property
    def key(self) -> o6.String: ...
    @key.setter
    def key(self, value: o6.String) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class StepResultDataType(ns0.datatypes.Structure):
    """This structure represents the measurement values corresponding to a given step in the program. It is used in JoiningResultDataType."""

    @property
    def stepResultId(self) -> o6.String: ...
    @stepResultId.setter
    def stepResultId(self, value: o6.String) -> None: ...
    @property
    def programStepId(self) -> o6.String | None: ...
    @programStepId.setter
    def programStepId(self, value: o6.String | None) -> None: ...
    @property
    def programStep(self) -> o6.String | None: ...
    @programStep.setter
    def programStep(self, value: o6.String | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def resultEvaluation(self) -> machinery_result.datatypes.ResultEvaluationEnum | None: ...
    @resultEvaluation.setter
    def resultEvaluation(self, value: machinery_result.datatypes.ResultEvaluationEnum | None) -> None: ...
    @property
    def startTimeOffset(self) -> o6.Double | None: ...
    @startTimeOffset.setter
    def startTimeOffset(self, value: SupportsFloat | None) -> None: ...
    @property
    def stepTraceId(self) -> o6.String | None: ...
    @stepTraceId.setter
    def stepTraceId(self, value: o6.String | None) -> None: ...
    @property
    def stepResultValues(self) -> list[ResultValueDataType] | None: ...
    @stepResultValues.setter
    def stepResultValues(self, value: Sequence[ResultValueDataType] | None) -> None: ...

class EntityDataType(ns0.datatypes.Structure):
    """This structure provides the identification data for a given entity in the system."""

    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.String | None: ...
    @description.setter
    def description(self, value: o6.String | None) -> None: ...
    @property
    def entityId(self) -> o6.String: ...
    @entityId.setter
    def entityId(self, value: o6.String) -> None: ...
    @property
    def entityOriginId(self) -> o6.String | None: ...
    @entityOriginId.setter
    def entityOriginId(self, value: o6.String | None) -> None: ...
    @property
    def isExternal(self) -> o6.Boolean | None: ...
    @isExternal.setter
    def isExternal(self, value: _Boolean | None) -> None: ...
    @property
    def entityType(self) -> o6.Int16: ...
    @entityType.setter
    def entityType(self, value: _Integer) -> None: ...

class TraceDataType(ns0.datatypes.Structure):
    """It is a base type to encapsulate common data for a Trace."""

    @property
    def traceId(self) -> o6.String: ...
    @traceId.setter
    def traceId(self, value: o6.String) -> None: ...
    @property
    def resultId(self) -> o6.String: ...
    @resultId.setter
    def resultId(self, value: o6.String) -> None: ...

class TraceContentDataType(ns0.datatypes.Structure):
    """It is to describe the trace samples for a given program step. It is used in StepTraceDataType."""

    @property
    def values(self) -> list[o6.Double]: ...
    @values.setter
    def values(self, value: Sequence[SupportsFloat]) -> None: ...
    @property
    def sensorId(self) -> o6.String | None: ...
    @sensorId.setter
    def sensorId(self, value: o6.String | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.String | None: ...
    @description.setter
    def description(self, value: o6.String | None) -> None: ...
    @property
    def physicalQuantity(self) -> o6.Byte | None: ...
    @physicalQuantity.setter
    def physicalQuantity(self, value: _Integer | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...

class StepTraceDataType(ns0.datatypes.Structure):
    """It is to describe of the trace for a given program step. It is used in JoiningTraceDataType."""

    @property
    def stepTraceId(self) -> o6.String: ...
    @stepTraceId.setter
    def stepTraceId(self, value: o6.String) -> None: ...
    @property
    def stepResultId(self) -> o6.String: ...
    @stepResultId.setter
    def stepResultId(self, value: o6.String) -> None: ...
    @property
    def numberOfTracePoints(self) -> o6.UInt32: ...
    @numberOfTracePoints.setter
    def numberOfTracePoints(self, value: _Integer) -> None: ...
    @property
    def samplingInterval(self) -> o6.Double | None: ...
    @samplingInterval.setter
    def samplingInterval(self, value: SupportsFloat | None) -> None: ...
    @property
    def startTimeOffset(self) -> o6.Double | None: ...
    @startTimeOffset.setter
    def startTimeOffset(self, value: SupportsFloat | None) -> None: ...
    @property
    def stepTraceContent(self) -> list[TraceContentDataType]: ...
    @stepTraceContent.setter
    def stepTraceContent(self, value: Sequence[TraceContentDataType]) -> None: ...

class JoiningTraceDataType(TraceDataType):
    """This structure is to describe the content of traces for all the steps in the given program. It is used in JoiningResultDataType."""

    @property
    def traceId(self) -> o6.String: ...
    @traceId.setter
    def traceId(self, value: o6.String) -> None: ...
    @property
    def resultId(self) -> o6.String: ...
    @resultId.setter
    def resultId(self, value: o6.String) -> None: ...
    @property
    def stepTraces(self) -> list[StepTraceDataType]: ...
    @stepTraces.setter
    def stepTraces(self, value: Sequence[StepTraceDataType]) -> None: ...

class JoiningResultDataType(ns0.datatypes.Structure):
    """This structure represents the data associated with Joining Result and the corresponding measurement values."""

    @property
    def failureReason(self) -> o6.Byte | None: ...
    @failureReason.setter
    def failureReason(self, value: _Integer | None) -> None: ...
    @property
    def overallResultValues(self) -> list[ResultValueDataType]: ...
    @overallResultValues.setter
    def overallResultValues(self, value: Sequence[ResultValueDataType]) -> None: ...
    @property
    def stepResults(self) -> list[StepResultDataType] | None: ...
    @stepResults.setter
    def stepResults(self, value: Sequence[StepResultDataType] | None) -> None: ...
    @property
    def errors(self) -> list[ErrorInformationDataType] | None: ...
    @errors.setter
    def errors(self, value: Sequence[ErrorInformationDataType] | None) -> None: ...
    @property
    def failingStepResultId(self) -> o6.String | None: ...
    @failingStepResultId.setter
    def failingStepResultId(self, value: o6.String | None) -> None: ...
    @property
    def trace(self) -> JoiningTraceDataType | None: ...
    @trace.setter
    def trace(self, value: JoiningTraceDataType | None) -> None: ...

class DesignValueDataType(ns0.datatypes.Structure):
    """This structure provides the design value for a given physical quantity. It is used in JointDesignDataType."""

    @property
    def physicalQuantity(self) -> o6.Byte | None: ...
    @physicalQuantity.setter
    def physicalQuantity(self, value: _Integer | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def designValue(self) -> Any | None: ...
    @designValue.setter
    def designValue(self, value: Any | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...

class SignalDataType(ns0.datatypes.Structure):
    """This structure contains the signal information which is used in SetIOSignals and GetIOSignals methods."""

    @property
    def signalId(self) -> o6.String: ...
    @signalId.setter
    def signalId(self, value: o6.String) -> None: ...
    @property
    def signalValue(self) -> o6.ExtensionObject: ...
    @signalValue.setter
    def signalValue(self, value: Any) -> None: ...
    @property
    def signalDescription(self) -> o6.String: ...
    @signalDescription.setter
    def signalDescription(self, value: o6.String) -> None: ...
    @property
    def signalType(self) -> o6.Int16: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...

class JoiningResultMetaDataType(machinery_result.datatypes.ResultMetaDataType):
    """This structure is a subtype of ResultMetaDataType. It is used to define additional meta data of a Result in a joining system."""

    @property
    def resultId(self) -> o6.String: ...
    @resultId.setter
    def resultId(self, value: o6.String) -> None: ...
    @property
    def hasTransferableDataOnFile(self) -> o6.Boolean | None: ...
    @hasTransferableDataOnFile.setter
    def hasTransferableDataOnFile(self, value: _Boolean | None) -> None: ...
    @property
    def isPartial(self) -> o6.Boolean | None: ...
    @isPartial.setter
    def isPartial(self, value: _Boolean | None) -> None: ...
    @property
    def isSimulated(self) -> o6.Boolean | None: ...
    @isSimulated.setter
    def isSimulated(self, value: _Boolean | None) -> None: ...
    @property
    def resultState(self) -> o6.Int32 | None: ...
    @resultState.setter
    def resultState(self, value: _Integer | None) -> None: ...
    @property
    def stepId(self) -> o6.String | None: ...
    @stepId.setter
    def stepId(self, value: o6.String | None) -> None: ...
    @property
    def partId(self) -> o6.String | None: ...
    @partId.setter
    def partId(self, value: o6.String | None) -> None: ...
    @property
    def externalRecipeId(self) -> o6.String | None: ...
    @externalRecipeId.setter
    def externalRecipeId(self, value: o6.String | None) -> None: ...
    @property
    def internalRecipeId(self) -> o6.String | None: ...
    @internalRecipeId.setter
    def internalRecipeId(self, value: o6.String | None) -> None: ...
    @property
    def productId(self) -> o6.String | None: ...
    @productId.setter
    def productId(self, value: o6.String | None) -> None: ...
    @property
    def externalConfigurationId(self) -> o6.String | None: ...
    @externalConfigurationId.setter
    def externalConfigurationId(self, value: o6.String | None) -> None: ...
    @property
    def internalConfigurationId(self) -> o6.String | None: ...
    @internalConfigurationId.setter
    def internalConfigurationId(self, value: o6.String | None) -> None: ...
    @property
    def jobId(self) -> o6.String | None: ...
    @jobId.setter
    def jobId(self, value: o6.String | None) -> None: ...
    @property
    def creationTime(self) -> o6.DateTime | None: ...
    @creationTime.setter
    def creationTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def processingTimes(self) -> machinery_result.datatypes.ProcessingTimesDataType | None: ...
    @processingTimes.setter
    def processingTimes(self, value: machinery_result.datatypes.ProcessingTimesDataType | None) -> None: ...
    @property
    def resultUri(self) -> list[o6.String] | None: ...
    @resultUri.setter
    def resultUri(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def resultEvaluation(self) -> machinery_result.datatypes.ResultEvaluationEnum | None: ...
    @resultEvaluation.setter
    def resultEvaluation(self, value: machinery_result.datatypes.ResultEvaluationEnum | None) -> None: ...
    @property
    def resultEvaluationCode(self) -> o6.Int64 | None: ...
    @resultEvaluationCode.setter
    def resultEvaluationCode(self, value: _Integer | None) -> None: ...
    @property
    def resultEvaluationDetails(self) -> o6.LocalizedText | None: ...
    @resultEvaluationDetails.setter
    def resultEvaluationDetails(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def fileFormat(self) -> list[o6.String] | None: ...
    @fileFormat.setter
    def fileFormat(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def joiningTechnology(self) -> o6.LocalizedText | None: ...
    @joiningTechnology.setter
    def joiningTechnology(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def sequenceNumber(self) -> o6.UInt64 | None: ...
    @sequenceNumber.setter
    def sequenceNumber(self, value: _Integer | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def classification(self) -> o6.Byte | None: ...
    @classification.setter
    def classification(self, value: _Integer | None) -> None: ...
    @property
    def operationMode(self) -> o6.Byte | None: ...
    @operationMode.setter
    def operationMode(self, value: _Integer | None) -> None: ...
    @property
    def assemblyType(self) -> o6.Byte | None: ...
    @assemblyType.setter
    def assemblyType(self, value: _Integer | None) -> None: ...
    @property
    def associatedEntities(self) -> list[EntityDataType] | None: ...
    @associatedEntities.setter
    def associatedEntities(self, value: Sequence[EntityDataType] | None) -> None: ...
    @property
    def resultCounters(self) -> list[ResultCounterDataType] | None: ...
    @resultCounters.setter
    def resultCounters(self, value: Sequence[ResultCounterDataType] | None) -> None: ...
    @property
    def interventionType(self) -> o6.Byte | None: ...
    @interventionType.setter
    def interventionType(self, value: _Integer | None) -> None: ...
    @property
    def isGeneratedOffline(self) -> o6.Boolean | None: ...
    @isGeneratedOffline.setter
    def isGeneratedOffline(self, value: _Boolean | None) -> None: ...
    @property
    def extendedMetaData(self) -> list[KeyValueDataType] | None: ...
    @extendedMetaData.setter
    def extendedMetaData(self, value: Sequence[KeyValueDataType] | None) -> None: ...

class JointComponentDataType(ns0.datatypes.Structure):
    """This structure is the base container for any joint component such as Bolt, Rivet, Gasket, Glue string, etc.
    Note: The concrete definition of joint component is not defined in this version of the specification."""

    @property
    def jointComponentId(self) -> o6.String: ...
    @jointComponentId.setter
    def jointComponentId(self, value: o6.String) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def manufacturer(self) -> o6.LocalizedText | None: ...
    @manufacturer.setter
    def manufacturer(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def manufacturerUri(self) -> o6.String | None: ...
    @manufacturerUri.setter
    def manufacturerUri(self, value: o6.String | None) -> None: ...
    @property
    def jointComponentContent(self) -> Any | None: ...
    @jointComponentContent.setter
    def jointComponentContent(self, value: Any | None) -> None: ...

class ReportedValueDataType(ns0.datatypes.Structure):
    """This structure provides the given value and corresponding limits for a given physical quantity (if applicable)."""

    @property
    def physicalQuantity(self) -> o6.Byte | None: ...
    @physicalQuantity.setter
    def physicalQuantity(self, value: _Integer | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def currentValue(self) -> Any: ...
    @currentValue.setter
    def currentValue(self, value: Any) -> None: ...
    @property
    def previousValue(self) -> Any | None: ...
    @previousValue.setter
    def previousValue(self, value: Any | None) -> None: ...
    @property
    def lowLimit(self) -> o6.Double | None: ...
    @lowLimit.setter
    def lowLimit(self, value: SupportsFloat | None) -> None: ...
    @property
    def highLimit(self) -> o6.Double | None: ...
    @highLimit.setter
    def highLimit(self, value: SupportsFloat | None) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation | None: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation | None) -> None: ...

class JoiningProcessMetaDataType(ns0.datatypes.Structure):
    """This structure provides the meta data which describes the joining process."""

    @property
    def joiningProcessId(self) -> o6.String: ...
    @joiningProcessId.setter
    def joiningProcessId(self, value: o6.String) -> None: ...
    @property
    def joiningProcessOriginId(self) -> o6.String | None: ...
    @joiningProcessOriginId.setter
    def joiningProcessOriginId(self, value: o6.String | None) -> None: ...
    @property
    def creationTime(self) -> o6.DateTime | None: ...
    @creationTime.setter
    def creationTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def lastUpdatedTime(self) -> o6.DateTime | None: ...
    @lastUpdatedTime.setter
    def lastUpdatedTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def joiningTechnology(self) -> o6.LocalizedText | None: ...
    @joiningTechnology.setter
    def joiningTechnology(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def classification(self) -> o6.Int16 | None: ...
    @classification.setter
    def classification(self, value: _Integer | None) -> None: ...
    @property
    def associatedEntities(self) -> list[EntityDataType] | None: ...
    @associatedEntities.setter
    def associatedEntities(self, value: Sequence[EntityDataType] | None) -> None: ...

class JoiningProcessDataType(ns0.datatypes.Structure):
    """This structure provides the base container for any joining process in a joining system.
    Note: This specification defines the meta data of a JoiningProcess, and the actual content of the Joining Process is application specific."""

    @property
    def joiningProcessMetaData(self) -> JoiningProcessMetaDataType: ...
    @joiningProcessMetaData.setter
    def joiningProcessMetaData(self, value: JoiningProcessMetaDataType) -> None: ...
    @property
    def joiningProcessContent(self) -> list[Any]: ...
    @joiningProcessContent.setter
    def joiningProcessContent(self, value: Sequence[Any]) -> None: ...

class JointDesignDataType(ns0.datatypes.Structure):
    """This structure provides the design information of a given joint."""

    @property
    def jointDesignId(self) -> o6.String: ...
    @jointDesignId.setter
    def jointDesignId(self, value: o6.String) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def jointDesignContent(self) -> list[DesignValueDataType] | None: ...
    @jointDesignContent.setter
    def jointDesignContent(self, value: Sequence[DesignValueDataType] | None) -> None: ...
    @property
    def jointComponentIdList(self) -> list[o6.String] | None: ...
    @jointComponentIdList.setter
    def jointComponentIdList(self, value: Sequence[o6.String] | None) -> None: ...

class JointDataType(ns0.datatypes.Structure):
    """This structure provides the joint information. Joint is the physical outcome of the joining operation which determines the properties of the point where multiple parts are assembled."""

    @property
    def jointId(self) -> o6.String: ...
    @jointId.setter
    def jointId(self, value: o6.String) -> None: ...
    @property
    def jointOriginId(self) -> o6.String | None: ...
    @jointOriginId.setter
    def jointOriginId(self, value: o6.String | None) -> None: ...
    @property
    def jointDesignId(self) -> o6.String | None: ...
    @jointDesignId.setter
    def jointDesignId(self, value: o6.String | None) -> None: ...
    @property
    def creationTime(self) -> o6.DateTime | None: ...
    @creationTime.setter
    def creationTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def lastUpdatedTime(self) -> o6.DateTime | None: ...
    @lastUpdatedTime.setter
    def lastUpdatedTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def classification(self) -> o6.Int16 | None: ...
    @classification.setter
    def classification(self, value: _Integer | None) -> None: ...
    @property
    def classificationDetails(self) -> o6.LocalizedText | None: ...
    @classificationDetails.setter
    def classificationDetails(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def jointStatus(self) -> o6.String | None: ...
    @jointStatus.setter
    def jointStatus(self, value: o6.String | None) -> None: ...
    @property
    def associatedEntities(self) -> list[EntityDataType] | None: ...
    @associatedEntities.setter
    def associatedEntities(self, value: Sequence[EntityDataType] | None) -> None: ...
    @property
    def joiningTechnology(self) -> o6.LocalizedText | None: ...
    @joiningTechnology.setter
    def joiningTechnology(self, value: o6.LocalizedText | None) -> None: ...

class JoiningProcessIdentificationDataType(ns0.datatypes.Structure):
    """This structure contains the identification information of a Joining Process. It is used in set of methods defined in JoiningProcessManagementType."""

    @property
    def joiningProcessId(self) -> o6.String | None: ...
    @joiningProcessId.setter
    def joiningProcessId(self, value: o6.String | None) -> None: ...
    @property
    def joiningProcessOriginId(self) -> o6.String | None: ...
    @joiningProcessOriginId.setter
    def joiningProcessOriginId(self, value: o6.String | None) -> None: ...
    @property
    def selectionName(self) -> o6.String | None: ...
    @selectionName.setter
    def selectionName(self, value: o6.String | None) -> None: ...
