# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Generated OPC UA mdis namespace declarations."""

from __future__ import annotations

from typing import Any, TYPE_CHECKING
import uuid
import o6
import o6.ns.ns0 as ns0
from . import reftypes as mdis_reftypes
from . import datatypes as mdis_datypes
from . import vartypes as mdis_vartypes

if TYPE_CHECKING:
    from o6.node import ObjectNode as _ObjectNode
    from o6.node import VariableNode as _VariableNode
else:
    _ObjectNode = object
    _VariableNode = object

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=196",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=195",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="Enable", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Disable the device (false), or enable the device (true)"))],
)
o6.call(nodeId="ns=mdis;i=195", browseName="ns=mdis;EnableDisable", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=196"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=884",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=883",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[5],
    value=[
        ns0.datatypes.Argument(
            name="Direction",
            dataType=o6.NodeId("ns=mdis;i=3"),
            valueRank=-1,
            description=o6.LocalizedText("The enumeration indicates whether the command is to open the valve or to close the valve"),
        ),
        ns0.datatypes.Argument(
            name="OverrideInterlock",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any defeat able interlocks"),
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
        ns0.datatypes.Argument(
            name="Signature", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicating if a profile should be generated by this move command request")
        ),
        ns0.datatypes.Argument(
            name="ShutdownRequest", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicates that this command is a shutdown move command")
        ),
    ],
)
o6.call(nodeId="ns=mdis;i=883", browseName="ns=mdis;Move", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=884"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1156",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1155",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[3],
    value=[
        ns0.datatypes.Argument(name="Position", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("A number (in percent) indicating the percent open")),
        ns0.datatypes.Argument(
            name="OverrideInterlocks",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any defeat able interlocks"),
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
    ],
)
o6.call(nodeId="ns=mdis;i=1155", browseName="ns=mdis;Move", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1156"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1158",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1157",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[4],
    value=[
        ns0.datatypes.Argument(
            name="Direction",
            dataType=o6.NodeId("ns=mdis;i=701"),
            valueRank=-1,
            description=o6.LocalizedText("The direction for the valve, true is opening a valve, false if closing the valve"),
        ),
        ns0.datatypes.Argument(name="Steps", dataType=o6.UInt16, valueRank=-1, description=o6.LocalizedText("The number of steps to open/close the valve")),
        ns0.datatypes.Argument(
            name="OverrideInterlocks",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any defeat able interlocks"),
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
    ],
)
o6.call(nodeId="ns=mdis;i=1157", browseName="ns=mdis;Step", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1158"]))


@o6.objecttype(
    nodeId="ns=mdis;i=194",
    browseName="ns=mdis;MDISBaseObjectType",
    displayName="MDISBaseObjectType",
    description="The definition of a MDIS base Object type from which all other object types are derived",
    isAbstract=True,
)
class MDISBaseObjectType(ns0.objtypes.BaseObjectType):
    enableDisable: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=195"])
    enabled: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=476", browseName="ns=mdis;Enabled", dataType=o6.Boolean)
    )
    fault: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=489", browseName="ns=mdis;Fault", dataType=o6.Boolean))
    faultCode: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1165", browseName="ns=mdis;FaultCode", dataType=o6.UInt32)
    )
    tagId: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(
            nodeId="ns=mdis;i=197", browseName="ns=mdis;TagId", description="The id used in other parts of the system", displayName="Tag ID", dataType=o6.String
        )
    )
    warning: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=497", browseName="ns=mdis;Warning", dataType=o6.Boolean)
    )
    warningCode: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1166", browseName="ns=mdis;WarningCode", dataType=o6.UInt32)
    )


@o6.objecttype(
    nodeId="ns=mdis;i=889",
    browseName="ns=mdis;MDISDigitalInstrumentObjectType",
    displayName="MDISDigitalInstrumentObjectType",
    description="The definition of a MDIS standard Digital Instrument",
)
class MDISDigitalInstrumentObjectType(MDISBaseObjectType):
    state: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=970", browseName="ns=mdis;State", dataType=o6.Boolean))


@o6.objecttype(
    nodeId="ns=mdis;i=971", browseName="ns=mdis;MDISInstrumentObjectType", displayName="MDISInstrumentObjectType", description="The definition of a MDIS standard Instrument"
)
class MDISInstrumentObjectType(MDISBaseObjectType):
    hHSetPoint: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1062", browseName="ns=mdis;HHSetPoint", dataType=o6.Float, accessLevel=3, userAccessLevel=1)
    )
    hHlimit: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1058", browseName="ns=mdis;HHlimit", dataType=o6.Boolean)
    )
    hSetPoint: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1063", browseName="ns=mdis;HSetPoint", dataType=o6.Float, accessLevel=3, userAccessLevel=1)
    )
    hlimit: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1059", browseName="ns=mdis;Hlimit", dataType=o6.Boolean))
    lLSetPoint: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1065", browseName="ns=mdis;LLSetPoint", dataType=o6.Float, accessLevel=3, userAccessLevel=1)
    )
    lLlimit: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1061", browseName="ns=mdis;LLlimit", dataType=o6.Boolean)
    )
    lSetPoint: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1064", browseName="ns=mdis;LSetPoint", dataType=o6.Float, accessLevel=3, userAccessLevel=1)
    )
    llimit: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1060", browseName="ns=mdis;Llimit", dataType=o6.Boolean))
    processVariable: ns0.vartypes.AnalogItemType


@o6.objecttype(
    nodeId="ns=mdis;i=1214",
    browseName="ns=mdis;MDISDiscreteInstrumentObjectType",
    displayName="MDISDiscreteInstrumentObjectType",
    description="The definition of a MDIS standard Discrete Instrument",
)
class MDISDiscreteInstrumentObjectType(MDISBaseObjectType):
    state: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1223", browseName="ns=mdis;State", dataType=o6.UInt32))


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1241",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1240",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="State", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean state that is being written to the object"))],
)
o6.call(nodeId="ns=mdis;i=1240", browseName="ns=mdis;WriteState", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1241"]))


@o6.objecttype(
    nodeId="ns=mdis;i=1230", browseName="ns=mdis;MDISDigitalOutObjectType", displayName="MDISDigitalOutObjectType", description="The definition of a MDIS standard Digital Output"
)
class MDISDigitalOutObjectType(MDISDigitalInstrumentObjectType):
    writeState: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1240"])


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1253",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1252",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="State", dataType=o6.UInt32, valueRank=-1, description=o6.LocalizedText("Unit32 state that is being written to the object"))],
)
o6.call(nodeId="ns=mdis;i=1252", browseName="ns=mdis;WriteValue", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1253"]))


@o6.objecttype(
    nodeId="ns=mdis;i=1242",
    browseName="ns=mdis;MDISDiscreteOutObjectType",
    displayName="MDISDiscreteOutObjectType",
    description="The definition of a MDIS standard Discrete Output",
)
class MDISDiscreteOutObjectType(MDISDiscreteInstrumentObjectType):
    writeValue: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1252"])


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1278",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1277",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="Value", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("Float value that is being written to the object"))],
)
o6.call(nodeId="ns=mdis;i=1277", browseName="ns=mdis;WriteValue", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1278"]))


@o6.objecttype(
    nodeId="ns=mdis;i=1254",
    browseName="ns=mdis;MDISInstrumentOutObjectType",
    displayName="MDISInstrumentOutObjectType",
    description="The definition of a MDIS standard Instrument Output",
)
class MDISInstrumentOutObjectType(MDISInstrumentObjectType):
    writeValue: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1277"])


@o6.objecttype(nodeId="ns=mdis;i=794", browseName="ns=mdis;MDISValveObjectType", displayName="MDISValveObjectType", description="The definition of a MDIS standard Valve Object")
class MDISValveObjectType(MDISBaseObjectType):
    closeTimeDuration: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=888", browseName="ns=mdis;CloseTimeDuration", dataType=ns0.datatypes.Duration)
    )
    commandRejected: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=876", browseName="ns=mdis;CommandRejected", dataType=o6.Boolean)
    )
    defeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=882", browseName="ns=mdis;DefeatableCloseInterlock", dataType=o6.Boolean)
    )
    defeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=880", browseName="ns=mdis;DefeatableOpenInterlock", dataType=o6.Boolean)
    )
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=1280", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    langleValveSignatureRangle: ns0.objtypes.FileType | None
    lastCommand: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=878", browseName="ns=mdis;LastCommand", dataType=mdis_datypes.CommandEnum)
    )
    move: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=883"])
    nonDefeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=881", browseName="ns=mdis;NonDefeatableCloseInterlock", dataType=o6.Boolean)
    )
    nonDefeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=879", browseName="ns=mdis;NonDefeatableOpenInterlock", dataType=o6.Boolean)
    )
    openTimeDuration: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=887", browseName="ns=mdis;OpenTimeDuration", dataType=ns0.datatypes.Duration)
    )
    position: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=875", browseName="ns=mdis;Position", dataType=mdis_datypes.ValvePositionEnum)
    )
    signatureRequestStatus: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=877", browseName="ns=mdis;SignatureRequestStatus", dataType=mdis_datypes.SignatureStatusEnum)
    )


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1285",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1284",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="Position", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("A number (in percent) indicating the percent open"))],
)
o6.call(nodeId="ns=mdis;i=1284", browseName="ns=mdis;SetCalculatedPosition", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1285"]))


@o6.objecttype(nodeId="ns=mdis;i=1066", browseName="ns=mdis;MDISChokeObjectType", displayName="MDISChokeObjectType", description="The definition of a MDIS standard Choke Object")
class MDISChokeObjectType(MDISBaseObjectType):
    abort: o6.node.MethodNode = o6.hasComponent(o6.call(nodeId="ns=mdis;i=1159", browseName="ns=mdis;Abort"))
    calculatedPosition: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1147", browseName="ns=mdis;CalculatedPosition", dataType=o6.Float)
    )
    commandRejected: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1150", browseName="ns=mdis;CommandRejected", dataType=o6.Boolean)
    )
    defeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1154", browseName="ns=mdis;DefeatableCloseInterlock", dataType=o6.Boolean)
    )
    defeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1152", browseName="ns=mdis;DefeatableOpenInterlock", dataType=o6.Boolean)
    )
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=1281", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    move: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1155"])
    moving: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1149", browseName="ns=mdis;Moving", dataType=mdis_datypes.ChokeMoveEnum)
    )
    nonDefeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1153", browseName="ns=mdis;NonDefeatableCloseInterlock", dataType=o6.Boolean)
    )
    nonDefeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1151", browseName="ns=mdis;NonDefeatableOpenInterlock", dataType=o6.Boolean)
    )
    positionInSteps: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1148", browseName="ns=mdis;PositionInSteps", dataType=o6.Int16)
    )
    setCalculatedPosition: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1284"])
    setCalculatedPositionStatus: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=1314", browseName="ns=mdis;SetCalculatedPositionStatus", dataType=mdis_datypes.SetCalculatedPositionEnum)
    )
    step: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=1157"])
    stepDurationClose: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1163", browseName="ns=mdis;StepDurationClose", dataType=ns0.datatypes.Duration)
    )
    stepDurationOpen: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1162", browseName="ns=mdis;StepDurationOpen", dataType=ns0.datatypes.Duration)
    )
    totalSteps: ns0.vartypes.PropertyType | None = o6.hasProperty(ns0.vartypes.PropertyType(nodeId="ns=mdis;i=1164", browseName="ns=mdis;TotalSteps", dataType=o6.UInt16))


@o6.objecttype(
    nodeId="ns=mdis;i=1315",
    browseName="ns=mdis;MDISAggregateObjectType",
    displayName="MDISAggregateObjectType",
    description="The definition of a MDIS standard Aggregate Object",
    isAbstract=True,
)
class MDISAggregateObjectType(MDISBaseObjectType):
    langleCIMVPlaceholderRangle: MDISCIMVObjectType | None
    langleChokePlaceholderRangle: MDISChokeObjectType | None
    langleCounterPlaceholderRangle: MDISCounterObjectType | None
    langleDigitalArbitrationPlaceholderRangle: MDISDigitalArbitrationObjectType | None
    langleDigitalOutPlaceholderRangle: MDISDigitalOutObjectType | None
    langleDigitalPlaceholderRangle: MDISDigitalInstrumentObjectType | None
    langleDiscreteArbitrationPlaceholderRangle: MDISDiscreteArbitrationObjectType | None
    langleDiscreteOutPlaceholderRangle: MDISDiscreteOutObjectType | None
    langleDiscretePlaceholderRangle: MDISDiscreteInstrumentObjectType | None
    langleElectricChokePlaceholderRangle: MDISElectricChokeObjectType | None
    langleInstrumentArbitrationPlaceholderRangle: MDISInstrumentArbitrationObjectType | None
    langleInstrumentOutPlaceholderRangle: MDISInstrumentOutObjectType | None
    langleInstrumentPlaceholderRangle: MDISInstrumentObjectType | None
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=1465", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    langleMotorPlaceholderRangle: MDISMotorObjectType | None
    langleValvePlaceholderRangle: MDISValveObjectType | None


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=1470",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=1469",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="TargetTime", dataType=ns0.datatypes.UtcTime, valueRank=-1, description=o6.LocalizedText("The UTC Time that the Server shall use to update its internal clock.")
        )
    ],
)
o6.call(nodeId="ns=mdis;i=1469", browseName="ns=mdis;SetTime", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=1470"]))


@o6.objecttype(
    nodeId="ns=mdis;i=1468", browseName="ns=mdis;MDISTimeSyncObjectType", displayName="MDISTimeSyncObjectType", description="The definition of a MDIS standard Time Sync object"
)
class MDISTimeSyncObjectType(ns0.objtypes.BaseObjectType):
    setTime: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=1469"])


@o6.objecttype(
    nodeId="ns=mdis;i=1471",
    browseName="ns=mdis;MDISInformationObjectType",
    displayName="MDISInformationObjectType",
    description="The definition of a MDIS standard Information object",
)
class MDISInformationObjectType(ns0.objtypes.BaseObjectType):
    mDISVersion: mdis_vartypes.MDISVersionVariableType
    signatures: ns0.objtypes.FolderType | None = o6.hasComponent(ns0.objtypes.FolderType(nodeId="ns=mdis;i=1475", browseName="ns=mdis;Signatures"))
    timeSynchronization: MDISTimeSyncObjectType | None


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15029",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15028",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="ArbitrationMode",
            dataType=o6.NodeId("ns=mdis;i=15009"),
            valueRank=-1,
            description=o6.LocalizedText("ArbitrationMode enumeration value Variable, that defines the new arbitration mode"),
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15028", browseName="ns=mdis;SetArbitrationMode", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15029"]))


@o6.objecttype(
    nodeId="ns=mdis;i=15015",
    browseName="ns=mdis;MDISDigitalArbitrationObjectType",
    displayName="MDISDigitalArbitrationObjectType",
    description="The definition of a MDIS standard Digital Arbitration",
)
class MDISDigitalArbitrationObjectType(MDISDigitalInstrumentObjectType):
    arbitrationMode: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15027", browseName="ns=mdis;ArbitrationMode", dataType=mdis_datypes.ArbitrationModeEnum)
    )
    setArbitrationMode: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15028"])
    sourceA: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15025", browseName="ns=mdis;SourceA", dataType=o6.Boolean))
    sourceB: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15026", browseName="ns=mdis;SourceB", dataType=o6.Boolean))


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15075",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15074",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="ArbitrationMode",
            dataType=o6.NodeId("ns=mdis;i=15009"),
            valueRank=-1,
            description=o6.LocalizedText("ArbitrationMode enumeration value Variable, that defines the new arbitration mode"),
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15074", browseName="ns=mdis;SetArbitrationMode", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15075"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15093",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15092",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[3],
    value=[
        ns0.datatypes.Argument(name="Position", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("A number (in percent) indicating the percent open")),
        ns0.datatypes.Argument(
            name="OverrideInterlocks",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any defeat able interlocks"),
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
    ],
)
o6.call(nodeId="ns=mdis;i=15092", browseName="ns=mdis;Move", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15093"]))


@o6.objecttype(
    nodeId="ns=mdis;i=15076",
    browseName="ns=mdis;MDISElectricChokeObjectType",
    displayName="MDISElectricChokeObjectType",
    description="The definition of a MDIS standard Electric Choke Object",
)
class MDISElectricChokeObjectType(MDISBaseObjectType):
    abort: o6.node.MethodNode = o6.hasComponent(o6.call(nodeId="ns=mdis;i=15094", browseName="ns=mdis;Abort"))
    actualPosition: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15085", browseName="ns=mdis;ActualPosition", dataType=o6.Float)
    )
    commandRejected: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15087", browseName="ns=mdis;CommandRejected", dataType=o6.Boolean)
    )
    defeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15091", browseName="ns=mdis;DefeatableCloseInterlock", dataType=o6.Boolean)
    )
    defeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15089", browseName="ns=mdis;DefeatableOpenInterlock", dataType=o6.Boolean)
    )
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=15095", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    move: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=15092"])
    moving: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15086", browseName="ns=mdis;Moving", dataType=mdis_datypes.ChokeMoveEnum)
    )
    nonDefeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15090", browseName="ns=mdis;NonDefeatableCloseInterlock", dataType=o6.Boolean)
    )
    nonDefeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15088", browseName="ns=mdis;NonDefeatableOpenInterlock", dataType=o6.Boolean)
    )


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15101",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15100",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="Initial", dataType=ns0.datatypes.Number, valueRank=-1, description=o6.LocalizedText("The value to initialize the Object Count to, default is 0")
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15100", browseName="ns=mdis;SetCount", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15101"]))


@o6.objecttype(
    nodeId="ns=mdis;i=15098",
    browseName="ns=mdis;MDISCounterObjectType",
    displayName="MDISCounterObjectType",
    description="The definition of a MDIS Counter object that is used in other Object types",
)
class MDISCounterObjectType(ns0.objtypes.BaseObjectType):
    count: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15099", browseName="ns=mdis;Count", dataType=ns0.datatypes.Number)
    )
    setCount: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15100"])


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15167",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15166",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="Initial", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("The value to initialize the TotalFlow to"))],
)
o6.call(nodeId="ns=mdis;i=15166", browseName="ns=mdis;ResetTotalFlow", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15167"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15169",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15168",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[3],
    value=[
        ns0.datatypes.Argument(
            name="Mode", dataType=o6.NodeId("ns=mdis;i=15102"), valueRank=-1, description=o6.LocalizedText("Enumeration indicating the requested operation mode")
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
        ns0.datatypes.Argument(
            name="ShutdownRequest",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any interlocks"),
        ),
    ],
)
o6.call(nodeId="ns=mdis;i=15168", browseName="ns=mdis;SetOperationMode", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15169"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15171",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15170",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[3],
    value=[
        ns0.datatypes.Argument(
            name="FlowRate", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("Target flow rate. The CIMV will automatically maintain this target flow")
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
        ns0.datatypes.Argument(
            name="ShutdownRequest", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicates that this command is part of a shutdown sequence. ")
        ),
    ],
)
o6.call(nodeId="ns=mdis;i=15170", browseName="ns=mdis;SetFlowRate", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15171"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15173",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15172",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[3],
    value=[
        ns0.datatypes.Argument(
            name="Position", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("Target position as percent of open. The CIMV will automatically maintain this position")
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
        ns0.datatypes.Argument(
            name="ShutdownRequest",
            dataType=o6.Boolean,
            valueRank=-1,
            description=o6.LocalizedText("Boolean indicating if the open or close command should override any interlocks"),
        ),
    ],
)
o6.call(nodeId="ns=mdis;i=15172", browseName="ns=mdis;SetPosition", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15173"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15175",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15174",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[4],
    value=[
        ns0.datatypes.Argument(name="Direction", dataType=o6.NodeId("ns=mdis;i=15007"), valueRank=-1, description=o6.LocalizedText("Direction to move &#8211; Open or Close")),
        ns0.datatypes.Argument(
            name="Delta", dataType=o6.Float, valueRank=-1, description=o6.LocalizedText("A relative change in position from the current position as a percent. ")
        ),
        ns0.datatypes.Argument(name="SEM", dataType=o6.NodeId("ns=mdis;i=5"), valueRank=-1, description=o6.LocalizedText("The selection of which SEM to send the command to")),
        ns0.datatypes.Argument(
            name="ShutdownRequest", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicates that this command is part of a shutdown sequence. ")
        ),
    ],
)
o6.call(nodeId="ns=mdis;i=15174", browseName="ns=mdis;SetManual", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15175"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15206",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15205",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="OverrideInterlocks", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicating if the command should override any interlocks")
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15205", browseName="ns=mdis;Start", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15206"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15208",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15207",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="OverrideInterlocks", dataType=o6.Boolean, valueRank=-1, description=o6.LocalizedText("Boolean indicating if the command should override any interlocks")
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15207", browseName="ns=mdis;Stop", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15208"]))

ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15210",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15209",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[ns0.datatypes.Argument(name="Mode", dataType=o6.NodeId("ns=mdis;i=15013"), valueRank=-1, description=o6.LocalizedText("Mode to operate in (i.e. Auto or Manual)"))],
)
o6.call(nodeId="ns=mdis;i=15209", browseName="ns=mdis;SetOperation", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15210"]))


@o6.objecttype(nodeId="ns=mdis;i=15114", browseName="ns=mdis;MDISCIMVObjectType", displayName="MDISCIMVObjectType", description="The definition of a MDIS standard CIMV Object")
class MDISCIMVObjectType(MDISBaseObjectType):
    abort: o6.node.MethodNode = o6.hasComponent(o6.call(nodeId="ns=mdis;i=15176", browseName="ns=mdis;Abort"))
    commandRejected: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15162", browseName="ns=mdis;CommandRejected", dataType=o6.Boolean)
    )
    deviceCurrent: ns0.vartypes.AnalogItemType | None
    flowRate: ns0.vartypes.AnalogItemType
    inletPressure: ns0.vartypes.AnalogItemType | None
    internalPressure: ns0.vartypes.AnalogItemType | None
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=15177", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    motorOperationsCount: MDISCounterObjectType | None
    moving: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15137", browseName="ns=mdis;Moving", dataType=mdis_datypes.CIMVMoveEnum)
    )
    nonDefeatableCloseInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15165", browseName="ns=mdis;NonDefeatableCloseInterlock", dataType=o6.Boolean)
    )
    nonDefeatableCommandInProgressInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15164", browseName="ns=mdis;NonDefeatableCommandInProgressInterlock", dataType=o6.Boolean)
    )
    nonDefeatableOpenInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15163", browseName="ns=mdis;NonDefeatableOpenInterlock", dataType=o6.Boolean)
    )
    operationMode: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15123", browseName="ns=mdis;OperationMode", dataType=mdis_datypes.CIMVOperationModeEnum)
    )
    outletPressure: ns0.vartypes.AnalogItemType | None
    position: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15136", browseName="ns=mdis;Position", dataType=o6.Float))
    resetTotalFlow: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15166"])
    setFlowRate: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=15170"])
    setManual: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15174"])
    setOperationMode: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=15168"])
    setPosition: o6.node.MethodNode = o6.hasComponent(o6.ns["ns=mdis;i=15172"])
    targetFlowRate: ns0.vartypes.AnalogItemType
    targetPosition: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15304", browseName="ns=mdis;TargetPosition", dataType=o6.Float)
    )
    totalFlow: ns0.vartypes.AnalogItemType | None
    totalMotorRuntime: MDISCounterObjectType | None


@o6.objecttype(nodeId="ns=mdis;i=15190", browseName="ns=mdis;MDISMotorObjectType", displayName="MDISMotorObjectType", description="The definition of a MDIS standard Motor Object")
class MDISMotorObjectType(MDISBaseObjectType):
    defeatableStartInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15396", browseName="ns=mdis;DefeatableStartInterlock", dataType=o6.Boolean)
    )
    defeatableStopInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15398", browseName="ns=mdis;DefeatableStopInterlock", dataType=o6.Boolean)
    )
    langleInterlockPlaceholderRangle: mdis_vartypes.InterlockVariableType | None = o6.reference(
        mdis_vartypes.InterlockVariableType(nodeId="ns=mdis;i=15211", browseName="ns=mdis;<InterlockPlaceholder>", modellingRule="OptionalPlaceholder", dataType=o6.Boolean),
        "ns=mdis;i=1183",
    )
    nonDefeatableStartInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15395", browseName="ns=mdis;NonDefeatableStartInterlock", dataType=o6.Boolean)
    )
    nonDefeatableStopInterlock: ns0.vartypes.BaseDataVariableType | None = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15397", browseName="ns=mdis;NonDefeatableStopInterlock", dataType=o6.Boolean)
    )
    operation: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15200", browseName="ns=mdis;Operation", dataType=mdis_datypes.MotorOperationEnum)
    )
    running: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15199", browseName="ns=mdis;Running", dataType=o6.Boolean))
    setOperation: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15209"])
    start: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15205"])
    stop: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15207"])


ns0.vartypes.PropertyType(
    nodeId="ns=mdis;i=15546",
    browseName="InputArguments",
    modellingRule="Mandatory",
    parent="ns=mdis;i=15545",
    referenceType=ns0.reftypes.HasProperty,
    dataType=ns0.datatypes.Argument,
    valueRank=1,
    arrayDimensions=[1],
    value=[
        ns0.datatypes.Argument(
            name="ArbitrationMode",
            dataType=o6.NodeId("ns=mdis;i=15009"),
            valueRank=-1,
            description=o6.LocalizedText("ArbitrationMode enumeration value Variable, that defines the new arbitration mode"),
        )
    ],
)
o6.call(nodeId="ns=mdis;i=15545", browseName="ns=mdis;SetArbitrationMode", inputArgs=o6.hasProperty(o6.ns["ns=mdis;i=15546"]))


@o6.objecttype(
    nodeId="ns=mdis;i=15032",
    browseName="ns=mdis;MDISDiscreteArbitrationObjectType",
    displayName="MDISDiscreteArbitrationObjectType",
    description="The definition of a MDIS standard Digital Arbitration",
)
class MDISDiscreteArbitrationObjectType(MDISDiscreteInstrumentObjectType):
    arbitrationMode: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15544", browseName="ns=mdis;ArbitrationMode", dataType=mdis_datypes.ArbitrationModeEnum)
    )
    setArbitrationMode: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15545"])
    sourceA: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15042", browseName="ns=mdis;SourceA", dataType=o6.UInt32))
    sourceB: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15043", browseName="ns=mdis;SourceB", dataType=o6.UInt32))


@o6.objecttype(
    nodeId="ns=mdis;i=15547",
    browseName="ns=mdis;MDISInstrumentArbitrationObjectType",
    displayName="MDISInstrumentArbitrationObjectType",
    description="The definition of a MDIS standard Instrument Arbitration",
)
class MDISInstrumentArbitrationObjectType(MDISInstrumentObjectType):
    arbitrationMode: ns0.vartypes.BaseDataVariableType = o6.hasComponent(
        ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15072", browseName="ns=mdis;ArbitrationMode", dataType=mdis_datypes.ArbitrationModeEnum)
    )
    discrepancySetPoint: ns0.vartypes.PropertyType | None = o6.hasProperty(
        ns0.vartypes.PropertyType(nodeId="ns=mdis;i=15073", browseName="ns=mdis;DiscrepancySetPoint", dataType=o6.Float, accessLevel=3, userAccessLevel=1)
    )
    setArbitrationMode: o6.node.MethodNode | None = o6.hasComponent(o6.ns["ns=mdis;i=15074"])
    sourceA: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15070", browseName="ns=mdis;SourceA", dataType=o6.Float))
    sourceB: ns0.vartypes.BaseDataVariableType = o6.hasComponent(ns0.vartypes.BaseDataVariableType(nodeId="ns=mdis;i=15071", browseName="ns=mdis;SourceB", dataType=o6.Float))


del Any, TYPE_CHECKING, uuid, o6, ns0, mdis_reftypes, mdis_datypes, mdis_vartypes
