# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Deterministically compile the enabled NodeSet registry."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from functools import cache
import os
from pathlib import Path
import sys
from typing import Iterable
from xml.etree import ElementTree

from .registry import NODESETS

from .backend_python import (
    UnsupportedNodeSetError,
    generate_namespace_datatypes_stub,
    generate_namespace_package,
    generate_type_module,
    has_generated_datatypes,
)
from .frontend import ModelInput, UnsupportedFeature, load_nodeset

_ROOT = Path(__file__).resolve().parents[2]
_OUT_DIR = _ROOT / "o6" / "ns"
_UA_URI = "http://opcfoundation.org/UA/"
_GLOBAL_NAMESPACES_HEADER = """\
# AUTO-GENERATED by tools/nodeset_compiler/compile_all.py — DO NOT EDIT
#
# Canonical namespaces shipped with o6-python. Historical compatibility
# releases are generated only when required and are deliberately excluded.
from __future__ import annotations

_GLOBAL_NAMESPACES: tuple[tuple[str, str, str], ...] = (
"""
_COMPATIBILITY_MODELS = (
    (
        _ROOT / "nodesets/compat/irdi/1.00/Opc.Ua.IRDI.NodeSet2.xml",
        "irdi_v1_00",
    ),
    (
        _ROOT / "nodesets/compat/irdi/1.01.0/Opc.Ua.IRDI.NodeSet2.xml",
        "irdi_v1_01_0",
    ),
    (
        _ROOT / "deps/UA-Nodeset/Powertrain/powertraindictionary.nodeset2.xml",
        "irdi_v1_0_0",
    ),
)


@dataclass(frozen=True, order=True)
class ModelIdentity:
    uri: str
    version: str


@dataclass(frozen=True, order=True)
class ModelRequirement:
    uri: str
    version: str = ""


@dataclass(frozen=True)
class Specification:
    path: Path
    shortname: str
    identity: ModelIdentity
    requirements: tuple[ModelRequirement, ...]
    supplementary_paths: tuple[Path, ...] = ()

    @property
    def uri(self) -> str:
        return self.identity.uri

    @property
    def version(self) -> str:
        return self.identity.version

    @property
    def required_uris(self) -> tuple[str, ...]:
        return tuple(requirement.uri for requirement in self.requirements)

    @property
    def paths(self) -> tuple[Path, ...]:
        return (self.path, *self.supplementary_paths)

    @property
    def model_input(self) -> ModelInput:
        return ModelInput(self.path, self.shortname)

    @property
    def dependency_input(self) -> ModelInput:
        return ModelInput(self.path, self.shortname, supplementary_paths=self.supplementary_paths)


@dataclass(frozen=True)
class CompileResult:
    specification: Specification
    status: str
    parsed: bool = False
    generated: bool = False
    compiled: bool = False
    unsupported: tuple[str, ...] = ()
    error: str | None = None


def _metadata(path: Path) -> tuple[ModelIdentity, tuple[ModelRequirement, ...]]:
    root = ElementTree.parse(path).getroot()
    models = root.find("{*}Models")
    model = models.find("{*}Model") if models is not None else None
    if model is not None and model.get("ModelUri"):
        uri = model.get("ModelUri")
        required = {
            ModelRequirement(
                child.get("ModelUri", ""),
                child.get("Version", ""),
            )
            for child in model.findall("{*}RequiredModel")
            if child.get("ModelUri")
        }
        identity = ModelIdentity(
            uri,
            model.get("Version", "1.0"),
        )
    else:
        namespace = root.find("{*}NamespaceUris/{*}Uri")
        uri = (namespace.text or "").strip() if namespace is not None else _UA_URI
        required = set()
        identity = ModelIdentity(uri, "1.0")
    assert uri is not None
    return identity, tuple(sorted(required))


def registry() -> tuple[Specification, ...]:
    specifications = []
    for entry in NODESETS:
        path = (_ROOT / entry.path).resolve()
        identity, required = _metadata(path)
        specifications.append(
            Specification(
                path,
                entry.shortname,
                identity,
                required,
            )
        )
    return tuple(specifications)


@cache
def compatibility_registry() -> tuple[Specification, ...]:
    """Return historical models available solely for dependency resolution."""
    specifications = []
    for path, shortname in _COMPATIBILITY_MODELS:
        identity, required = _metadata(path)
        specifications.append(Specification(path, shortname, identity, required))
    return tuple(specifications)


def _dependency_candidates(
    specifications: Iterable[Specification],
) -> tuple[Specification, ...]:
    """Add historical releases without making them default compilation targets."""
    selected = list(specifications)
    identities = {item.identity for item in selected}
    for specification in compatibility_registry():
        if specification.identity not in identities:
            selected.append(specification)
    return tuple(selected)


@cache
def _referenced_identifiers(specification: Specification, uri: str) -> frozenset[str]:
    identifiers: set[str] = set()
    for path in specification.paths:
        root = ElementTree.parse(path).getroot()
        namespaces = (
            _UA_URI,
            *(element.text or "" for element in root.findall("{*}NamespaceUris/{*}Uri")),
        )
        for reference in root.findall(".//{*}References/{*}Reference"):
            target = (reference.text or "").strip()
            if not target.startswith("ns=") or ";" not in target:
                continue
            index, identifier = target[3:].split(";", 1)
            if int(index) < len(namespaces) and namespaces[int(index)] == uri:
                identifiers.add(identifier)
    return frozenset(identifiers)


@cache
def _provided_identifiers(specification: Specification) -> frozenset[str]:
    identifiers: set[str] = set()
    for path in specification.paths:
        for element in ElementTree.parse(path).getroot():
            nodeid = element.get("NodeId", "")
            if ";" in nodeid:
                identifiers.add(nodeid.split(";", 1)[1])
    return frozenset(identifiers)


def _select_requirement(
    owner: Specification,
    requirement: ModelRequirement,
    specifications: tuple[Specification, ...],
    forced_versions: dict[str, str] | None = None,
) -> Specification:
    candidates = tuple(item for item in specifications if item.uri == requirement.uri)
    if not candidates:
        raise ValueError(f"{owner.shortname}: required Model URI is not enabled: {requirement.uri}")
    referenced = _referenced_identifiers(owner, requirement.uri)
    compatible = tuple(item for item in candidates if referenced <= _provided_identifiers(item))
    forced_version = (forced_versions or {}).get(requirement.uri)
    if forced_version is not None:
        forced = tuple(item for item in compatible if item.version == forced_version)
        if len(forced) == 1:
            return forced[0]
        raise ValueError(
            f"{owner.shortname}: forced Model version {requirement.uri} "
            f"{forced_version} is unavailable or lacks required endpoints"
        )
    compatibility_paths = {path.resolve() for path, _ in _COMPATIBILITY_MODELS}
    latest = tuple(item for item in compatible if item.path.resolve() not in compatibility_paths)
    if len(latest) == 1:
        return latest[0]
    declared = tuple(
        item for item in compatible if requirement.version and item.version == requirement.version
    )
    if len(declared) == 1:
        return declared[0]
    if len(compatible) == 1:
        return compatible[0]
    available = ", ".join(
        f"{item.shortname} {item.version or '<unspecified>'}"
        for item in sorted(candidates, key=lambda item: item.shortname)
    )
    requested = f"{requirement.uri} {requirement.version or '<unspecified>'}"
    raise ValueError(
        f"{owner.shortname}: cannot resolve required Model {requested}; available: {available}"
    )


def _direct_dependencies(
    specification: Specification,
    specifications: tuple[Specification, ...],
    forced_versions: dict[str, str] | None = None,
) -> tuple[Specification, ...]:
    requirements = list(specification.requirements)
    if specification.uri != _UA_URI and not any(item.uri == _UA_URI for item in requirements):
        requirements.append(ModelRequirement(_UA_URI))
    return tuple(
        _select_requirement(specification, item, specifications, forced_versions)
        for item in requirements
    )


def dependency_order(
    specifications: Iterable[Specification],
    *,
    candidates: Iterable[Specification] | None = None,
    forced_versions: dict[str, str] | None = None,
) -> tuple[Specification, ...]:
    specifications = tuple(specifications)
    if len({item.shortname for item in specifications}) != len(specifications):
        raise ValueError("the enabled NodeSet registry contains duplicate shortnames")
    if len({item.identity for item in specifications}) != len(specifications):
        raise ValueError("the enabled NodeSet registry contains duplicate model identities")
    candidates = _dependency_candidates(candidates or specifications)
    enabled = set(specifications)
    dependencies: dict[Specification, set[Specification]] = {}
    for specification in specifications:
        dependencies[specification] = {
            dependency
            for dependency in _direct_dependencies(specification, candidates, forced_versions)
            if dependency in enabled
        }

    ordered: list[Specification] = []
    ready = sorted(
        (specification for specification in specifications if not dependencies[specification]),
        key=lambda specification: specification.shortname,
    )
    while ready:
        specification = ready.pop(0)
        ordered.append(specification)
        for candidate in specifications:
            pending = dependencies[candidate]
            if specification not in pending:
                continue
            pending.remove(specification)
            if not pending and candidate not in ordered and candidate not in ready:
                ready.append(candidate)
        ready.sort(key=lambda candidate: candidate.shortname)
    if len(ordered) != len(specifications):
        cyclic = sorted(
            specification.shortname
            for specification in specifications
            if specification not in ordered
        )
        raise ValueError(f"cyclic NodeSet dependencies: {', '.join(cyclic)}")
    return tuple(ordered)


def _transitive_dependencies(
    specification: Specification,
    available: Iterable[Specification] | dict[str, Specification],
    forced_versions: dict[str, str] | None = None,
) -> tuple[ModelInput, ...]:
    return tuple(
        item.dependency_input
        for item in _transitive_specifications(specification, available, forced_versions)
    )


def _transitive_specifications(
    specification: Specification,
    available: Iterable[Specification] | dict[str, Specification],
    forced_versions: dict[str, str] | None = None,
) -> tuple[Specification, ...]:
    specifications = _dependency_candidates(
        available.values() if isinstance(available, dict) else available
    )
    found: set[Specification] = set()
    direct = _direct_dependencies(specification, specifications, forced_versions)
    selected_by_uri = {dependency.uri: dependency for dependency in direct}

    def visit(dependency: Specification) -> None:
        if dependency is specification or dependency in found:
            return
        selected = selected_by_uri.get(dependency.uri)
        if selected is not None and selected is not dependency:
            # The root model's RequiredModel table defines the dependency
            # closure. A transitive model may have been authored against a
            # different release, but one AddressSpace can contain only one
            # release of a namespace URI.
            return
        selected_by_uri[dependency.uri] = dependency
        for required in _direct_dependencies(dependency, specifications, forced_versions):
            visit(required)
        found.add(dependency)

    for dependency in direct:
        visit(dependency)
    ordered = dependency_order(
        (*found, specification),
        candidates=specifications,
        forced_versions=forced_versions,
    )
    return tuple(item for item in ordered if item is not specification)


def _unsupported(features: Iterable[UnsupportedFeature]) -> tuple[str, ...]:
    return tuple(
        sorted(
            {f"{feature.node_class} {feature.nodeid}: {feature.feature}" for feature in features}
        )
    )


def _format(source: str, *, is_pyi: bool = False) -> str:
    try:
        import black
    except ImportError as exc:
        raise RuntimeError("black is required to format generated NodeSet modules") from exc
    return black.format_str(
        source,
        mode=black.Mode(
            line_length=180,
            target_versions={black.TargetVersion.PY312},
            is_pyi=is_pyi,
        ),
    )


def _write_if_changed(path: Path, content: str) -> bool:
    try:
        if path.read_text(encoding="utf-8") == content:
            return False
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)
    return True


def _global_namespace_manifest(specifications: Iterable[Specification]) -> str:
    lines = [_GLOBAL_NAMESPACES_HEADER]
    for specification in dependency_order(specifications):
        lines.append(
            f"    ({specification.shortname!r}, {specification.uri!r}, "
            f"{specification.version!r}),\n"
        )
    lines.append(")\n")
    return "".join(lines)


def compile_registry(
    specifications: Iterable[Specification],
    out_dir: Path,
    *,
    keep_going: bool,
    forced_versions: dict[str, str] | None = None,
) -> tuple[CompileResult, ...]:
    specifications = tuple(specifications)
    targets = set(specifications)
    completed_targets = 0
    required = {
        dependency
        for specification in specifications
        for dependency in _transitive_specifications(specification, specifications, forced_versions)
    }
    ordered = dependency_order(
        (*specifications, *(required - set(specifications))),
        forced_versions=forced_versions,
    )
    results: list[CompileResult] = []
    for specification in ordered:
        parsed = generated = compiled = False
        try:
            loaded = load_nodeset(
                specification.model_input,
                existing=_transitive_dependencies(specification, ordered, forced_versions),
            )
            parsed = True
            unsupported = _unsupported(loaded.unsupported_features)
            if unsupported:
                result = CompileResult(
                    specification, "unsupported", parsed=True, unsupported=unsupported
                )
            else:
                source = generate_type_module(loaded, source=str(specification.path))
                generated = True
                compile(source, f"{specification.shortname}.py", "exec")
                compiled = True
                package = generate_namespace_package(source, specification.shortname)
                package_dir = out_dir / specification.shortname
                changed = False
                expected = set(package)
                if has_generated_datatypes(source):
                    expected.add("datatypes.pyi")
                for stale in (*package_dir.glob("*.py"), *package_dir.glob("*.pyi")):
                    if stale.name not in expected:
                        stale.unlink()
                        changed = True
                for relative, content in package.items():
                    changed |= _write_if_changed(package_dir / relative, _format(content))
                if has_generated_datatypes(source):
                    changed |= _write_if_changed(
                        package_dir / "datatypes.pyi",
                        _format(
                            generate_namespace_datatypes_stub(source, specification.shortname),
                            is_pyi=True,
                        ),
                    )
                result = CompileResult(
                    specification,
                    "written" if changed else "unchanged",
                    parsed=True,
                    generated=True,
                    compiled=True,
                )
        except UnsupportedNodeSetError as exc:
            result = CompileResult(
                specification,
                "unsupported",
                parsed=parsed,
                generated=generated,
                compiled=compiled,
                unsupported=(str(exc),),
            )
        except Exception as exc:  # noqa: BLE001 - each specification needs an isolated report
            result = CompileResult(
                specification,
                "failed",
                parsed=parsed,
                generated=generated,
                compiled=compiled,
                error=f"{type(exc).__name__}: {exc}",
            )
        results.append(result)
        if specification in targets:
            completed_targets += 1
            print(
                f"[{completed_targets}/{len(targets)}] {specification.shortname}: {result.status}",
                flush=True,
            )
        if result.status in {"unsupported", "failed"} and not keep_going:
            break
    if len(results) == len(ordered) and all(result.compiled for result in results):
        _write_if_changed(
            out_dir / "_generated_nodesets.py",
            _format(_global_namespace_manifest(specifications)),
        )
    return tuple(results)


def _report(results: Iterable[CompileResult]) -> bool:
    failed = False
    for result in results:
        print(f"{result.specification.shortname}: {result.status}")
        for feature in result.unsupported:
            print(f"  unsupported: {feature}")
        if result.error:
            print(f"  error: {result.error}")
        failed |= result.status in {"unsupported", "failed"}
    return failed


def _parse_forced_versions(
    values: Iterable[str], specifications: Iterable[Specification]
) -> dict[str, str]:
    by_shortname = {item.shortname: item.uri for item in specifications}
    forced: dict[str, str] = {}
    for value in values:
        model, separator, version = value.rpartition("=")
        if not separator or not model or not version:
            raise ValueError(f"invalid forced version {value!r}; expected MODEL=VERSION")
        uri = by_shortname.get(model, model)
        previous = forced.get(uri)
        if previous is not None and previous != version:
            raise ValueError(f"conflicting forced versions for {model}: {previous}, {version}")
        forced[uri] = version
    return forced


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=_OUT_DIR)
    parser.add_argument(
        "--keep-going", action="store_true", help="report every enabled specification"
    )
    parser.add_argument(
        "--force-version",
        action="append",
        default=[],
        metavar="MODEL=VERSION",
        help=(
            "force a dependency model release by canonical shortname or Model URI; "
            "may be repeated"
        ),
    )
    args = parser.parse_args(argv)
    try:
        specifications = registry()
        forced_versions = _parse_forced_versions(args.force_version, specifications)
        results = compile_registry(
            specifications,
            args.out_dir,
            keep_going=args.keep_going,
            forced_versions=forced_versions,
        )
    except (OSError, ValueError, ElementTree.ParseError) as exc:
        print(f"registry error: {exc}", file=sys.stderr)
        return 2
    return 1 if _report(results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
