# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.ns0 as ns0

class PnIoTelegramStatusEnumeration(enum.IntFlag):
    GOOD = 0
    BAD_BY_SUBSLOT = 1
    BAD_BY_SLOT = 2
    BAD_BY_DEVICE = 3
    BAD_BY_CONTROLLER = 4

class RioPaDigitalValueDataType(ns0.datatypes.Structure):
    @property
    def value(self) -> o6.Boolean: ...
    @value.setter
    def value(self, value: _Boolean) -> None: ...
    @property
    def qualifier(self) -> o6.Byte: ...
    @qualifier.setter
    def qualifier(self, value: _Integer) -> None: ...

class RioFaDigitalValueDataType(ns0.datatypes.Structure):
    @property
    def value(self) -> o6.Boolean: ...
    @value.setter
    def value(self, value: _Boolean) -> None: ...
    @property
    def qualifier(self) -> o6.Boolean: ...
    @qualifier.setter
    def qualifier(self, value: _Boolean) -> None: ...

class RioSignalTypeEnumeration(enum.IntFlag):
    CURRENT_4_20_M_A = 0
    CURRENT_0_20_M_A = 1
    VOLTAGE_0_10_V = 2
    VOLTAGE_10_10_V = 3
    HART = 4
    DIGITAL_0_24_V = 5
    NAMUR = 6
    MANUFACTURER_SPECIFIC = 7

class RioSubstitutePolicyEnumeration(enum.IntFlag):
    USE_SUBSTITUTE_VALUE = 0
    USE_LAST_VALID_VALUE = 1
    USE_ACTUAL_VALUE = 2
    UNSPECIFIED = 255

class RioChannelModeEnumeration(enum.IntFlag):
    AUTO = 0
    MANUAL = 1
    OUT_OF_SERVICE = 2

class RioQualityEnumeration(enum.IntFlag):
    GOOD = 0
    UNCERTAIN = 1
    BAD = 2
    UNSPECIFIED = 255

class RioSpecifierEnumeration(enum.IntFlag):
    NORMAL = 0
    FAILURE = 1
    FUNCTION_CHECK = 2
    MAINTENANCE_REQUEST = 3
    OUT_OF_SPECIFICATION = 4
    UNSPECIFIED = 255

class RioQualifierEnumeration(enum.IntFlag):
    BAD_NOT_SPECIFIC = 0
    BAD_NOT_CONNECTED = 8
    BAD_NOT_CONNECTED_SIMULATION_ACTIVE = 9
    BAD_PASSIVATED = 32
    BAD_PASSIVATED_SIMULATION_ACTIVE = 33
    BAD_MAINTENANCE_ALARM = 36
    BAD_MAINTENANCE_ALARM_SIMULATION_ACTIVE = 37
    BAD_PROCESS = 40
    BAD_PROCESS_SIMULATION_ACTIVE = 41
    BAD_FUNCTION_CHECK = 60
    BAD_FUNCTION_CHECK_SIMULATION_ACTIVE = 61
    UNCERTAIN_SUBSTITUTE_SET = 72
    UNCERTAIN_SUBSTITUTE_SET_SIMULATION_ACTIVE = 73
    UNCERTAIN_INITIAL_VALUE = 76
    UNCERTAIN_INITIAL_VALUE_SIMULATION_ACTIVE = 77
    UNCERTAIN_MAINTENANCE_DEMANDED = 104
    UNCERTAIN_MAINTENANCE_DEMANDED_SIMULATION_ACTIVE = 105
    UNCERTAIN_NO_MAINTENANCE = 120
    UNCERTAIN_NO_MAINTENANCE_SIMULATION_ACTIVE = 121
    GOOD = 128
    GOOD_SIMULATION_ACTIVE = 129
    UPDATE = 130
    GOOD_LOCAL_OVERRIDE = 156
    GOOD_LOCAL_OVERRIDE_SIMULATION_ACTIVE = 157
    GOOD_INITIATE_FAULT_STATE = 160
    GOOD_MAINTENANCE_REQUIRED = 164
    GOOD_MAINTENANCE_REQUIRED_SIMULATION_ACTIVE = 165
    GOOD_MAINTENANCE_DEMANDED = 168
    GOOD_MAINTENANCE_DEMANDED_SIMULATION_ACTIVE = 169
    GOOD_FUNCTION_CHECK = 188
    GOOD_FUNCTION_CHECK_SIMULATION_ACTIVE = 189
    UNSPECIFIED = 255

class RioChannelDiagnosisStatusEnumeration(enum.IntFlag):
    HI_LIM_EXCEEDED = 0
    LO_LIM_EXCEEDED = 1
    SIMULATION_ACTIVE = 2
    MODE_CHANGED = 3
    SUBSTITUTE_VALUE_USED = 4
    Q_BAD_SUBSTITUTE_VALUE_USED = 5
    OUT_OF_SERVICE = 6

class RioPaDigitalInputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def inversionEnabled(self) -> o6.Boolean: ...
    @inversionEnabled.setter
    def inversionEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> o6.Boolean: ...
    @substituteValue.setter
    def substituteValue(self, value: _Boolean) -> None: ...

class RioFaDigitalInputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def supplyVoltageCheckEnabled(self) -> o6.Boolean: ...
    @supplyVoltageCheckEnabled.setter
    def supplyVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> o6.Boolean: ...
    @substituteValue.setter
    def substituteValue(self, value: _Boolean) -> None: ...

class RioPaDigitalOutputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def inversionEnabled(self) -> o6.Boolean: ...
    @inversionEnabled.setter
    def inversionEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> o6.Boolean: ...
    @substituteValue.setter
    def substituteValue(self, value: _Boolean) -> None: ...
    @property
    def substituteTime(self) -> o6.Float: ...
    @substituteTime.setter
    def substituteTime(self, value: SupportsFloat) -> None: ...

class RioFaDigitalOutputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def supplyVoltageCheckEnabled(self) -> o6.Boolean: ...
    @supplyVoltageCheckEnabled.setter
    def supplyVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def loadVoltageCheckEnabled(self) -> o6.Boolean: ...
    @loadVoltageCheckEnabled.setter
    def loadVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> o6.Boolean: ...
    @substituteValue.setter
    def substituteValue(self, value: _Boolean) -> None: ...
    @property
    def substituteTime(self) -> o6.Float: ...
    @substituteTime.setter
    def substituteTime(self, value: SupportsFloat) -> None: ...

class RioAnalogDataType(ns0.datatypes.Union):
    @property
    def float_32(self) -> o6.Float: ...
    @float_32.setter
    def float_32(self, value: SupportsFloat) -> None: ...
    @property
    def int_16(self) -> o6.Int16: ...
    @int_16.setter
    def int_16(self, value: _Integer) -> None: ...
    @property
    def int_32(self) -> o6.Int32: ...
    @int_32.setter
    def int_32(self, value: _Integer) -> None: ...
    @property
    def uInt_16(self) -> o6.UInt16: ...
    @uInt_16.setter
    def uInt_16(self, value: _Integer) -> None: ...
    @property
    def uInt_32(self) -> o6.UInt32: ...
    @uInt_32.setter
    def uInt_32(self, value: _Integer) -> None: ...

class RioPaAnalogInputConfigDataType(ns0.datatypes.Structure):
    @property
    def damping(self) -> o6.Float: ...
    @damping.setter
    def damping(self, value: SupportsFloat) -> None: ...
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> RioAnalogDataType: ...
    @substituteValue.setter
    def substituteValue(self, value: RioAnalogDataType) -> None: ...
    @property
    def highLimit(self) -> RioAnalogDataType: ...
    @highLimit.setter
    def highLimit(self, value: RioAnalogDataType) -> None: ...
    @property
    def lowLimit(self) -> RioAnalogDataType: ...
    @lowLimit.setter
    def lowLimit(self, value: RioAnalogDataType) -> None: ...

class RioFaAnalogInputConfigDataType(ns0.datatypes.Structure):
    @property
    def damping(self) -> o6.Float: ...
    @damping.setter
    def damping(self, value: SupportsFloat) -> None: ...
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def supplyVoltageCheckEnabled(self) -> o6.Boolean: ...
    @supplyVoltageCheckEnabled.setter
    def supplyVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> RioAnalogDataType: ...
    @substituteValue.setter
    def substituteValue(self, value: RioAnalogDataType) -> None: ...

class RioPaAnalogOutputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> RioAnalogDataType: ...
    @substituteValue.setter
    def substituteValue(self, value: RioAnalogDataType) -> None: ...
    @property
    def substituteTime(self) -> o6.Float: ...
    @substituteTime.setter
    def substituteTime(self, value: SupportsFloat) -> None: ...

class RioFaAnalogOutputConfigDataType(ns0.datatypes.Structure):
    @property
    def signalType(self) -> RioSignalTypeEnumeration: ...
    @signalType.setter
    def signalType(self, value: _Integer) -> None: ...
    @property
    def wireCheckEnabled(self) -> o6.Boolean: ...
    @wireCheckEnabled.setter
    def wireCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def supplyVoltageCheckEnabled(self) -> o6.Boolean: ...
    @supplyVoltageCheckEnabled.setter
    def supplyVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def loadVoltageCheckEnabled(self) -> o6.Boolean: ...
    @loadVoltageCheckEnabled.setter
    def loadVoltageCheckEnabled(self, value: _Boolean) -> None: ...
    @property
    def substitutePolicy(self) -> RioSubstitutePolicyEnumeration: ...
    @substitutePolicy.setter
    def substitutePolicy(self, value: _Integer) -> None: ...
    @property
    def substituteValue(self) -> RioAnalogDataType: ...
    @substituteValue.setter
    def substituteValue(self, value: RioAnalogDataType) -> None: ...
    @property
    def substituteTime(self) -> o6.Float: ...
    @substituteTime.setter
    def substituteTime(self, value: SupportsFloat) -> None: ...

class RioPaDigitalProcessValueDataType(RioPaDigitalValueDataType):
    @property
    def value(self) -> o6.Boolean: ...
    @value.setter
    def value(self, value: _Boolean) -> None: ...
    @property
    def qualifier(self) -> o6.Byte: ...
    @qualifier.setter
    def qualifier(self, value: _Integer) -> None: ...
    @property
    def quality(self) -> o6.Byte: ...
    @quality.setter
    def quality(self, value: _Integer) -> None: ...
    @property
    def nE_107(self) -> o6.Byte: ...
    @nE_107.setter
    def nE_107(self, value: _Integer) -> None: ...
    @property
    def status_full(self) -> o6.Byte: ...
    @status_full.setter
    def status_full(self, value: _Integer) -> None: ...

class RioFaDigitalProcessValueDataType(RioFaDigitalValueDataType):
    @property
    def value(self) -> o6.Boolean: ...
    @value.setter
    def value(self, value: _Boolean) -> None: ...
    @property
    def qualifier(self) -> o6.Boolean: ...
    @qualifier.setter
    def qualifier(self, value: _Boolean) -> None: ...
    @property
    def quality(self) -> o6.Byte: ...
    @quality.setter
    def quality(self, value: _Integer) -> None: ...

class RioBitFieldDataType(ns0.datatypes.Structure):
    @property
    def bitData(self) -> o6.UInt32: ...
    @bitData.setter
    def bitData(self, value: _Integer) -> None: ...
    @property
    def bitUsed(self) -> o6.UInt32: ...
    @bitUsed.setter
    def bitUsed(self, value: _Integer) -> None: ...

class RioChannelDiagnosisReasonEnumeration(enum.IntFlag):
    ALL_DISAPPEARS = 0
    APPEARS = 1
    DISAPPEARS = 2
    DISAPPEARS_OTHER_REMAIN = 3

class RioPaAnalogValueDataType(ns0.datatypes.Structure):
    @property
    def value(self) -> RioAnalogDataType: ...
    @value.setter
    def value(self, value: RioAnalogDataType) -> None: ...
    @property
    def qualifier(self) -> o6.Byte: ...
    @qualifier.setter
    def qualifier(self, value: _Integer) -> None: ...

class RioPaAnalogProcessValueDataType(RioPaAnalogValueDataType):
    @property
    def value(self) -> RioAnalogDataType: ...
    @value.setter
    def value(self, value: RioAnalogDataType) -> None: ...
    @property
    def qualifier(self) -> o6.Byte: ...
    @qualifier.setter
    def qualifier(self, value: _Integer) -> None: ...
    @property
    def quality(self) -> o6.Byte: ...
    @quality.setter
    def quality(self, value: _Integer) -> None: ...
    @property
    def nE_107(self) -> o6.Byte: ...
    @nE_107.setter
    def nE_107(self, value: _Integer) -> None: ...
    @property
    def status_full(self) -> o6.Byte: ...
    @status_full.setter
    def status_full(self, value: _Integer) -> None: ...

class RioFaAnalogValueDataType(ns0.datatypes.Structure):
    @property
    def value(self) -> RioAnalogDataType: ...
    @value.setter
    def value(self, value: RioAnalogDataType) -> None: ...
    @property
    def qualifier(self) -> o6.Boolean: ...
    @qualifier.setter
    def qualifier(self, value: _Boolean) -> None: ...

class RioFaAnalogProcessValueDataType(RioFaAnalogValueDataType):
    @property
    def value(self) -> RioAnalogDataType: ...
    @value.setter
    def value(self, value: RioAnalogDataType) -> None: ...
    @property
    def qualifier(self) -> o6.Boolean: ...
    @qualifier.setter
    def qualifier(self, value: _Boolean) -> None: ...
    @property
    def quality(self) -> o6.Byte: ...
    @quality.setter
    def quality(self, value: _Integer) -> None: ...
