# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.gds as gds

import o6.ns.ns0 as ns0

class CertificateAuthorityType(ns0.datatypes.Structure):
    @property
    def authorityCertificate(self) -> o6.ByteString: ...
    @authorityCertificate.setter
    def authorityCertificate(self, value: o6.ByteString) -> None: ...
    @property
    def issuerCertificates(self) -> list[o6.ByteString]: ...
    @issuerCertificates.setter
    def issuerCertificates(self, value: Sequence[o6.ByteString]) -> None: ...

class BaseTicketType(ns0.datatypes.Structure):
    @property
    def manufacturerName(self) -> o6.String: ...
    @manufacturerName.setter
    def manufacturerName(self, value: o6.String) -> None: ...
    @property
    def modelName(self) -> o6.String: ...
    @modelName.setter
    def modelName(self, value: o6.String) -> None: ...
    @property
    def modelVersion(self) -> o6.String: ...
    @modelVersion.setter
    def modelVersion(self, value: o6.String) -> None: ...
    @property
    def hardwareRevision(self) -> o6.String: ...
    @hardwareRevision.setter
    def hardwareRevision(self, value: o6.String) -> None: ...
    @property
    def softwareRevision(self) -> o6.String: ...
    @softwareRevision.setter
    def softwareRevision(self, value: o6.String) -> None: ...
    @property
    def serialNumber(self) -> o6.String: ...
    @serialNumber.setter
    def serialNumber(self, value: o6.String) -> None: ...
    @property
    def manufactureDate(self) -> o6.DateTime: ...
    @manufactureDate.setter
    def manufactureDate(self, value: o6.DateTime) -> None: ...
    @property
    def authorities(self) -> list[CertificateAuthorityType]: ...
    @authorities.setter
    def authorities(self, value: Sequence[CertificateAuthorityType]) -> None: ...

class DeviceIdentityTicketType(BaseTicketType):
    @property
    def manufacturerName(self) -> o6.String: ...
    @manufacturerName.setter
    def manufacturerName(self, value: o6.String) -> None: ...
    @property
    def modelName(self) -> o6.String: ...
    @modelName.setter
    def modelName(self, value: o6.String) -> None: ...
    @property
    def modelVersion(self) -> o6.String: ...
    @modelVersion.setter
    def modelVersion(self, value: o6.String) -> None: ...
    @property
    def hardwareRevision(self) -> o6.String: ...
    @hardwareRevision.setter
    def hardwareRevision(self, value: o6.String) -> None: ...
    @property
    def softwareRevision(self) -> o6.String: ...
    @softwareRevision.setter
    def softwareRevision(self, value: o6.String) -> None: ...
    @property
    def serialNumber(self) -> o6.String: ...
    @serialNumber.setter
    def serialNumber(self, value: o6.String) -> None: ...
    @property
    def manufactureDate(self) -> o6.DateTime: ...
    @manufactureDate.setter
    def manufactureDate(self, value: o6.DateTime) -> None: ...
    @property
    def authorities(self) -> list[CertificateAuthorityType]: ...
    @authorities.setter
    def authorities(self, value: Sequence[CertificateAuthorityType]) -> None: ...
    @property
    def productInstanceUri(self) -> o6.String: ...
    @productInstanceUri.setter
    def productInstanceUri(self, value: o6.String) -> None: ...

class CompositeIdentityTicketType(BaseTicketType):
    @property
    def manufacturerName(self) -> o6.String: ...
    @manufacturerName.setter
    def manufacturerName(self, value: o6.String) -> None: ...
    @property
    def modelName(self) -> o6.String: ...
    @modelName.setter
    def modelName(self, value: o6.String) -> None: ...
    @property
    def modelVersion(self) -> o6.String: ...
    @modelVersion.setter
    def modelVersion(self, value: o6.String) -> None: ...
    @property
    def hardwareRevision(self) -> o6.String: ...
    @hardwareRevision.setter
    def hardwareRevision(self, value: o6.String) -> None: ...
    @property
    def softwareRevision(self) -> o6.String: ...
    @softwareRevision.setter
    def softwareRevision(self, value: o6.String) -> None: ...
    @property
    def serialNumber(self) -> o6.String: ...
    @serialNumber.setter
    def serialNumber(self, value: o6.String) -> None: ...
    @property
    def manufactureDate(self) -> o6.DateTime: ...
    @manufactureDate.setter
    def manufactureDate(self, value: o6.DateTime) -> None: ...
    @property
    def authorities(self) -> list[CertificateAuthorityType]: ...
    @authorities.setter
    def authorities(self, value: Sequence[CertificateAuthorityType]) -> None: ...
    @property
    def compositeInstanceUri(self) -> o6.String: ...
    @compositeInstanceUri.setter
    def compositeInstanceUri(self, value: o6.String) -> None: ...
    @property
    def devices(self) -> list[o6.String]: ...
    @devices.setter
    def devices(self, value: Sequence[o6.String]) -> None: ...
    @property
    def composites(self) -> list[o6.String]: ...
    @composites.setter
    def composites(self, value: Sequence[o6.String]) -> None: ...

class TicketListType(ns0.datatypes.Structure):
    @property
    def devices(self) -> list[o6.String]: ...
    @devices.setter
    def devices(self, value: Sequence[o6.String]) -> None: ...
    @property
    def composites(self) -> list[o6.String]: ...
    @composites.setter
    def composites(self, value: Sequence[o6.String]) -> None: ...

class ManagerDescription(ns0.datatypes.Structure):
    @property
    def name(self) -> o6.LocalizedText: ...
    @name.setter
    def name(self, value: o6.LocalizedText) -> None: ...
    @property
    def isRequired(self) -> o6.Boolean: ...
    @isRequired.setter
    def isRequired(self, value: _Boolean) -> None: ...
    @property
    def purposeUri(self) -> o6.String: ...
    @purposeUri.setter
    def purposeUri(self, value: o6.String) -> None: ...
    @property
    def protocolUri(self) -> o6.String: ...
    @protocolUri.setter
    def protocolUri(self, value: o6.String) -> None: ...
    @property
    def endpointUrls(self) -> list[o6.String]: ...
    @endpointUrls.setter
    def endpointUrls(self, value: Sequence[o6.String]) -> None: ...
