# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
O6 - High-Level OPC UA Python Library

This package provides a high-level, pythonic interface to OPC UA functionality,
built on top of the low-level _o6 C extension module.

Basic usage:
    from o6 import Client

    client = Client("opc.tcp://localhost:4840")
    with client:
        value = client.read("ns=1;s=Temperature")
        client.write("ns=1;s=SetPoint", 25.0)
"""

from __future__ import annotations
import enum
import logging
from typing import Optional, Any, Awaitable, Generator, TypeAlias, TypeVar
from asyncio import Future as AsyncIOFuture
from concurrent.futures import Future as ConcurrentFuture

from . import _o6
from ._o6 import types as types
from ._o6.types_builtin import *
from ._o6.types_gen import *
from ._o6.types import DataTypeKind as DataTypeKind
from ._o6.types_gen import DataChangeFilter as _DataChangeFilterBase
from ._o6.types_gen import RelativePath as _RelativePathBase
from ._o6.types_gen import SimpleAttributeOperand as _SimpleAttributeOperandBase
from ._o6.types_gen import ReadValueId as _ReadValueIdBase
from ._o6.types import (
    EventFilter as EventFilter,
)
from o6 import namespaces as namespaces
from o6.namespaces import Namespaces as Namespaces
from o6._ns import ns as ns
from o6.client import Client as Client
from o6.client import Subscription as Subscription
from o6.client import MonitoredItem as MonitoredItem
from o6.server import (
    Server as Server,
    ServerNode as ServerNode,
    make_argument as make_argument,
)
from o6 import crypto as crypto

KeyValueMap: TypeAlias = dict[str, Any]

_T = TypeVar("_T")
MaybeAwaitable: TypeAlias = _T | Awaitable[_T]

_V = TypeVar("_V")
AwaitReturn: TypeAlias = Generator[Any, None, _V]

_U = TypeVar("_U")
Future: TypeAlias = AsyncIOFuture[_U] | ConcurrentFuture[_U]

LocalizedTextLike: TypeAlias = _o6.types.LocalizedText | str

class StatusCodeError(Exception): ...

def encryption_available() -> bool: ...

class AttributeId(enum.IntEnum):
    NODEID = ...
    NODECLASS = ...
    BROWSENAME = ...
    DISPLAYNAME = ...
    DESCRIPTION = ...
    WRITEMASK = ...
    USERWRITEMASK = ...
    ISABSTRACT = ...
    SYMMETRIC = ...
    INVERSENAME = ...
    CONTAINSNOLOOPS = ...
    EVENTNOTIFIER = ...
    VALUE = ...
    DATATYPE = ...
    VALUERANK = ...
    ARRAYDIMENSIONS = ...
    ACCESSLEVEL = ...
    USERACCESSLEVEL = ...
    MINIMUMSAMPLINGINTERVAL = ...
    HISTORIZING = ...
    EXECUTABLE = ...
    USEREXECUTABLE = ...
    DATATYPEDEFINITION = ...
    ROLEPERMISSIONS = ...
    USERROLEPERMISSIONS = ...
    ACCESSRESTRICTIONS = ...
    ACCESSLEVELEX = ...

class ValueRank(enum.IntEnum):
    """Enum for the most common ValueRanks. ValueRanks >2 can also be used.
    They indicate an array with the given dimensions.
    But ValueRanks >2 don't have a shortname defined in this enum class."""

    SCALAR_OR_1D: int
    ANY = ...
    SCALAR = ...
    ARRAY_ANY = ...
    ARRAY_1D: int
    ARRAY_2D: int

class AccessLevel(enum.IntFlag):
    """Bitmask values for the AccessLevel and UserAccessLevel attributes."""

    READ = ...
    CURRENTREAD = ...
    WRITE = ...
    CURRENTWRITE = ...
    HISTORYREAD = ...
    HISTORYWRITE = ...
    SEMANTICCHANGE = ...
    STATUSWRITE = ...
    TIMESTAMPWRITE = ...

class WriteMask(enum.IntFlag):
    """Bitmask values for the WriteMask and UserWriteMask attributes."""

    ACCESSLEVEL = ...
    ARRAYDIMENSIONS = ...
    BROWSENAME = ...
    CONTAINSNOLOOPS = ...
    DATATYPE = ...
    DESCRIPTION = ...
    DISPLAYNAME = ...
    EVENTNOTIFIER = ...
    EXECUTABLE = ...
    HISTORIZING = ...
    INVERSENAME = ...
    ISABSTRACT = ...
    MINIMUMSAMPLINGINTERVAL = ...
    NODECLASS = ...
    NODEID = ...
    SYMMETRIC = ...
    USERACCESSLEVEL = ...
    USEREXECUTABLE = ...
    USERWRITEMASK = ...
    VALUERANK = ...
    WRITEMASK = ...
    VALUEFORVARIABLETYPE = ...
    DATATYPEDEFINITION = ...
    ROLEPERMISSIONS = ...
    ACCESSRESTRICTIONS = ...
    ACCESSLEVELEX = ...

class SecurityMode(enum.IntEnum):
    """OPC UA MessageSecurityMode."""

    INVALID = ...
    NONE = ...
    SIGN = ...
    SIGN_AND_ENCRYPT = ...

class SecurityPolicy(str, enum.Enum):
    """OPC UA security policy URIs."""

    NONE = ...
    BASIC128RSA15 = ...
    BASIC256 = ...
    BASIC256SHA256 = ...
    AES128_SHA256_RSAOAEP = ...
    AES256_SHA256_RSAPSS = ...

class SecureChannelState(enum.IntEnum):
    """Possible status of a SecureChannel"""

    CLOSED = ...
    REVERSE_LISTENING = ...
    CONNECTING = ...
    CONNECTED = ...
    REVERSE_CONNECTED = ...
    RHE_SENT = ...
    HEL_SENT = ...
    HEL_RECEIVED = ...
    ACK_SENT = ...
    ACK_RECEIVED = ...
    OPN_SENT = ...
    OPEN = ...
    CLOSING = ...

class SessionState(enum.IntEnum):
    """Possible status of a Session"""

    CLOSED = ...
    CREATE_REQUESTED = ...
    CREATED = ...
    ACTIVATE_REQUESTED = ...
    ACTIVATED = ...
    CLOSING = ...

# Monkey-patched in o6/__init__.py
class DataChangeFilter(_DataChangeFilterBase):
    def __init__(
        self,
        trigger: Optional[DataChangeTrigger | int] = ...,
        deadband_type: Optional[int] = ...,
        deadband_value: Optional[float] = ...,
    ) -> None: ...

class RelativePath(_RelativePathBase):
    def __init__(self, input: Optional[str] = None) -> None: ...
    def __str__(self) -> str: ...

class SimpleAttributeOperand(_SimpleAttributeOperandBase):
    def __init__(self, input: Optional[str] = None) -> None: ...
    def __str__(self) -> str: ...

class ReadValueId(_ReadValueIdBase):
    def __init__(self, input: Optional[str] = None) -> None: ...
    def __str__(self) -> str: ...

class ClientConfig: ...

def log_trace(logger: logging.Logger, message: str, category: str = ...) -> None: ...
def log_debug(logger: logging.Logger, message: str, category: str = ...) -> None: ...
def log_info(logger: logging.Logger, message: str, category: str = ...) -> None: ...
def log_warning(logger: logging.Logger, message: str, category: str = ...) -> None: ...
def log_error(logger: logging.Logger, message: str, category: str = ...) -> None: ...
def log_fatal(logger: logging.Logger, message: str, category: str = ...) -> None: ...
