# Copyright 2026 (c) o6 Automation GmbH
from __future__ import annotations
from typing import Any, Optional, Protocol, runtime_checkable
import asyncio

import o6
from o6 import MaybeAwaitable, HasNodeId, NodeIdLike

if False:
    from o6.client import Client
    from o6.server import Server

@runtime_checkable
class NodeBackend(Protocol):
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def dispatch(self, coro: Any) -> MaybeAwaitable: ...
    async def node_browse(self, nodeid: Any, result_mask: Any) -> list: ...
    async def node_read(self, nodeid: Any, attr: Any) -> Any: ...
    async def node_write(self, nodeid: Any, value: Any, attr: Any) -> None: ...
    async def node_call(self, obj_id: Any, method_id: Any, args: Any) -> tuple: ...
    async def node_translate(self, request: Any) -> Any: ...
    async def node_delete(self, nodeid: Any) -> None: ...
    async def node_get(self, nodeid: Any) -> Node: ...

class ClientBackend:
    def __init__(self, client: Client) -> None: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def dispatch(self, coro: Any) -> MaybeAwaitable: ...
    async def node_browse(self, nodeid: Any, result_mask: Any) -> list: ...
    async def node_read(self, nodeid: Any, attr: Any) -> Any: ...
    async def node_write(self, nodeid: Any, value: Any, attr: Any) -> None: ...
    async def node_call(self, obj_id: Any, method_id: Any, args: Any) -> tuple: ...
    async def node_translate(self, request: Any) -> Any: ...
    async def node_delete(self, nodeid: Any) -> None: ...
    async def node_get(self, nodeid: Any) -> Node: ...

class ServerBackend:
    def __init__(self, server: Server) -> None: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def dispatch(self, coro: Any) -> MaybeAwaitable: ...
    async def node_browse(self, nodeid: Any, result_mask: Any) -> list: ...
    async def node_read(self, nodeid: Any, attr: Any) -> Any: ...
    async def node_write(self, nodeid: Any, value: Any, attr: Any) -> None: ...
    async def node_call(self, obj_id: Any, method_id: Any, args: Any) -> tuple: ...
    async def node_translate(self, request: Any) -> Any: ...
    async def node_delete(self, nodeid: Any) -> None: ...
    async def node_get(self, nodeid: Any) -> Node: ...

def _str2attributeid(s: str) -> o6.AttributeId: ...
def _nodeclass2type(nc: o6.NodeClass) -> type: ...
def _type2nodeclass(T: type) -> o6.NodeClass: ...

class Node(HasNodeId):
    _nodeid: o6.NodeId
    _browse_name: o6.QualifiedName

    def __init__(
        self,
        backend: NodeBackend,
        nodeid: NodeIdLike,
        browse_name: o6.QualifiedName,
    ) -> None: ...
    @property
    def backend(self) -> NodeBackend: ...
    @property
    def nodeid(self) -> o6.NodeId: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def delete(self) -> None: ...
    def __call__(
        self,
        value: Optional[Any] = None,
        attr: Optional[o6.AttributeId | str] = None,
    ) -> MaybeAwaitable[Any]: ...
    def _delete_cache(self) -> None: ...
    def __dir__(self) -> list[str]: ...
    def __getattr__(self, name: str) -> Node | AwaitableNode: ...
    def __getitem__(self, key: str | o6.RelativePath) -> MaybeAwaitable[list[Any]]: ...

class AwaitableNode:
    def __init__(self, backend: NodeBackend, awaitable: Any) -> None: ...
    def __await__(self): ...
    def __getattr__(self, name: str) -> AwaitableNode: ...
    def __call__(self, *args: Any, **kwargs: Any) -> AwaitableNode: ...

class ObjectNode(Node):
    pass

class VariableNode(Node):
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, v: Any) -> None: ...
    def __call__(
        self,
        value: Optional[Any] = None,
        attr: Optional[o6.AttributeId | str] = None,
    ) -> MaybeAwaitable[Any]: ...

class VariableTypeNode(Node):
    def __call__(
        self,
        value: Optional[Any] = None,
        attr: Optional[o6.AttributeId | str] = None,
    ) -> MaybeAwaitable[Any]: ...

class MethodNode(Node):
    _default_object: o6.NodeId | None

    def __call__(
        self,
        *args: Any,
        object_id: Optional[o6.NodeId] = None,
        attr: Optional[o6.AttributeId | str] = None,
        value: Optional[Any] = None,
    ) -> MaybeAwaitable[Any]: ...

class ObjectTypeNode(Node):
    pass

class ReferenceTypeNode(Node):
    pass

class DataTypeNode(Node):
    pass

class ViewNode(Node):
    pass
