# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
from __future__ import annotations
from uuid import UUID
from datetime import datetime
from typing import Any, overload, Protocol

# --- Primitive Wrapper Types ---

class Boolean:
    def __init__(self, value: bool = ..., /) -> None: ...
    def __bool__(self) -> bool: ...

class SByte:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class Byte:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class Int16:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class UInt16:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class Int32:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class UInt32:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class Int64:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class UInt64:
    def __init__(self, value: int = ..., /) -> None: ...
    def __int__(self) -> int: ...

class Float:
    def __init__(self, value: float = ..., /) -> None: ...
    def __float__(self) -> float: ...

class Double:
    def __init__(self, value: float = ..., /) -> None: ...
    def __float__(self) -> float: ...

class String:
    def __init__(self, value: str = ..., /) -> None: ...
    def __str__(self) -> str: ...

# --- Core Types ---

class StatusCode:
    """
    A numeric identifier for an error or condition that is associated with a
    value or an operation.

    Each StatusCode has one of three "severity" bit-flags: Good, Uncertain, Bad.
    An additional reason is indicated by the SubCode bitfield.
    """

    BADNOTWRITABLE: StatusCode

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, data: int, /) -> None: ...
    @property
    def code(self) -> int: ...
    @property
    def name(self) -> str: ...

class DateTime:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, date: datetime, /) -> None: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...

# Protocol for classes with a member "_nodeid" of type NodeId. The native NodeId
# constructor checks the argument for a _nodeid member and makes a copy if
# present.
class HasNodeId(Protocol):
    _nodeid: NodeId

class NodeId:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, numericNs0Id: int, /) -> None: ...
    @overload
    def __init__(self, parseStr: str, /) -> None: ...
    @overload
    def __init__(self, hasNodeId: HasNodeId, /) -> None: ...
    @overload
    def __init__(self, other: NodeId, /) -> None: ...
    @overload
    def __init__(self, nop: None, /) -> None: ...
    @overload
    def __init__(self, *, ns: int = 0, i: int) -> None: ...
    @overload
    def __init__(self, *, ns: int = 0, s: str) -> None: ...
    @overload
    def __init__(self, *, ns: int = 0, b: bytes) -> None: ...
    @overload
    def __init__(self, *, ns: int = 0, g: UUID) -> None: ...
    @property
    def ns(self) -> int: ...
    @property
    def id(self) -> int | str | bytes | UUID: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

NodeIdLike = NodeId | str | HasNodeId

class ExpandedNodeId:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, parseStr: str, /) -> None: ...
    @overload
    def __init__(self, nodeId: NodeId, /) -> None: ...
    @property
    def ns(self) -> int: ...
    @property
    def id(self) -> int | str | bytes | UUID: ...
    @property
    def nsu(self) -> str: ...
    @property
    def svr(self) -> int: ...

class QualifiedName:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ns: int, name: str, /) -> None: ...
    @overload
    def __init__(self, name: str, /) -> None: ...
    @property
    def ns(self) -> int: ...
    @property
    def name(self) -> str: ...

class LocalizedText:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, lt: LocalizedText, /) -> None: ...
    @overload
    def __init__(self, text: str, /) -> None: ...
    @overload
    def __init__(self, locale: str, text: str, /) -> None: ...
    @property
    def locale(self) -> str: ...
    @property
    def text(self) -> str: ...

class ExtensionObject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, body: Any | None, /) -> None: ...
    @overload
    def __init__(self, type_id: NodeIdLike, body: str | bytes, /) -> None: ...
    @property
    def type_id(self) -> NodeId | None: ...
    @property
    def body(self) -> Any | None: ...

class DataValue:
    def __init__(self) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, val: Any, /) -> None: ...
    @property
    def status(self) -> StatusCode | None: ...
    @status.setter
    def status(self, val: StatusCode | None, /) -> None: ...
    @property
    def source_timestamp(self) -> DateTime | None: ...
    @source_timestamp.setter
    def source_timestamp(self, val: DateTime | None, /) -> None: ...
    @property
    def server_timestamp(self) -> DateTime | None: ...
    @server_timestamp.setter
    def server_timestamp(self, val: DateTime | None, /) -> None: ...
    @property
    def source_picoseconds(self) -> int | None: ...
    @source_picoseconds.setter
    def source_picoseconds(self, val: int | None, /) -> None: ...
    @property
    def server_picoseconds(self) -> int | None: ...
    @server_picoseconds.setter
    def server_picoseconds(self, val: int | None, /) -> None: ...
