# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.ns0 as ns0

class ProductionMaintenanceModeEnum(enum.IntFlag):
    INVALID = 0
    PRODUCE = 1
    MAINTENANCE = 2
    MANUAL = 3

class PackMLCountDataType(ns0.datatypes.Structure):
    @property
    def iD(self) -> o6.Int32: ...
    @iD.setter
    def iD(self, value: _Integer) -> None: ...
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...
    @property
    def unit(self) -> ns0.datatypes.EUInformation: ...
    @unit.setter
    def unit(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def count(self) -> o6.Int32: ...
    @count.setter
    def count(self, value: _Integer) -> None: ...
    @property
    def accCount(self) -> o6.Int32: ...
    @accCount.setter
    def accCount(self, value: _Integer) -> None: ...

class PackMLAlarmDataType(ns0.datatypes.Structure):
    @property
    def iD(self) -> o6.Int32: ...
    @iD.setter
    def iD(self, value: _Integer) -> None: ...
    @property
    def value(self) -> o6.Int32: ...
    @value.setter
    def value(self, value: _Integer) -> None: ...
    @property
    def message(self) -> o6.String: ...
    @message.setter
    def message(self, value: o6.String) -> None: ...
    @property
    def category(self) -> o6.Int32: ...
    @category.setter
    def category(self, value: _Integer) -> None: ...
    @property
    def dateTime(self) -> o6.DateTime: ...
    @dateTime.setter
    def dateTime(self, value: o6.DateTime) -> None: ...
    @property
    def ackDateTime(self) -> o6.DateTime: ...
    @ackDateTime.setter
    def ackDateTime(self, value: o6.DateTime) -> None: ...
    @property
    def trigger(self) -> o6.Boolean: ...
    @trigger.setter
    def trigger(self, value: _Boolean) -> None: ...

class PackMLDescriptorDataType(ns0.datatypes.Structure):
    @property
    def iD(self) -> o6.Int32: ...
    @iD.setter
    def iD(self, value: _Integer) -> None: ...
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...
    @property
    def unit(self) -> ns0.datatypes.EUInformation: ...
    @unit.setter
    def unit(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def value(self) -> o6.Float: ...
    @value.setter
    def value(self, value: SupportsFloat) -> None: ...

class PackMLIngredientsDataType(ns0.datatypes.Structure):
    @property
    def ingredientID(self) -> o6.Int32: ...
    @ingredientID.setter
    def ingredientID(self, value: _Integer) -> None: ...
    @property
    def parameter(self) -> list[PackMLDescriptorDataType]: ...
    @parameter.setter
    def parameter(self, value: Sequence[PackMLDescriptorDataType]) -> None: ...

class PackMLProductDataType(ns0.datatypes.Structure):
    @property
    def productID(self) -> o6.Int32: ...
    @productID.setter
    def productID(self, value: _Integer) -> None: ...
    @property
    def processVariables(self) -> list[PackMLDescriptorDataType]: ...
    @processVariables.setter
    def processVariables(self, value: Sequence[PackMLDescriptorDataType]) -> None: ...
    @property
    def ingredients(self) -> list[PackMLIngredientsDataType]: ...
    @ingredients.setter
    def ingredients(self, value: Sequence[PackMLIngredientsDataType]) -> None: ...

class PackMLRemoteInterfaceDataType(ns0.datatypes.Structure):
    @property
    def number(self) -> o6.Int32: ...
    @number.setter
    def number(self, value: _Integer) -> None: ...
    @property
    def controlCmdNumber(self) -> o6.Int32: ...
    @controlCmdNumber.setter
    def controlCmdNumber(self, value: _Integer) -> None: ...
    @property
    def cmdValue(self) -> o6.Int32: ...
    @cmdValue.setter
    def cmdValue(self, value: _Integer) -> None: ...
    @property
    def parameter(self) -> list[PackMLDescriptorDataType]: ...
    @parameter.setter
    def parameter(self, value: Sequence[PackMLDescriptorDataType]) -> None: ...
