# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.ns0 as ns0

class DeviceStatusEnumeration(enum.IntFlag):
    IDLE = 0
    ERROR = 1
    SCANNING = 2
    BUSY = 3

class Position(ns0.datatypes.Structure):
    @property
    def positionX(self) -> o6.Int32: ...
    @positionX.setter
    def positionX(self, value: _Integer) -> None: ...
    @property
    def positionY(self) -> o6.Int32: ...
    @positionY.setter
    def positionY(self, value: _Integer) -> None: ...
    @property
    def sizeX(self) -> o6.Int32: ...
    @sizeX.setter
    def sizeX(self, value: _Integer) -> None: ...
    @property
    def sizeY(self) -> o6.Int32: ...
    @sizeY.setter
    def sizeY(self, value: _Integer) -> None: ...
    @property
    def rotation(self) -> o6.Int32: ...
    @rotation.setter
    def rotation(self, value: _Integer) -> None: ...

class RfidSighting(ns0.datatypes.Structure):
    @property
    def antenna(self) -> o6.Int32: ...
    @antenna.setter
    def antenna(self, value: _Integer) -> None: ...
    @property
    def strength(self) -> o6.Int32: ...
    @strength.setter
    def strength(self, value: _Integer) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def currentPowerLevel(self) -> o6.Int32: ...
    @currentPowerLevel.setter
    def currentPowerLevel(self, value: _Integer) -> None: ...

class LocationTypeEnumeration(enum.IntFlag):
    NMEA = 0
    LOCAL = 1
    WGS84 = 2
    NAME = 3

class ScanSettings(ns0.datatypes.Structure):
    @property
    def duration(self) -> o6.Double: ...
    @duration.setter
    def duration(self, value: SupportsFloat) -> None: ...
    @property
    def cycles(self) -> o6.Int32: ...
    @cycles.setter
    def cycles(self, value: _Integer) -> None: ...
    @property
    def dataAvailable(self) -> o6.Boolean: ...
    @dataAvailable.setter
    def dataAvailable(self, value: _Boolean) -> None: ...
    @property
    def locationType(self) -> LocationTypeEnumeration | None: ...
    @locationType.setter
    def locationType(self, value: _Integer | None) -> None: ...

class AntennaNameIdPair(ns0.datatypes.Structure):
    @property
    def antennaId(self) -> o6.Int32: ...
    @antennaId.setter
    def antennaId(self, value: _Integer) -> None: ...
    @property
    def antennaName(self) -> o6.String: ...
    @antennaName.setter
    def antennaName(self, value: o6.String) -> None: ...

class NmeaCoordinateString:
    pass

class AutoIdOperationStatusEnumeration(enum.IntFlag):
    SUCCESS = 0
    MISC_ERROR_TOTAL = 1
    MISC_ERROR_PARTIAL = 2
    PERMISSON_ERROR = 3
    PASSWORD_ERROR = 4
    REGION_NOT_FOUND_ERROR = 5
    OP_NOT_POSSIBLE_ERROR = 6
    OUT_OF_RANGE_ERROR = 7
    NO_IDENTIFIER = 8
    MULTIPLE_IDENTIFIERS = 9
    READ_ERROR = 10
    DECODING_ERROR = 11
    MATCH_ERROR = 12
    CODE_NOT_SUPPORTED = 13
    WRITE_ERROR = 14
    NOT_SUPPORTED_BY_DEVICE = 15
    NOT_SUPPORTED_BY_TAG = 16
    DEVICE_NOT_READY = 17
    INVALID_CONFIGURATION = 18
    RF_COMMUNICATION_ERROR = 19
    DEVICE_FAULT = 20
    TAG_HAS_LOW_BATTERY = 21

class RfidPasswordTypeEnumeration(enum.IntFlag):
    ACCESS = 0
    KILL = 1
    READ = 2
    WRITE = 3

class RfidLockRegionEnumeration(enum.IntFlag):
    KILL = 0
    ACCESS = 1
    EPC = 2
    TID = 3
    USER = 4

class RfidLockOperationEnumeration(enum.IntFlag):
    LOCK = 0
    UNLOCK = 1
    PERMANENT_LOCK = 2
    PERMANENT_UNLOCK = 3

class LocalCoordinate(ns0.datatypes.Structure):
    @property
    def x(self) -> o6.Double: ...
    @x.setter
    def x(self, value: SupportsFloat) -> None: ...
    @property
    def y(self) -> o6.Double: ...
    @y.setter
    def y(self, value: SupportsFloat) -> None: ...
    @property
    def z(self) -> o6.Double: ...
    @z.setter
    def z(self, value: SupportsFloat) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def dilutionOfPrecision(self) -> o6.Double: ...
    @dilutionOfPrecision.setter
    def dilutionOfPrecision(self, value: SupportsFloat) -> None: ...
    @property
    def usefulPrecision(self) -> o6.Int32: ...
    @usefulPrecision.setter
    def usefulPrecision(self, value: _Integer) -> None: ...

class LocationName:
    pass

class DhcpGeoConfCoordinate(ns0.datatypes.Structure):
    @property
    def laRes(self) -> o6.Byte: ...
    @laRes.setter
    def laRes(self, value: _Integer) -> None: ...
    @property
    def latitudeInteger(self) -> o6.Int16: ...
    @latitudeInteger.setter
    def latitudeInteger(self, value: _Integer) -> None: ...
    @property
    def latitudeFraction(self) -> o6.Int32: ...
    @latitudeFraction.setter
    def latitudeFraction(self, value: _Integer) -> None: ...
    @property
    def loRes(self) -> o6.Byte: ...
    @loRes.setter
    def loRes(self, value: _Integer) -> None: ...
    @property
    def longitudeInteger(self) -> o6.Int16: ...
    @longitudeInteger.setter
    def longitudeInteger(self, value: _Integer) -> None: ...
    @property
    def longitudeFraction(self) -> o6.Int32: ...
    @longitudeFraction.setter
    def longitudeFraction(self, value: _Integer) -> None: ...
    @property
    def aT(self) -> o6.Byte: ...
    @aT.setter
    def aT(self, value: _Integer) -> None: ...
    @property
    def altRes(self) -> o6.Byte: ...
    @altRes.setter
    def altRes(self, value: _Integer) -> None: ...
    @property
    def altitudeInteger(self) -> o6.Int32: ...
    @altitudeInteger.setter
    def altitudeInteger(self, value: _Integer) -> None: ...
    @property
    def altitudeFraction(self) -> o6.Int16: ...
    @altitudeFraction.setter
    def altitudeFraction(self, value: _Integer) -> None: ...
    @property
    def datum(self) -> o6.Byte: ...
    @datum.setter
    def datum(self, value: _Integer) -> None: ...

class ScanDataEpc(ns0.datatypes.Structure):
    @property
    def pC(self) -> o6.UInt16: ...
    @pC.setter
    def pC(self, value: _Integer) -> None: ...
    @property
    def uId(self) -> o6.ByteString: ...
    @uId.setter
    def uId(self, value: o6.ByteString) -> None: ...
    @property
    def xPC_W1(self) -> o6.UInt16: ...
    @xPC_W1.setter
    def xPC_W1(self, value: _Integer) -> None: ...
    @property
    def xPC_W2(self) -> o6.UInt16: ...
    @xPC_W2.setter
    def xPC_W2(self, value: _Integer) -> None: ...

class ScanData(ns0.datatypes.Union):
    @property
    def byteString(self) -> o6.ByteString: ...
    @byteString.setter
    def byteString(self, value: o6.ByteString) -> None: ...
    @property
    def string(self) -> o6.String: ...
    @string.setter
    def string(self, value: o6.String) -> None: ...
    @property
    def epc(self) -> ScanDataEpc: ...
    @epc.setter
    def epc(self, value: ScanDataEpc) -> None: ...
    @property
    def custom(self) -> Any: ...
    @custom.setter
    def custom(self, value: Any) -> None: ...

class AccessResult(ns0.datatypes.Structure):
    """Result values of an AutoID Identifier access."""

    @property
    def codeType(self) -> o6.String | None: ...
    @codeType.setter
    def codeType(self, value: o6.String | None) -> None: ...
    @property
    def identifier(self) -> ScanData | None: ...
    @identifier.setter
    def identifier(self, value: ScanData | None) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime | None: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime | None) -> None: ...

class RfidAccessResult(AccessResult):
    """Additional result values of an Rfid Transponder access."""

    @property
    def codeType(self) -> o6.String | None: ...
    @codeType.setter
    def codeType(self, value: o6.String | None) -> None: ...
    @property
    def identifier(self) -> ScanData | None: ...
    @identifier.setter
    def identifier(self, value: ScanData | None) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime | None: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime | None) -> None: ...
    @property
    def codeTypeRWData(self) -> o6.String | None: ...
    @codeTypeRWData.setter
    def codeTypeRWData(self, value: o6.String | None) -> None: ...
    @property
    def rWData(self) -> ScanData | None: ...
    @rWData.setter
    def rWData(self, value: ScanData | None) -> None: ...
    @property
    def antenna(self) -> o6.Int32 | None: ...
    @antenna.setter
    def antenna(self, value: _Integer | None) -> None: ...
    @property
    def currentPowerLevel(self) -> o6.Int32 | None: ...
    @currentPowerLevel.setter
    def currentPowerLevel(self, value: _Integer | None) -> None: ...
    @property
    def pC(self) -> o6.UInt16 | None: ...
    @pC.setter
    def pC(self, value: _Integer | None) -> None: ...
    @property
    def polarization(self) -> o6.String | None: ...
    @polarization.setter
    def polarization(self, value: o6.String | None) -> None: ...
    @property
    def strength(self) -> o6.Int32 | None: ...
    @strength.setter
    def strength(self, value: _Integer | None) -> None: ...

class WGS84Coordinate(ns0.datatypes.Structure):
    @property
    def n_S_Hemisphere(self) -> o6.String: ...
    @n_S_Hemisphere.setter
    def n_S_Hemisphere(self, value: o6.String) -> None: ...
    @property
    def latitude(self) -> o6.Double: ...
    @latitude.setter
    def latitude(self, value: SupportsFloat) -> None: ...
    @property
    def e_W_Hemisphere(self) -> o6.String: ...
    @e_W_Hemisphere.setter
    def e_W_Hemisphere(self, value: o6.String) -> None: ...
    @property
    def longitude(self) -> o6.Double: ...
    @longitude.setter
    def longitude(self, value: SupportsFloat) -> None: ...
    @property
    def altitude(self) -> o6.Double: ...
    @altitude.setter
    def altitude(self, value: SupportsFloat) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def dilutionOfPrecision(self) -> o6.Double: ...
    @dilutionOfPrecision.setter
    def dilutionOfPrecision(self, value: SupportsFloat) -> None: ...
    @property
    def usefulPrecisionLatLon(self) -> o6.Int32: ...
    @usefulPrecisionLatLon.setter
    def usefulPrecisionLatLon(self, value: _Integer) -> None: ...
    @property
    def usefulPrecisionAlt(self) -> o6.Int32: ...
    @usefulPrecisionAlt.setter
    def usefulPrecisionAlt(self, value: _Integer) -> None: ...

class Location(ns0.datatypes.Union):
    @property
    def nMEA(self) -> o6.String: ...
    @nMEA.setter
    def nMEA(self, value: o6.String) -> None: ...
    @property
    def local(self) -> LocalCoordinate: ...
    @local.setter
    def local(self, value: LocalCoordinate) -> None: ...
    @property
    def wGS84(self) -> WGS84Coordinate: ...
    @wGS84.setter
    def wGS84(self, value: WGS84Coordinate) -> None: ...
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...

class ScanResult(ns0.datatypes.Structure):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...

class OcrScanResult(ScanResult):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...
    @property
    def imageId(self) -> o6.NodeId: ...
    @imageId.setter
    def imageId(self, value: o6.NodeId) -> None: ...
    @property
    def quality(self) -> o6.Byte: ...
    @quality.setter
    def quality(self, value: _Integer) -> None: ...
    @property
    def position(self) -> Position: ...
    @position.setter
    def position(self, value: Position) -> None: ...
    @property
    def font(self) -> o6.String | None: ...
    @font.setter
    def font(self, value: o6.String | None) -> None: ...
    @property
    def decodingTime(self) -> o6.DateTime | None: ...
    @decodingTime.setter
    def decodingTime(self, value: o6.DateTime | None) -> None: ...

class RfidScanResult(ScanResult):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...
    @property
    def sighting(self) -> list[RfidSighting]: ...
    @sighting.setter
    def sighting(self, value: Sequence[RfidSighting]) -> None: ...

class OpticalScanResult(ScanResult):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...
    @property
    def grade(self) -> o6.Float | None: ...
    @grade.setter
    def grade(self, value: SupportsFloat | None) -> None: ...
    @property
    def position(self) -> Position | None: ...
    @position.setter
    def position(self, value: Position | None) -> None: ...
    @property
    def symbology(self) -> o6.String | None: ...
    @symbology.setter
    def symbology(self, value: o6.String | None) -> None: ...
    @property
    def imageId(self) -> o6.NodeId | None: ...
    @imageId.setter
    def imageId(self, value: o6.NodeId | None) -> None: ...

class Rotation(ns0.datatypes.Structure):
    @property
    def yaw(self) -> o6.Double: ...
    @yaw.setter
    def yaw(self, value: SupportsFloat) -> None: ...
    @property
    def pitch(self) -> o6.Double: ...
    @pitch.setter
    def pitch(self, value: SupportsFloat) -> None: ...
    @property
    def roll(self) -> o6.Double: ...
    @roll.setter
    def roll(self, value: SupportsFloat) -> None: ...

class RtlsLocationResult(ScanResult):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...
    @property
    def speed(self) -> o6.Double: ...
    @speed.setter
    def speed(self, value: SupportsFloat) -> None: ...
    @property
    def heading(self) -> o6.Double: ...
    @heading.setter
    def heading(self, value: SupportsFloat) -> None: ...
    @property
    def rotation(self) -> Rotation: ...
    @rotation.setter
    def rotation(self, value: Rotation) -> None: ...
    @property
    def receiveTime(self) -> o6.DateTime: ...
    @receiveTime.setter
    def receiveTime(self, value: o6.DateTime) -> None: ...

class OpticalVerifierScanResult(OpticalScanResult):
    @property
    def codeType(self) -> o6.String: ...
    @codeType.setter
    def codeType(self, value: o6.String) -> None: ...
    @property
    def scanData(self) -> ScanData: ...
    @scanData.setter
    def scanData(self, value: ScanData) -> None: ...
    @property
    def timestamp(self) -> o6.DateTime: ...
    @timestamp.setter
    def timestamp(self, value: o6.DateTime) -> None: ...
    @property
    def location(self) -> Location | None: ...
    @location.setter
    def location(self, value: Location | None) -> None: ...
    @property
    def grade(self) -> o6.Float | None: ...
    @grade.setter
    def grade(self, value: SupportsFloat | None) -> None: ...
    @property
    def position(self) -> Position | None: ...
    @position.setter
    def position(self, value: Position | None) -> None: ...
    @property
    def symbology(self) -> o6.String | None: ...
    @symbology.setter
    def symbology(self, value: o6.String | None) -> None: ...
    @property
    def imageId(self) -> o6.NodeId | None: ...
    @imageId.setter
    def imageId(self, value: o6.NodeId | None) -> None: ...
    @property
    def isoGrade(self) -> o6.String: ...
    @isoGrade.setter
    def isoGrade(self, value: o6.String) -> None: ...
    @property
    def rMin(self) -> o6.Int16: ...
    @rMin.setter
    def rMin(self, value: _Integer) -> None: ...
    @property
    def symbolContrast(self) -> o6.Int16: ...
    @symbolContrast.setter
    def symbolContrast(self, value: _Integer) -> None: ...
    @property
    def eCMin(self) -> o6.Int16: ...
    @eCMin.setter
    def eCMin(self, value: _Integer) -> None: ...
    @property
    def modulation(self) -> o6.Int16: ...
    @modulation.setter
    def modulation(self, value: _Integer) -> None: ...
    @property
    def defects(self) -> o6.Int16: ...
    @defects.setter
    def defects(self, value: _Integer) -> None: ...
    @property
    def decodability(self) -> o6.Int16: ...
    @decodability.setter
    def decodability(self, value: _Integer) -> None: ...
    @property
    def decode(self) -> o6.Int16: ...
    @decode.setter
    def decode(self, value: _Integer) -> None: ...
    @property
    def printGain(self) -> o6.Int16: ...
    @printGain.setter
    def printGain(self, value: _Integer) -> None: ...

class CodeTypeDataType:
    pass
