# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.ns0 as ns0

class PubSubConnectionEndpointModeEnum(enum.IntFlag):
    PUBLISHER_SUBSCRIBER = 1
    PUBLISHER = 2
    SUBSCRIBER = 3

class FxCommandMask(enum.IntFlag):
    """This OptionSet defines flags indicating the commands a ConnectionManager may use in its call to the EstablishConnections Method."""

    VERIFY_ASSET_CMD = 0
    VERIFY_FUNCTIONAL_ENTITY_CMD = 1
    CREATE_CONNECTION_ENDPOINT_CMD = 2
    ESTABLISH_CONTROL_CMD = 3
    SET_CONFIGURATION_DATA_CMD = 4
    REASSIGN_CONTROL_CMD = 5
    RESERVE_COMMUNICATION_IDS_CMD = 6
    SET_COMMUNICATION_CONFIGURATION_CMD = 7
    ENABLE_COMMUNICATION_CMD = 8

class AssetVerificationModeEnum(enum.IntFlag):
    ASSET_COMPATIBILITY = 0
    ASSET_IDENTITY = 1
    ASSET_IDENTITY_AND_COMPATIBILITY = 2

class CommunicationConfigurationResultDataType(ns0.datatypes.Structure):
    pass

class NodeIdArray(ns0.datatypes.Structure):
    @property
    def node(self) -> o6.NodeId: ...
    @node.setter
    def node(self, value: o6.NodeId) -> None: ...
    @property
    def arrayIndex(self) -> list[o6.UInt32]: ...
    @arrayIndex.setter
    def arrayIndex(self, value: Sequence[_Integer]) -> None: ...

class NodeIdValuePair(ns0.datatypes.Structure):
    @property
    def key(self) -> NodeIdArray: ...
    @key.setter
    def key(self, value: NodeIdArray) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class AssetVerificationResultEnum(enum.IntFlag):
    NOT_SET = 0
    MATCH = 1
    COMPATIBLE = 2
    MISMATCH = 3

class AssetVerificationResultDataType(ns0.datatypes.Structure):
    @property
    def verificationStatus(self) -> o6.StatusCode: ...
    @verificationStatus.setter
    def verificationStatus(self, value: _Integer) -> None: ...
    @property
    def verificationResult(self) -> AssetVerificationResultEnum: ...
    @verificationResult.setter
    def verificationResult(self, value: _Integer) -> None: ...
    @property
    def verificationVariablesErrors(self) -> list[o6.StatusCode]: ...
    @verificationVariablesErrors.setter
    def verificationVariablesErrors(self, value: Sequence[_Integer]) -> None: ...
    @property
    def verificationAdditionalVariablesErrors(self) -> list[o6.StatusCode]: ...
    @verificationAdditionalVariablesErrors.setter
    def verificationAdditionalVariablesErrors(self, value: Sequence[_Integer]) -> None: ...

class PubSubCommunicationConfigurationResultDataType(CommunicationConfigurationResultDataType):
    @property
    def result(self) -> o6.StatusCode: ...
    @result.setter
    def result(self, value: _Integer) -> None: ...
    @property
    def changesApplied(self) -> o6.Boolean: ...
    @changesApplied.setter
    def changesApplied(self, value: _Boolean) -> None: ...
    @property
    def referenceResults(self) -> list[o6.StatusCode]: ...
    @referenceResults.setter
    def referenceResults(self, value: Sequence[_Integer]) -> None: ...
    @property
    def configurationValues(self) -> list[ns0.datatypes.PubSubConfigurationValueDataType]: ...
    @configurationValues.setter
    def configurationValues(self, value: Sequence[ns0.datatypes.PubSubConfigurationValueDataType]) -> None: ...
    @property
    def configurationObjects(self) -> list[o6.NodeId]: ...
    @configurationObjects.setter
    def configurationObjects(self, value: Sequence[o6.NodeId]) -> None: ...

class CommunicationConfigurationDataType(ns0.datatypes.Structure):
    pass

class PubSubCommunicationConfigurationDataType(CommunicationConfigurationDataType):
    @property
    def pubSubConfiguration(self) -> ns0.datatypes.PubSubConfiguration2DataType: ...
    @pubSubConfiguration.setter
    def pubSubConfiguration(self, value: ns0.datatypes.PubSubConfiguration2DataType) -> None: ...
    @property
    def requireCompleteUpdate(self) -> o6.Boolean: ...
    @requireCompleteUpdate.setter
    def requireCompleteUpdate(self, value: _Boolean) -> None: ...
    @property
    def configurationReferences(self) -> list[ns0.datatypes.PubSubConfigurationRefDataType]: ...
    @configurationReferences.setter
    def configurationReferences(self, value: Sequence[ns0.datatypes.PubSubConfigurationRefDataType]) -> None: ...

class AssetVerificationDataType(ns0.datatypes.Structure):
    @property
    def assetToVerify(self) -> o6.NodeId: ...
    @assetToVerify.setter
    def assetToVerify(self, value: o6.NodeId) -> None: ...
    @property
    def verificationMode(self) -> AssetVerificationModeEnum: ...
    @verificationMode.setter
    def verificationMode(self, value: _Integer) -> None: ...
    @property
    def expectedVerificationResult(self) -> AssetVerificationResultEnum: ...
    @expectedVerificationResult.setter
    def expectedVerificationResult(self, value: _Integer) -> None: ...
    @property
    def expectedVerificationVariables(self) -> list[ns0.datatypes.KeyValuePair]: ...
    @expectedVerificationVariables.setter
    def expectedVerificationVariables(self, value: Sequence[ns0.datatypes.KeyValuePair]) -> None: ...
    @property
    def expectedAdditionalVerificationVariables(self) -> list[NodeIdValuePair]: ...
    @expectedAdditionalVerificationVariables.setter
    def expectedAdditionalVerificationVariables(self, value: Sequence[NodeIdValuePair]) -> None: ...

class FunctionalEntityVerificationResultEnum(enum.IntFlag):
    NOT_SET = 0
    MATCH = 1
    MISMATCH = 2

class RelatedEndpointDataType(ns0.datatypes.Structure):
    @property
    def address(self) -> o6.String: ...
    @address.setter
    def address(self, value: o6.String) -> None: ...
    @property
    def connectionEndpointPath(self) -> list[ns0.datatypes.PortableQualifiedName]: ...
    @connectionEndpointPath.setter
    def connectionEndpointPath(self, value: Sequence[ns0.datatypes.PortableQualifiedName]) -> None: ...
    @property
    def connectionEndpointName(self) -> o6.String: ...
    @connectionEndpointName.setter
    def connectionEndpointName(self, value: o6.String) -> None: ...

class CommunicationLinkConfigurationDataType(ns0.datatypes.Structure):
    pass

class PubSubCommunicationLinkConfigurationDataType(CommunicationLinkConfigurationDataType):
    @property
    def dataSetReaderRef(self) -> ns0.datatypes.PubSubConfigurationRefDataType: ...
    @dataSetReaderRef.setter
    def dataSetReaderRef(self, value: ns0.datatypes.PubSubConfigurationRefDataType) -> None: ...
    @property
    def expectedSubscribedDataSetVersion(self) -> ns0.datatypes.ConfigurationVersionDataType: ...
    @expectedSubscribedDataSetVersion.setter
    def expectedSubscribedDataSetVersion(self, value: ns0.datatypes.ConfigurationVersionDataType) -> None: ...
    @property
    def dataSetWriterRef(self) -> ns0.datatypes.PubSubConfigurationRefDataType: ...
    @dataSetWriterRef.setter
    def dataSetWriterRef(self, value: ns0.datatypes.PubSubConfigurationRefDataType) -> None: ...
    @property
    def expectedPublishedDataSetVersion(self) -> ns0.datatypes.ConfigurationVersionDataType: ...
    @expectedPublishedDataSetVersion.setter
    def expectedPublishedDataSetVersion(self, value: ns0.datatypes.ConfigurationVersionDataType) -> None: ...

class ConnectionEndpointConfigurationResultDataType(ns0.datatypes.Structure):
    @property
    def connectionEndpointId(self) -> o6.NodeId: ...
    @connectionEndpointId.setter
    def connectionEndpointId(self, value: o6.NodeId) -> None: ...
    @property
    def functionalEntityNodeResult(self) -> o6.StatusCode: ...
    @functionalEntityNodeResult.setter
    def functionalEntityNodeResult(self, value: _Integer) -> None: ...
    @property
    def connectionEndpointResult(self) -> o6.StatusCode: ...
    @connectionEndpointResult.setter
    def connectionEndpointResult(self, value: _Integer) -> None: ...
    @property
    def verificationResult(self) -> FunctionalEntityVerificationResultEnum: ...
    @verificationResult.setter
    def verificationResult(self, value: _Integer) -> None: ...
    @property
    def verificationStatus(self) -> o6.StatusCode: ...
    @verificationStatus.setter
    def verificationStatus(self, value: _Integer) -> None: ...
    @property
    def verificationVariablesErrors(self) -> list[o6.StatusCode]: ...
    @verificationVariablesErrors.setter
    def verificationVariablesErrors(self, value: Sequence[_Integer]) -> None: ...
    @property
    def establishControlResult(self) -> list[o6.StatusCode]: ...
    @establishControlResult.setter
    def establishControlResult(self, value: Sequence[_Integer]) -> None: ...
    @property
    def configurationDataResult(self) -> list[o6.StatusCode]: ...
    @configurationDataResult.setter
    def configurationDataResult(self, value: Sequence[_Integer]) -> None: ...
    @property
    def reassignControlResult(self) -> list[o6.StatusCode]: ...
    @reassignControlResult.setter
    def reassignControlResult(self, value: Sequence[_Integer]) -> None: ...
    @property
    def communicationLinksResult(self) -> o6.StatusCode: ...
    @communicationLinksResult.setter
    def communicationLinksResult(self, value: _Integer) -> None: ...
    @property
    def enableCommunicationResult(self) -> o6.StatusCode: ...
    @enableCommunicationResult.setter
    def enableCommunicationResult(self, value: _Integer) -> None: ...

class ConnectionEndpointParameterDataType(ns0.datatypes.Structure):
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...
    @property
    def connectionEndpointTypeId(self) -> o6.NodeId: ...
    @connectionEndpointTypeId.setter
    def connectionEndpointTypeId(self, value: o6.NodeId) -> None: ...
    @property
    def inputVariableIds(self) -> list[o6.NodeId]: ...
    @inputVariableIds.setter
    def inputVariableIds(self, value: Sequence[o6.NodeId]) -> None: ...
    @property
    def outputVariableIds(self) -> list[o6.NodeId]: ...
    @outputVariableIds.setter
    def outputVariableIds(self, value: Sequence[o6.NodeId]) -> None: ...
    @property
    def isPersistent(self) -> o6.Boolean: ...
    @isPersistent.setter
    def isPersistent(self, value: _Boolean) -> None: ...
    @property
    def cleanupTimeout(self) -> o6.Double: ...
    @cleanupTimeout.setter
    def cleanupTimeout(self, value: SupportsFloat) -> None: ...
    @property
    def relatedEndpoint(self) -> RelatedEndpointDataType: ...
    @relatedEndpoint.setter
    def relatedEndpoint(self, value: RelatedEndpointDataType) -> None: ...
    @property
    def isPreconfigured(self) -> o6.Boolean: ...
    @isPreconfigured.setter
    def isPreconfigured(self, value: _Boolean) -> None: ...

class PubSubConnectionEndpointParameterDataType(ConnectionEndpointParameterDataType):
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...
    @property
    def connectionEndpointTypeId(self) -> o6.NodeId: ...
    @connectionEndpointTypeId.setter
    def connectionEndpointTypeId(self, value: o6.NodeId) -> None: ...
    @property
    def inputVariableIds(self) -> list[o6.NodeId]: ...
    @inputVariableIds.setter
    def inputVariableIds(self, value: Sequence[o6.NodeId]) -> None: ...
    @property
    def outputVariableIds(self) -> list[o6.NodeId]: ...
    @outputVariableIds.setter
    def outputVariableIds(self, value: Sequence[o6.NodeId]) -> None: ...
    @property
    def isPersistent(self) -> o6.Boolean: ...
    @isPersistent.setter
    def isPersistent(self, value: _Boolean) -> None: ...
    @property
    def cleanupTimeout(self) -> o6.Double: ...
    @cleanupTimeout.setter
    def cleanupTimeout(self, value: SupportsFloat) -> None: ...
    @property
    def relatedEndpoint(self) -> RelatedEndpointDataType: ...
    @relatedEndpoint.setter
    def relatedEndpoint(self, value: RelatedEndpointDataType) -> None: ...
    @property
    def isPreconfigured(self) -> o6.Boolean: ...
    @isPreconfigured.setter
    def isPreconfigured(self, value: _Boolean) -> None: ...
    @property
    def mode(self) -> PubSubConnectionEndpointModeEnum: ...
    @mode.setter
    def mode(self, value: _Integer) -> None: ...

class ConnectionEndpointDefinitionDataType(ns0.datatypes.Union):
    @property
    def parameter(self) -> ConnectionEndpointParameterDataType: ...
    @parameter.setter
    def parameter(self, value: ConnectionEndpointParameterDataType) -> None: ...
    @property
    def node(self) -> o6.NodeId: ...
    @node.setter
    def node(self, value: o6.NodeId) -> None: ...

class ConnectionEndpointConfigurationDataType(ns0.datatypes.Structure):
    @property
    def functionalEntityNode(self) -> o6.NodeId: ...
    @functionalEntityNode.setter
    def functionalEntityNode(self, value: o6.NodeId) -> None: ...
    @property
    def connectionEndpoint(self) -> ConnectionEndpointDefinitionDataType: ...
    @connectionEndpoint.setter
    def connectionEndpoint(self, value: ConnectionEndpointDefinitionDataType) -> None: ...
    @property
    def expectedVerificationVariables(self) -> list[NodeIdValuePair]: ...
    @expectedVerificationVariables.setter
    def expectedVerificationVariables(self, value: Sequence[NodeIdValuePair]) -> None: ...
    @property
    def controlGroups(self) -> list[o6.NodeId]: ...
    @controlGroups.setter
    def controlGroups(self, value: Sequence[o6.NodeId]) -> None: ...
    @property
    def configurationData(self) -> list[NodeIdValuePair]: ...
    @configurationData.setter
    def configurationData(self, value: Sequence[NodeIdValuePair]) -> None: ...
    @property
    def communicationLinks(self) -> CommunicationLinkConfigurationDataType: ...
    @communicationLinks.setter
    def communicationLinks(self, value: CommunicationLinkConfigurationDataType) -> None: ...

class FxTimeUnitsEnum(enum.IntFlag):
    """This enumeration describes the support units of time"""

    NANOSECOND = 0
    MICROSECOND = 1
    MILLISECOND = 2
    SECOND = 3

class ReserveCommunicationIdsDataType(ns0.datatypes.Structure):
    pass

class PubSubReserveCommunicationIdsDataType(ReserveCommunicationIdsDataType):
    @property
    def transportProfileUri(self) -> o6.String: ...
    @transportProfileUri.setter
    def transportProfileUri(self, value: o6.String) -> None: ...
    @property
    def numReqWriterGroupIds(self) -> o6.UInt16: ...
    @numReqWriterGroupIds.setter
    def numReqWriterGroupIds(self, value: _Integer) -> None: ...
    @property
    def numReqDataSetWriterIds(self) -> o6.UInt16: ...
    @numReqDataSetWriterIds.setter
    def numReqDataSetWriterIds(self, value: _Integer) -> None: ...

class PubSubReserveCommunicationIds2DataType(PubSubReserveCommunicationIdsDataType):
    @property
    def transportProfileUri(self) -> o6.String: ...
    @transportProfileUri.setter
    def transportProfileUri(self, value: o6.String) -> None: ...
    @property
    def numReqWriterGroupIds(self) -> o6.UInt16: ...
    @numReqWriterGroupIds.setter
    def numReqWriterGroupIds(self, value: _Integer) -> None: ...
    @property
    def numReqDataSetWriterIds(self) -> o6.UInt16: ...
    @numReqDataSetWriterIds.setter
    def numReqDataSetWriterIds(self, value: _Integer) -> None: ...
    @property
    def requestTransportSpecificInfo(self) -> o6.Boolean: ...
    @requestTransportSpecificInfo.setter
    def requestTransportSpecificInfo(self, value: _Boolean) -> None: ...

class ReserveCommunicationIdsResultDataType(ns0.datatypes.Structure):
    pass

class PubSubReserveCommunicationIdsResultDataType(ReserveCommunicationIdsResultDataType):
    @property
    def result(self) -> o6.StatusCode: ...
    @result.setter
    def result(self, value: _Integer) -> None: ...
    @property
    def defaultPublisherId(self) -> Any: ...
    @defaultPublisherId.setter
    def defaultPublisherId(self, value: Any) -> None: ...
    @property
    def writerGroupIds(self) -> list[o6.UInt16]: ...
    @writerGroupIds.setter
    def writerGroupIds(self, value: Sequence[_Integer]) -> None: ...
    @property
    def dataSetWriterIds(self) -> list[o6.UInt16]: ...
    @dataSetWriterIds.setter
    def dataSetWriterIds(self, value: Sequence[_Integer]) -> None: ...

class PubSubReserveCommunicationIdsResult2DataType(PubSubReserveCommunicationIdsResultDataType):
    @property
    def result(self) -> o6.StatusCode: ...
    @result.setter
    def result(self, value: _Integer) -> None: ...
    @property
    def defaultPublisherId(self) -> Any: ...
    @defaultPublisherId.setter
    def defaultPublisherId(self, value: Any) -> None: ...
    @property
    def writerGroupIds(self) -> list[o6.UInt16]: ...
    @writerGroupIds.setter
    def writerGroupIds(self, value: Sequence[_Integer]) -> None: ...
    @property
    def dataSetWriterIds(self) -> list[o6.UInt16]: ...
    @dataSetWriterIds.setter
    def dataSetWriterIds(self, value: Sequence[_Integer]) -> None: ...
    @property
    def transportSpecificInfo(self) -> Any: ...
    @transportSpecificInfo.setter
    def transportSpecificInfo(self, value: Any) -> None: ...

class IntervalRange(ns0.datatypes.Structure):
    @property
    def min(self) -> o6.UInt32: ...
    @min.setter
    def min(self, value: _Integer) -> None: ...
    @property
    def max(self) -> o6.UInt32: ...
    @max.setter
    def max(self, value: _Integer) -> None: ...
    @property
    def increment(self) -> o6.UInt16: ...
    @increment.setter
    def increment(self, value: _Integer) -> None: ...
    @property
    def multiplier(self) -> o6.UInt16: ...
    @multiplier.setter
    def multiplier(self, value: _Integer) -> None: ...
    @property
    def unit(self) -> FxTimeUnitsEnum: ...
    @unit.setter
    def unit(self, value: _Integer) -> None: ...
