# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.ns0 as ns0

class ProductIdDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class PartIdDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class ProcessingTimesDataType(ns0.datatypes.Structure):
    @property
    def startTime(self) -> o6.DateTime: ...
    @startTime.setter
    def startTime(self, value: o6.DateTime) -> None: ...
    @property
    def endTime(self) -> o6.DateTime: ...
    @endTime.setter
    def endTime(self, value: o6.DateTime) -> None: ...
    @property
    def acquisitionDuration(self) -> o6.Double | None: ...
    @acquisitionDuration.setter
    def acquisitionDuration(self, value: SupportsFloat | None) -> None: ...
    @property
    def processingDuration(self) -> o6.Double | None: ...
    @processingDuration.setter
    def processingDuration(self, value: SupportsFloat | None) -> None: ...

class ResultStateDataType:
    pass

class TriStateBooleanDataType(enum.IntFlag):
    FALSE_0 = 0
    TRUE_1 = 1
    DONTCARE_2 = 2

class MeasIdDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class JobIdDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class TrimmedString:
    pass

class Handle:
    pass

class BinaryIdBaseDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...
    @property
    def hash(self) -> o6.ByteString | None: ...
    @hash.setter
    def hash(self, value: o6.ByteString | None) -> None: ...
    @property
    def hashAlgorithm(self) -> o6.String | None: ...
    @hashAlgorithm.setter
    def hashAlgorithm(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class RecipeIdExternalDataType(BinaryIdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...
    @property
    def hash(self) -> o6.ByteString | None: ...
    @hash.setter
    def hash(self, value: o6.ByteString | None) -> None: ...
    @property
    def hashAlgorithm(self) -> o6.String | None: ...
    @hashAlgorithm.setter
    def hashAlgorithm(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class ConfigurationIdDataType(BinaryIdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...
    @property
    def hash(self) -> o6.ByteString | None: ...
    @hash.setter
    def hash(self, value: o6.ByteString | None) -> None: ...
    @property
    def hashAlgorithm(self) -> o6.String | None: ...
    @hashAlgorithm.setter
    def hashAlgorithm(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class ConfigurationDataType(ns0.datatypes.Structure):
    @property
    def hasTransferableDataOnFile(self) -> o6.Boolean | None: ...
    @hasTransferableDataOnFile.setter
    def hasTransferableDataOnFile(self, value: _Boolean | None) -> None: ...
    @property
    def externalId(self) -> ConfigurationIdDataType | None: ...
    @externalId.setter
    def externalId(self, value: ConfigurationIdDataType | None) -> None: ...
    @property
    def internalId(self) -> ConfigurationIdDataType: ...
    @internalId.setter
    def internalId(self, value: ConfigurationIdDataType) -> None: ...
    @property
    def lastModified(self) -> o6.DateTime: ...
    @lastModified.setter
    def lastModified(self, value: o6.DateTime) -> None: ...

class ConfigurationTransferOptions(ns0.datatypes.Structure):
    @property
    def internalId(self) -> ConfigurationIdDataType: ...
    @internalId.setter
    def internalId(self, value: ConfigurationIdDataType) -> None: ...

class RecipeIdInternalDataType(BinaryIdBaseDataType):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...
    @property
    def hash(self) -> o6.ByteString | None: ...
    @hash.setter
    def hash(self, value: o6.ByteString | None) -> None: ...
    @property
    def hashAlgorithm(self) -> o6.String | None: ...
    @hashAlgorithm.setter
    def hashAlgorithm(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.LocalizedText | None: ...
    @description.setter
    def description(self, value: o6.LocalizedText | None) -> None: ...

class RecipeTransferOptions(ns0.datatypes.Structure):
    @property
    def internalId(self) -> RecipeIdInternalDataType: ...
    @internalId.setter
    def internalId(self, value: RecipeIdInternalDataType) -> None: ...

class ProductDataType(ns0.datatypes.Structure):
    @property
    def externalId(self) -> ProductIdDataType: ...
    @externalId.setter
    def externalId(self, value: ProductIdDataType) -> None: ...

class ResultIdDataType(ns0.datatypes.Structure):
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class ResultDataType(ns0.datatypes.Structure):
    @property
    def resultId(self) -> ResultIdDataType: ...
    @resultId.setter
    def resultId(self, value: ResultIdDataType) -> None: ...
    @property
    def hasTransferableDataOnFile(self) -> o6.Boolean | None: ...
    @hasTransferableDataOnFile.setter
    def hasTransferableDataOnFile(self, value: _Boolean | None) -> None: ...
    @property
    def isPartial(self) -> o6.Boolean: ...
    @isPartial.setter
    def isPartial(self, value: _Boolean) -> None: ...
    @property
    def isSimulated(self) -> o6.Boolean | None: ...
    @isSimulated.setter
    def isSimulated(self, value: _Boolean | None) -> None: ...
    @property
    def resultState(self) -> o6.Int32: ...
    @resultState.setter
    def resultState(self, value: _Integer) -> None: ...
    @property
    def measId(self) -> MeasIdDataType | None: ...
    @measId.setter
    def measId(self, value: MeasIdDataType | None) -> None: ...
    @property
    def partId(self) -> PartIdDataType | None: ...
    @partId.setter
    def partId(self, value: PartIdDataType | None) -> None: ...
    @property
    def externalRecipeId(self) -> RecipeIdExternalDataType | None: ...
    @externalRecipeId.setter
    def externalRecipeId(self, value: RecipeIdExternalDataType | None) -> None: ...
    @property
    def internalRecipeId(self) -> RecipeIdInternalDataType: ...
    @internalRecipeId.setter
    def internalRecipeId(self, value: RecipeIdInternalDataType) -> None: ...
    @property
    def productId(self) -> ProductIdDataType | None: ...
    @productId.setter
    def productId(self, value: ProductIdDataType | None) -> None: ...
    @property
    def externalConfigurationId(self) -> ConfigurationIdDataType | None: ...
    @externalConfigurationId.setter
    def externalConfigurationId(self, value: ConfigurationIdDataType | None) -> None: ...
    @property
    def internalConfigurationId(self) -> ConfigurationIdDataType: ...
    @internalConfigurationId.setter
    def internalConfigurationId(self, value: ConfigurationIdDataType) -> None: ...
    @property
    def jobId(self) -> JobIdDataType: ...
    @jobId.setter
    def jobId(self, value: JobIdDataType) -> None: ...
    @property
    def creationTime(self) -> o6.DateTime: ...
    @creationTime.setter
    def creationTime(self, value: o6.DateTime) -> None: ...
    @property
    def processingTimes(self) -> ProcessingTimesDataType | None: ...
    @processingTimes.setter
    def processingTimes(self, value: ProcessingTimesDataType | None) -> None: ...
    @property
    def resultContent(self) -> list[Any] | None: ...
    @resultContent.setter
    def resultContent(self, value: Sequence[Any] | None) -> None: ...

class ResultTransferOptions(ns0.datatypes.Structure):
    @property
    def id(self) -> ResultIdDataType: ...
    @id.setter
    def id(self, value: ResultIdDataType) -> None: ...

class SystemStateDataType(enum.IntFlag):
    PRD_1 = 1
    SBY_2 = 2
    ENG_3 = 3
    SDT_4 = 4
    UDT_5 = 5
    NST_6 = 6

class SystemStateDescriptionDataType(ns0.datatypes.Structure):
    @property
    def state(self) -> SystemStateDataType: ...
    @state.setter
    def state(self, value: _Integer) -> None: ...
    @property
    def stateDescription(self) -> o6.String | None: ...
    @stateDescription.setter
    def stateDescription(self, value: o6.String | None) -> None: ...
