# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.ns0 as ns0

import o6.ns.pack_ml as pack_ml

class MessageType(ns0.datatypes.Structure):
    """The MessageType provides a uniquely identified localised text."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def localText(self) -> o6.LocalizedText: ...
    @localText.setter
    def localText(self, value: o6.LocalizedText) -> None: ...

class DataSetEntryType(ns0.datatypes.Structure):
    """The DataSetEntryType structure contains the value of a single parameter, or data value."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class ParameterDependencyEnumeration(enum.IntFlag):
    """The ParameterDependencyEnumeration contains what a parameter is depending upon."""

    MACHINE = 0
    BRAND = 1
    MACHINE_AND__BRAND = 2

class CommandEnumeration(enum.IntFlag):
    """The CommandEnumeration provides standardized commands that can be sent to a state machine."""

    ABORT = 0
    START = 1
    STOP = 2
    RESET = 3
    HOLD = 4
    UNHOLD = 5
    CLEAR = 6
    SUSPEND = 7
    UNSUSPEND = 8

class StateEnumeration(enum.IntFlag):
    """The StateEnumeration contains the PackML states for a machine."""

    STOPPED = 0
    RESETTING = 1
    IDLE = 2
    STARTING = 3
    EXECUTE = 4
    COMPLETING = 5
    COMPLETE = 6
    ABORTING = 7
    ABORTED = 8
    STOPPING = 9
    CLEARING = 10
    SUSPENDING = 11
    SUSPENDED = 12
    UNSUSPENDING = 13
    HOLDING = 14
    HELD = 15
    UNHOLDING = 16

class MethodExecutionFeedbackType(ns0.datatypes.Structure):
    """The MethodExecutionFeedbackType provides suitable feedback, both positive and negative, to an OPC UA client invoking a method."""

    @property
    def success(self) -> o6.Boolean: ...
    @success.setter
    def success(self, value: _Boolean) -> None: ...
    @property
    def message(self) -> list[MessageType]: ...
    @message.setter
    def message(self, value: Sequence[MessageType]) -> None: ...

class StorageLogicEnumeration(enum.IntFlag):
    """The StorageLogicEnumeration describes standard loading and unloading material
    configurations."""

    OTHER = 0
    FIFO = 1
    LIFO = 2
    FEFO = 3

class ProductionStatusEnumeration(enum.IntFlag):
    """The ProductionStatusEnumeration contains the production state of a machine module."""

    OTHER = 0
    BRAND_CHANGE = 1
    PRODUCTION = 2
    NO_PRODUCTION = 3

class DataSetType(ns0.datatypes.Structure):
    """The DataSetType structure contains a set of data values."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def values(self) -> list[DataSetEntryType]: ...
    @values.setter
    def values(self, value: Sequence[DataSetEntryType]) -> None: ...

class DataDescriptionType(ns0.datatypes.Structure):
    """The DataDescriptionType structure contains a metadata, i.e. a description."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...

class DataDefinitionType(DataDescriptionType):
    """The DataDefinitionType structure contains the metadata that describes a parameter."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def displayFormat(self) -> o6.String: ...
    @displayFormat.setter
    def displayFormat(self, value: o6.String) -> None: ...
    @property
    def dependency(self) -> ParameterDependencyEnumeration: ...
    @dependency.setter
    def dependency(self, value: _Integer) -> None: ...
    @property
    def dataType(self) -> o6.String: ...
    @dataType.setter
    def dataType(self, value: o6.String) -> None: ...
    @property
    def userSubset(self) -> o6.Boolean: ...
    @userSubset.setter
    def userSubset(self, value: _Boolean) -> None: ...
    @property
    def controlRange(self) -> ns0.datatypes.Range: ...
    @controlRange.setter
    def controlRange(self, value: ns0.datatypes.Range) -> None: ...
    @property
    def alarmRange(self) -> ns0.datatypes.Range: ...
    @alarmRange.setter
    def alarmRange(self, value: ns0.datatypes.Range) -> None: ...

class DataValueType(DataDescriptionType):
    """The DataValueType structure contains a data value."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation) -> None: ...

class MaterialDefinitionType(ns0.datatypes.Structure):
    """The MaterialDefinitionType structure contains the definition of a material. It is harmonised with
    ISA 95 Material Definition."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def baseUnitOfMeasure(self) -> ns0.datatypes.EUInformation: ...
    @baseUnitOfMeasure.setter
    def baseUnitOfMeasure(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def batchManaged(self) -> o6.Boolean: ...
    @batchManaged.setter
    def batchManaged(self, value: _Boolean) -> None: ...
    @property
    def groupID(self) -> o6.String | None: ...
    @groupID.setter
    def groupID(self, value: o6.String | None) -> None: ...
    @property
    def parentGroupID(self) -> o6.String | None: ...
    @parentGroupID.setter
    def parentGroupID(self, value: o6.String | None) -> None: ...
    @property
    def shelfLife(self) -> o6.UInt32 | None: ...
    @shelfLife.setter
    def shelfLife(self, value: _Integer | None) -> None: ...
    @property
    def properties(self) -> list[DataValueType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[DataValueType] | None) -> None: ...

class MaterialPointType(ns0.datatypes.Structure):
    """The MaterialPointType structure provides the description of the capability of a load or
    unload point."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def materialCapability(self) -> list[MaterialDefinitionType]: ...
    @materialCapability.setter
    def materialCapability(self, value: Sequence[MaterialDefinitionType]) -> None: ...
    @property
    def connectedMaterialPoint(self) -> o6.ExpandedNodeId: ...
    @connectedMaterialPoint.setter
    def connectedMaterialPoint(self, value: o6.ExpandedNodeId) -> None: ...
    @property
    def propagatesProductionOrder(self) -> o6.Boolean: ...
    @propagatesProductionOrder.setter
    def propagatesProductionOrder(self, value: _Boolean) -> None: ...

class ProductionOrderHeaderType(ns0.datatypes.Structure):
    """The ProductionOrderHeaderType structure contains the header information for a production
    order."""

    @property
    def number(self) -> o6.String: ...
    @number.setter
    def number(self, value: o6.String) -> None: ...
    @property
    def producedMaterial(self) -> MaterialDefinitionType: ...
    @producedMaterial.setter
    def producedMaterial(self, value: MaterialDefinitionType) -> None: ...
    @property
    def targetQuantity(self) -> o6.Double: ...
    @targetQuantity.setter
    def targetQuantity(self, value: SupportsFloat) -> None: ...
    @property
    def continueAtJobEnd(self) -> o6.Boolean: ...
    @continueAtJobEnd.setter
    def continueAtJobEnd(self, value: _Boolean) -> None: ...
    @property
    def targetStartTime(self) -> o6.DateTime: ...
    @targetStartTime.setter
    def targetStartTime(self, value: o6.DateTime) -> None: ...
    @property
    def targetEndTime(self) -> o6.DateTime: ...
    @targetEndTime.setter
    def targetEndTime(self, value: o6.DateTime) -> None: ...
    @property
    def dataSetID(self) -> o6.String: ...
    @dataSetID.setter
    def dataSetID(self, value: o6.String) -> None: ...
    @property
    def dataSetDescription(self) -> o6.LocalizedText: ...
    @dataSetDescription.setter
    def dataSetDescription(self, value: o6.LocalizedText) -> None: ...
    @property
    def materialListID(self) -> o6.String: ...
    @materialListID.setter
    def materialListID(self, value: o6.String) -> None: ...
    @property
    def materialListDescription(self) -> o6.LocalizedText: ...
    @materialListDescription.setter
    def materialListDescription(self, value: o6.LocalizedText) -> None: ...

class MaterialIntegrityAgentEnumeration(enum.IntFlag):
    """The MaterialIntegrityAgentEnumeration identifies the possible agents responsible for material integrity checking."""

    NONE = 0
    LOCAL = 1
    EXTERNAL = 2

class DataSetDefinitionType(ns0.datatypes.Structure):
    """The DataSetDefinition structure contains the description and other necessary metadata of the
    complete set of machine settings required for production."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def definitions(self) -> list[DataDefinitionType]: ...
    @definitions.setter
    def definitions(self, value: Sequence[DataDefinitionType]) -> None: ...

class ControlModeEnumeration(enum.IntFlag):
    """The ControlModeEnumeration contains the PackML modes of operation of a machine."""

    OTHER = 0
    PRODUCTION = 1
    MAINTENANCE = 2
    MANUAL = 3
    CHANGE_OVER = 4
    CLEAN = 5
    SET_UP = 6
    EMPTY_OUT = 7
    REMOTE_SERVICE = 8

class MotorDirectionEnumeration(enum.IntFlag):
    """The MotorDirectionEnumeration provides the rotation direction of a motor."""

    CLOCKWISE = 0
    COUNTER_CLOCKWISE = 1

class RootCauseMessageType(MessageType):
    """The RootCauseMessageType structure contains a root cause message and its group identifier."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def localText(self) -> o6.LocalizedText: ...
    @localText.setter
    def localText(self, value: o6.LocalizedText) -> None: ...
    @property
    def groupID(self) -> o6.String: ...
    @groupID.setter
    def groupID(self, value: o6.String) -> None: ...

class RootCauseGroupType(ns0.datatypes.Structure):
    """The RootCauseGroupType structure contains a root cause message and its group identifier."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def parentID(self) -> o6.String: ...
    @parentID.setter
    def parentID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...

class StorageMixingLogicEnumeration(enum.IntFlag):
    """The StorageMixingLogicEnumeration describes standard ways of mixing material in a material
    storage buffer."""

    MIXING = 0
    NON_MIXING_BY_PRODUCT = 1
    NON_MIXING_BY_BATCH = 2

class MaterialStorageBufferDataType(ns0.datatypes.Structure):
    """The MaterialStorageBufferDataType structure provides the description of the capability of a
    material storage buffer."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def storedMaterial(self) -> MaterialDefinitionType: ...
    @storedMaterial.setter
    def storedMaterial(self, value: MaterialDefinitionType) -> None: ...
    @property
    def engineeringUnits(self) -> ns0.datatypes.EUInformation: ...
    @engineeringUnits.setter
    def engineeringUnits(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def totalStorageCapacity(self) -> o6.Double: ...
    @totalStorageCapacity.setter
    def totalStorageCapacity(self, value: SupportsFloat) -> None: ...
    @property
    def storageLogic(self) -> StorageLogicEnumeration: ...
    @storageLogic.setter
    def storageLogic(self, value: _Integer) -> None: ...
    @property
    def mixingLogic(self) -> StorageMixingLogicEnumeration: ...
    @mixingLogic.setter
    def mixingLogic(self, value: _Integer) -> None: ...

class MaterialStockStatusEnumeration(enum.IntFlag):
    """The MaterialStockStatusEnumeration provides the stock status for a material lot."""

    UNRESTRICTED = 0
    QUALITY_INSPECTION = 1
    BLOCKED = 2

class MaterialLotType(ns0.datatypes.Structure):
    """The MaterialLotType structure contains the material lot information. It is harmonised with ISA
    95 Material Lot."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def materialDefinition(self) -> MaterialDefinitionType: ...
    @materialDefinition.setter
    def materialDefinition(self, value: MaterialDefinitionType) -> None: ...
    @property
    def status(self) -> MaterialStockStatusEnumeration: ...
    @status.setter
    def status(self, value: _Integer) -> None: ...
    @property
    def productionDate(self) -> o6.DateTime: ...
    @productionDate.setter
    def productionDate(self, value: o6.DateTime) -> None: ...
    @property
    def bestUsedBeforeDate(self) -> o6.DateTime | None: ...
    @bestUsedBeforeDate.setter
    def bestUsedBeforeDate(self, value: o6.DateTime | None) -> None: ...
    @property
    def properties(self) -> list[DataValueType] | None: ...
    @properties.setter
    def properties(self, value: Sequence[DataValueType] | None) -> None: ...

class MaterialSublotType(ns0.datatypes.Structure):
    """The MaterialSublotType structure contains the material sublot information. It is harmonised with
    ISA 95 Material Sublot."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def mES_ID(self) -> o6.String: ...
    @mES_ID.setter
    def mES_ID(self, value: o6.String) -> None: ...
    @property
    def materialLot(self) -> MaterialLotType: ...
    @materialLot.setter
    def materialLot(self, value: MaterialLotType) -> None: ...
    @property
    def materialStorageLocationID(self) -> o6.String: ...
    @materialStorageLocationID.setter
    def materialStorageLocationID(self, value: o6.String) -> None: ...
    @property
    def quantity(self) -> o6.Double: ...
    @quantity.setter
    def quantity(self, value: SupportsFloat) -> None: ...
    @property
    def carrierID(self) -> o6.String | None: ...
    @carrierID.setter
    def carrierID(self, value: o6.String | None) -> None: ...
    @property
    def relativePositionID(self) -> o6.String | None: ...
    @relativePositionID.setter
    def relativePositionID(self, value: o6.String | None) -> None: ...
    @property
    def parentSublotID(self) -> o6.String | None: ...
    @parentSublotID.setter
    def parentSublotID(self, value: o6.String | None) -> None: ...
    @property
    def sublots(self) -> list[MaterialSublotType] | None: ...
    @sublots.setter
    def sublots(self, value: Sequence[MaterialSublotType] | None) -> None: ...

class MaterialListItemType(ns0.datatypes.Structure):
    """The MaterialListItemType structure contains a single material to be processed."""

    @property
    def assemblyID(self) -> o6.String: ...
    @assemblyID.setter
    def assemblyID(self, value: o6.String) -> None: ...
    @property
    def materialPointID(self) -> o6.String: ...
    @materialPointID.setter
    def materialPointID(self, value: o6.String) -> None: ...
    @property
    def materialPointMES_ID(self) -> o6.String: ...
    @materialPointMES_ID.setter
    def materialPointMES_ID(self, value: o6.String) -> None: ...
    @property
    def materialSublot(self) -> MaterialSublotType: ...
    @materialSublot.setter
    def materialSublot(self, value: MaterialSublotType) -> None: ...
    @property
    def materialStockStatus(self) -> MaterialStockStatusEnumeration: ...
    @materialStockStatus.setter
    def materialStockStatus(self, value: _Integer) -> None: ...
    @property
    def followUpMaterials(self) -> list[MaterialSublotType]: ...
    @followUpMaterials.setter
    def followUpMaterials(self, value: Sequence[MaterialSublotType]) -> None: ...

class MaterialListType(ns0.datatypes.Structure):
    """The MaterialListType structure contains a set of material list items."""

    @property
    def iD(self) -> o6.String: ...
    @iD.setter
    def iD(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.LocalizedText: ...
    @description.setter
    def description(self, value: o6.LocalizedText) -> None: ...
    @property
    def items(self) -> list[MaterialListItemType]: ...
    @items.setter
    def items(self, value: Sequence[MaterialListItemType]) -> None: ...

class ProductionOrderType(ns0.datatypes.Structure):
    """The ProductionOrderType structure contains the complete production order information."""

    @property
    def header(self) -> ProductionOrderHeaderType: ...
    @header.setter
    def header(self, value: ProductionOrderHeaderType) -> None: ...
    @property
    def materialList(self) -> MaterialListType: ...
    @materialList.setter
    def materialList(self, value: MaterialListType) -> None: ...
    @property
    def dataSet(self) -> DataSetType: ...
    @dataSet.setter
    def dataSet(self, value: DataSetType) -> None: ...

class OrchestrationProductionOrderType(ProductionOrderType):
    """The OrchestrationProductionOrderType structure contains the complete production order
    information used by the Production Order Orchestration Layer."""

    @property
    def header(self) -> ProductionOrderHeaderType: ...
    @header.setter
    def header(self, value: ProductionOrderHeaderType) -> None: ...
    @property
    def materialList(self) -> MaterialListType: ...
    @materialList.setter
    def materialList(self, value: MaterialListType) -> None: ...
    @property
    def dataSet(self) -> DataSetType: ...
    @dataSet.setter
    def dataSet(self, value: DataSetType) -> None: ...
    @property
    def activeMachineModules(self) -> list[o6.String]: ...
    @activeMachineModules.setter
    def activeMachineModules(self, value: Sequence[o6.String]) -> None: ...

class MaterialValidationStatusEnumeration(enum.IntFlag):
    """The MaterialValidationStatusEnumeration describes the status of the material validation
    process."""

    NONE = 0
    WAITING = 1
    PASSED = 2
    FAILED = 3
