# AUTO-GENERATED — DO NOT EDIT
# source-sha256: a82b37bf0e73186c689fa861d93cafc10aa1f23e80a086debd104a46240e1a83
# Run tools/update_ns.py to regenerate.
from __future__ import annotations

_URI: str = "http://opcfoundation.org/UA/Mining/ExternalStandards/IREDES"
_VERSION: str = "1.0.0"
_REQUIRED: list = [{"uri": "http://opcfoundation.org/UA/", "version": "1.05.02"}]
_STRUCTURES: list = [
    (
        "ns=1;i=3003",
        "IRLengthDataType",
        "ns=1;i=5001",
        {
            "structure_type": 0,
            "fields": [
                {"name": "Value", "data_type": "i=11", "value_rank": -1},
                {"name": "Unit", "data_type": "i=887", "value_rank": -1},
            ],
        },
    ),
    (
        "ns=1;i=3004",
        "JobAssignmentTimeDataType",
        "ns=1;i=5004",
        {
            "structure_type": 0,
            "fields": [
                {"name": "ExpectedFinishTime", "data_type": "i=13", "value_rank": -1},
                {"name": "ExpectedDuration", "data_type": "i=290", "value_rank": -1},
            ],
        },
    ),
]
_ENUMS: list = [
    (
        "ns=1;i=3009",
        "Answer",
        {
            "fields": [
                {"name": "Accepted", "value": 0, "display_name": "Accepted"},
                {"name": "Delayed", "value": 1, "display_name": "Delayed"},
                {
                    "name": "AcceptedWithCondition",
                    "value": 2,
                    "display_name": "AcceptedWithCondition",
                },
                {"name": "Denied", "value": 3, "display_name": "Denied"},
            ]
        },
    ),
    (
        "ns=1;i=3006",
        "DispFlag",
        {
            "fields": [
                {"name": "MachStart", "value": 0, "display_name": "MachStart"},
                {"name": "FileLoad", "value": 1, "display_name": "FileLoad"},
            ]
        },
    ),
    (
        "ns=1;i=3018",
        "LTPPMaction",
        {
            "fields": [
                {"name": "Load", "value": 0, "display_name": "Load"},
                {"name": "Dump", "value": 1, "display_name": "Dump"},
                {"name": "Parking", "value": 2, "display_name": "Parking"},
                {"name": "Workshop", "value": 3, "display_name": "Workshop"},
                {"name": "Other", "value": 4, "display_name": "Other"},
            ]
        },
    ),
    (
        "ns=1;i=3012",
        "LTPPMptFromType",
        {
            "fields": [
                {"name": "LoadPt", "value": 0, "display_name": "LoadPt"},
                {"name": "DumpPt", "value": 1, "display_name": "DumpPt"},
                {"name": "Parking", "value": 2, "display_name": "Parking"},
                {"name": "Workshop", "value": 3, "display_name": "Workshop"},
                {"name": "Others", "value": 4, "display_name": "Others"},
            ]
        },
    ),
    (
        "ns=1;i=3015",
        "LTPPMptToType",
        {
            "fields": [
                {"name": "LoadPt", "value": 0, "display_name": "LoadPt"},
                {"name": "DumpPt", "value": 1, "display_name": "DumpPt"},
                {"name": "Parking", "value": 2, "display_name": "Parking"},
                {"name": "Boulder", "value": 3, "display_name": "Boulder"},
                {"name": "Workshop", "value": 4, "display_name": "Workshop"},
                {"name": "Others", "value": 5, "display_name": "Others"},
            ]
        },
    ),
]
_ORIGINAL_NODEIDS: tuple = (
    [
        ("ns=1;i=3003", "ns=1;i=5001", ["i=11", "i=887"]),
        ("ns=1;i=3004", "ns=1;i=5004", ["i=13", "i=290"]),
    ],
    ["ns=1;i=3009", "ns=1;i=3006", "ns=1;i=3018", "ns=1;i=3012", "ns=1;i=3015"],
)
_NODES: dict = {
    "datatypes": {
        "Answer": ("D", "ns=1;i=3009", {"EnumValues": ("V", "ns=1;i=6008", {})}),
        "AnyURI": ("D", "ns=1;i=3008", {}),
        "DispFlag": ("D", "ns=1;i=3006", {"EnumValues": ("V", "ns=1;i=6007", {})}),
        "IRLengthDataType": ("D", "ns=1;i=3003", {}),
        "IRVersion": ("D", "ns=1;i=3007", {}),
        "IRangle": ("D", "ns=1;i=3005", {}),
        "IRtext": ("D", "ns=1;i=3001", {}),
        "IRtextLong": ("D", "ns=1;i=3002", {}),
        "IRtextShort": ("D", "ns=1;i=3000", {}),
        "JobAssignmentTimeDataType": ("D", "ns=1;i=3004", {}),
        "LTPPMaction": ("D", "ns=1;i=3018", {"EnumValues": ("V", "ns=1;i=6011", {})}),
        "LTPPMptFromType": (
            "D",
            "ns=1;i=3012",
            {"EnumValues": ("V", "ns=1;i=6009", {})},
        ),
        "LTPPMptToType": ("D", "ns=1;i=3015", {"EnumValues": ("V", "ns=1;i=6010", {})}),
    },
    "objects": {
        "AckFlag": ("V", "ns=1;i=6030", {}),
        "Answer": ("V", "ns=1;i=6085", {}),
        "AssignmentTime": ("V", "ns=1;i=6099", {}),
        "BlastDelay": ("V", "ns=1;i=6158", {}),
        "CantDump": ("V", "ns=1;i=6159", {}),
        "ChkSum": ("V", "ns=1;i=6136", {}),
        "Comment": ("V", "ns=1;i=6016", {}),
        "Condition": ("V", "ns=1;i=6087", {}),
        "Default Binary": ("O", "ns=1;i=5004", {}),
        "Default JSON": ("O", "ns=1;i=5006", {}),
        "Default XML": ("O", "ns=1;i=5005", {}),
        "DefaultInstanceBrowseName": ("V", "ns=1;i=6035", {}),
        "DispFlag": ("V", "ns=1;i=6029", {}),
        "DispText": ("V", "ns=1;i=6031", {}),
        "DisplayToOperator": ("O", "ns=1;i=5009", {}),
        "DownCompat": ("V", "ns=1;i=6095", {}),
        "Duration": ("V", "ns=1;i=6086", {}),
        "EndLogTime": ("V", "ns=1;i=6081", {}),
        "EndLogTine": ("V", "ns=1;i=6065", {}),
        "EqpInfo": ("V", "ns=1;i=6023", {}),
        "EqpManufact": ("V", "ns=1;i=6263", {}),
        "EqpModel": ("V", "ns=1;i=6020", {}),
        "EqpName": ("V", "ns=1;i=6024", {}),
        "EqpSerNo": ("V", "ns=1;i=6021", {}),
        "EqpSysVer": ("V", "ns=1;i=6022", {}),
        "EqpType": ("V", "ns=1;i=6264", {}),
        "EquipmentInfo": ("O", "ns=1;i=5008", {}),
        "Extra": ("V", "ns=1;i=6088", {}),
        "FileCloseDate": ("V", "ns=1;i=6137", {}),
        "FileCreateDate": ("V", "ns=1;i=6096", {}),
        "GenHead": ("O", "ns=1;i=5023", {}),
        "GenTrailer": ("O", "ns=1;i=5051", {}),
        "IRDownwCompat": ("V", "ns=1;i=6094", {}),
        "IREDES": ("O", "ns=1;i=5077", {}),
        "IREDESType": ("O", "ns=1;i=5022", {}),
        "IRLTMMon": ("O", "ns=1;i=5072", {}),
        "IRLTPPerf": ("O", "ns=1;i=5062", {}),
        "IRLTPlan": ("O", "ns=1;i=5067", {}),
        "IRVersion": ("V", "ns=1;i=6098", {}),
        "IRpPerfGen": ("O", "ns=1;i=5058", {}),
        "IRpPerfGenType": ("O", "ns=1;i=5068", {}),
        "IRplanGen": ("O", "ns=1;i=5048", {}),
        "Issuer": ("V", "ns=1;i=6103", {}),
        "LTMMonDownwCompat": ("V", "ns=1;i=6139", {}),
        "LTMMonVersion": ("V", "ns=1;i=6138", {}),
        "LTPPCyclTot": ("V", "ns=1;i=6198", {}),
        "LTPPEndTime": ("V", "ns=1;i=6167", {}),
        "LTPPLcycl": ("V", "ns=1;i=6202", {}),
        "LTPPLdist": ("V", "ns=1;i=6273", {}),
        "LTPPLdrawPtID": ("V", "ns=1;i=6189", {}),
        "LTPPLdrawPtN": ("V", "ns=1;i=6203", {}),
        "LTPPLdumpPtID": ("V", "ns=1;i=6191", {}),
        "LTPPLdumpPtN": ("V", "ns=1;i=6204", {}),
        "LTPPLmass": ("V", "ns=1;i=6205", {}),
        "LTPPLoadRep": ("O", "ns=1;i=5061", {}),
        "LTPPLoadRepType": ("O", "ns=1;i=5071", {}),
        "LTPPLopObserv": ("V", "ns=1;i=6000", {}),
        "LTPPMaction": ("V", "ns=1;i=6180", {}),
        "LTPPMarea": ("V", "ns=1;i=6176", {}),
        "LTPPMisSeq": ("V", "ns=1;i=6169", {}),
        "LTPPMissEnd": ("V", "ns=1;i=6178", {}),
        "LTPPMission": ("O", "ns=1;i=5057", {}),
        "LTPPMisstart": ("V", "ns=1;i=6177", {}),
        "LTPPMopID": ("V", "ns=1;i=6186", {}),
        "LTPPMpayld": ("V", "ns=1;i=6183", {}),
        "LTPPMptFromID": ("V", "ns=1;i=6172", {}),
        "LTPPMptFromN": ("V", "ns=1;i=6170", {}),
        "LTPPMptFromType": ("V", "ns=1;i=6171", {}),
        "LTPPMptToID": ("V", "ns=1;i=6174", {}),
        "LTPPMptToN": ("V", "ns=1;i=6173", {}),
        "LTPPMptToType": ("V", "ns=1;i=6175", {}),
        "LTPPMtimeAct": ("V", "ns=1;i=6182", {}),
        "LTPPMtramDist": ("V", "ns=1;i=6185", {}),
        "LTPPMtramEnd": ("V", "ns=1;i=6184", {}),
        "LTPPMwaitPoint": ("V", "ns=1;i=6179", {}),
        "LTPPMwaitgen": ("V", "ns=1;i=6181", {}),
        "LTPPStartTime": ("V", "ns=1;i=6166", {}),
        "LTPPTimeRep": ("O", "ns=1;i=5054", {}),
        "LTPPaccPts": ("O", "ns=1;i=5056", {}),
        "LTPPdistTot": ("V", "ns=1;i=6199", {}),
        "LTPPerfDownwCompat": ("V", "ns=1;i=6221", {}),
        "LTPPerfVersion": ("V", "ns=1;i=6220", {}),
        "LTPPloadTot": ("V", "ns=1;i=6201", {}),
        "LTPPwaitProc": ("O", "ns=1;i=5055", {}),
        "LTPPwrkDist": ("V", "ns=1;i=6200", {}),
        "LTPlanDownwCompat": ("V", "ns=1;i=6156", {}),
        "LTPlanVersion": ("V", "ns=1;i=6155", {}),
        "MachineId": ("V", "ns=1;i=6104", {}),
        "MineUtils": ("V", "ns=1;i=6162", {}),
        "Mworking": ("V", "ns=1;i=6046", {}),
        "NoRock": ("V", "ns=1;i=6161", {}),
        "OpPerfLog": ("O", "ns=1;i=5017", {}),
        "OperatorId": ("V", "ns=1;i=6105", {}),
        "OptionSchema": ("V", "ns=1;i=6034", {}),
        "PlanId": ("V", "ns=1;i=6074", {}),
        "PlanName": ("V", "ns=1;i=6073", {}),
        "PriorityLevel": ("V", "ns=1;i=6101", {}),
        "Project": ("V", "ns=1;i=6076", {}),
        "ProjectInfo": ("O", "ns=1;i=5007", {}),
        "Reason": ("V", "ns=1;i=6089", {}),
        "Reply": ("O", "ns=1;i=5041", {}),
        "Reply1": ("O", "ns=1;i=5024", {}),
        "Reply10": ("O", "ns=1;i=5042", {}),
        "Reply2": ("O", "ns=1;i=5026", {}),
        "Reply3": ("O", "ns=1;i=5028", {}),
        "Reply4": ("O", "ns=1;i=5030", {}),
        "Reply5": ("O", "ns=1;i=5032", {}),
        "Reply6": ("O", "ns=1;i=5034", {}),
        "Reply7": ("O", "ns=1;i=5036", {}),
        "Reply8": ("O", "ns=1;i=5038", {}),
        "Reply9": ("O", "ns=1;i=5040", {}),
        "ReportId": ("V", "ns=1;i=6079", {}),
        "RoadMaint": ("V", "ns=1;i=6164", {}),
        "SafetyAdvice": ("V", "ns=1;i=6106", {}),
        "Signature": ("V", "ns=1;i=6015", {}),
        "SiteHead": ("O", "ns=1;i=5012", {}),
        "SiteOption": ("O", "ns=1;i=5010", {}),
        "SpecialCondition": ("V", "ns=1;i=6107", {}),
        "SpecialTask": ("V", "ns=1;i=6108", {}),
        "StartLogTime": ("V", "ns=1;i=6080", {}),
        "Traffic": ("V", "ns=1;i=6160", {}),
        "TurnedOff": ("V", "ns=1;i=6051", {}),
        "WaitOperator": ("V", "ns=1;i=6048", {}),
        "WaitProcess": ("V", "ns=1;i=6047", {}),
        "WaitRepair": ("V", "ns=1;i=6049", {}),
        "WaitSamples": ("V", "ns=1;i=6050", {}),
        "WorkOrder": ("V", "ns=1;i=6077", {}),
        "WorkOrderContent": ("O", "ns=1;i=5044", {}),
        "WorkOrderId": ("V", "ns=1;i=6102", {}),
        "WorkOrderType": ("V", "ns=1;i=6100", {}),
        "http://opcfoundation.org/UA/Mining/ExternalStandards/IREDES": (
            "O",
            "ns=1;i=5076",
            {
                "IsNamespaceSubset": ("V", "ns=1;i=6256", {}),
                "NamespacePublicationDate": ("V", "ns=1;i=6257", {}),
                "NamespaceUri": ("V", "ns=1;i=6258", {}),
                "NamespaceVersion": ("V", "ns=1;i=6259", {}),
                "StaticNodeIdTypes": ("V", "ns=1;i=6260", {}),
                "StaticNumericNodeIdRange": ("V", "ns=1;i=6261", {}),
                "StaticStringNodeIdPattern": ("V", "ns=1;i=6262", {}),
            },
        ),
    },
    "objtypes": {
        "DisplayToOperatorType": ("OT", "ns=1;i=1004", {}),
        "EquipmentInfoType": ("OT", "ns=1;i=1006", {}),
        "GenHeadType": ("OT", "ns=1;i=1009", {}),
        "GenTrailerType": ("OT", "ns=1;i=1015", {}),
        "IREDESType": ("OT", "ns=1;i=1005", {}),
        "IRLHDTruckType": ("OT", "ns=1;i=1030", {}),
        "IRLTMMonType": ("OT", "ns=1;i=1011", {}),
        "IRLTPPerfType": ("OT", "ns=1;i=1026", {}),
        "IRLTPlanType": ("OT", "ns=1;i=1014", {}),
        "IROptionType": ("OT", "ns=1;i=1008", {}),
        "IRStatusGenType": ("OT", "ns=1;i=1020", {}),
        "IRWorkOrderGenType": ("OT", "ns=1;i=1021", {}),
        "IRWorkOrderReplyGenType": ("OT", "ns=1;i=1010", {}),
        "IRpPerfGenType": ("OT", "ns=1;i=1013", {}),
        "IRplanGenType": ("OT", "ns=1;i=1017", {}),
        "IRreplyType": ("OT", "ns=1;i=1016", {}),
        "LTPPLoadRepType": ("OT", "ns=1;i=1019", {}),
        "LTPPMissionType": ("OT", "ns=1;i=1028", {}),
        "LTPPTimeRepType": ("OT", "ns=1;i=1025", {}),
        "LTPPaccPtsType": ("OT", "ns=1;i=1018", {}),
        "LTPPwaitProcType": ("OT", "ns=1;i=1022", {}),
        "OpPerfLogType": ("OT", "ns=1;i=1007", {}),
        "ProjectInfoType": ("OT", "ns=1;i=1003", {}),
        "SiteHeadType": ("OT", "ns=1;i=1012", {}),
    },
}
