# AUTO-GENERATED — DO NOT EDIT
# source-sha256: 4f4acb7bb3f4bf0569335e9a0b8cdb5ac02bea1d7c0488a2131f955845458c36
# Run tools/update_ns.py to regenerate.
from __future__ import annotations

_URI: str = "http://www.OPCFoundation.org/UA/2013/01/ISA95"
_VERSION: str = "1.00"
_REQUIRED: list = [{"uri": "http://opcfoundation.org/UA/", "version": ""}]
_STRUCTURES: list = [
    (
        "ns=1;i=4776",
        "CurrencyCode",
        "ns=1;i=4788",
        {
            "structure_type": 0,
            "fields": [
                {"name": "namespaceUri", "data_type": "i=12", "value_rank": -1},
                {"name": "unitId", "data_type": "i=6", "value_rank": -1},
                {"name": "charId", "data_type": "i=3", "value_rank": 1},
                {"name": "displayName", "data_type": "i=21", "value_rank": -1},
                {"name": "Description", "data_type": "i=21", "value_rank": -1},
            ],
        },
    ),
    (
        "ns=1;i=4862",
        "ISA95TestResultMeasurementDataType",
        "ns=1;i=4867",
        {
            "structure_type": 0,
            "fields": [
                {"name": "Id", "data_type": "i=17", "value_rank": -1},
                {
                    "name": "TestResultDescription",
                    "data_type": "i=21",
                    "value_rank": -1,
                },
                {"name": "Date", "data_type": "i=13", "value_rank": -1},
                {"name": "Result", "data_type": "i=24", "value_rank": -1},
                {"name": "ResultUnitOfMeasure", "data_type": "i=887", "value_rank": -1},
                {"name": "Expiration", "data_type": "i=13", "value_rank": -1},
            ],
        },
    ),
    (
        "ns=1;i=4873",
        "ISA95TestResultDataType",
        "ns=1;i=4902",
        {
            "structure_type": 0,
            "fields": [
                {"name": "Id", "data_type": "i=17", "value_rank": -1},
                {
                    "name": "TestResultDescription",
                    "data_type": "i=21",
                    "value_rank": -1,
                },
                {"name": "Date", "data_type": "i=13", "value_rank": -1},
                {"name": "Result", "data_type": "i=24", "value_rank": -1},
                {"name": "ResultUnitOfMeasure", "data_type": "i=12", "value_rank": -1},
                {"name": "Expiration", "data_type": "i=13", "value_rank": -1},
            ],
        },
    ),
    (
        "ns=1;i=4956",
        "ISA95AssetAssignmentDataType",
        "ns=1;i=4973",
        {
            "structure_type": 0,
            "fields": [
                {"name": "Id", "data_type": "i=17", "value_rank": -1},
                {"name": "AssinmentDescription", "data_type": "i=21", "value_rank": -1},
                {"name": "StartTime", "data_type": "i=13", "value_rank": -1},
                {"name": "EndTime", "data_type": "i=13", "value_rank": -1},
            ],
        },
    ),
]
_ENUMS: list = [
    (
        "ns=1;i=4871",
        "ISA95EquipmentElementLevelEnum",
        {
            "fields": [
                {"name": "Enterprise", "value": 0, "display_name": "Enterprise"},
                {"name": "Site", "value": 1, "display_name": "Site"},
                {"name": "Area", "value": 2, "display_name": "Area"},
                {"name": "ProcessCell", "value": 3, "display_name": "ProcessCell"},
                {"name": "Unit", "value": 4, "display_name": "Unit"},
                {
                    "name": "ProductionLine",
                    "value": 5,
                    "display_name": "ProductionLine",
                },
                {"name": "WorkCell", "value": 6, "display_name": "WorkCell"},
                {
                    "name": "ProductionUnit",
                    "value": 7,
                    "display_name": "ProductionUnit",
                },
                {"name": "StorageZone", "value": 8, "display_name": "StorageZone"},
                {"name": "StorageUnit", "value": 9, "display_name": "StorageUnit"},
                {"name": "WorkCenter", "value": 10, "display_name": "WorkCenter"},
                {"name": "WorkUnit", "value": 11, "display_name": "WorkUnit"},
                {
                    "name": "EquipmentModule",
                    "value": 12,
                    "display_name": "EquipmentModule",
                },
                {"name": "ControlModule", "value": 13, "display_name": "ControlModule"},
                {"name": "Other", "value": 14, "display_name": "Other"},
            ]
        },
    )
]
_ORIGINAL_NODEIDS: tuple = (
    [
        ("ns=1;i=4776", "ns=1;i=4788", ["i=12", "i=6", "i=3", "i=21", "i=21"]),
        (
            "ns=1;i=4862",
            "ns=1;i=4867",
            ["i=17", "i=21", "i=13", "i=24", "i=887", "i=13"],
        ),
        (
            "ns=1;i=4873",
            "ns=1;i=4902",
            ["i=17", "i=21", "i=13", "i=24", "i=12", "i=13"],
        ),
        ("ns=1;i=4956", "ns=1;i=4973", ["i=17", "i=21", "i=13", "i=13"]),
    ],
    ["ns=1;i=4871"],
)
_NODES: dict = {
    "datatypes": {
        "CDTBinaryObject": ("D", "ns=1;i=4798", {}),
        "CDTCode": ("D", "ns=1;i=4792", {}),
        "CDTDateTime": ("D", "ns=1;i=4803", {}),
        "CDTGraphic": ("D", "ns=1;i=4806", {}),
        "CDTIdentifier": ("D", "ns=1;i=4777", {}),
        "CDTMeasureDouble": ("D", "ns=1;i=4811", {}),
        "CDTMeasureFloat": ("D", "ns=1;i=4813", {}),
        "CDTMeasureInt16": ("D", "ns=1;i=4815", {}),
        "CDTMeasureInt32": ("D", "ns=1;i=4817", {}),
        "CDTMeasureInt64": ("D", "ns=1;i=4819", {}),
        "CDTOrdinal": ("D", "ns=1;i=4821", {}),
        "CDTPicture": ("D", "ns=1;i=4822", {}),
        "CDTRateDouble": ("D", "ns=1;i=4832", {}),
        "CDTRateFloat": ("D", "ns=1;i=4839", {}),
        "CDTRateInt32": ("D", "ns=1;i=4846", {}),
        "CDTSound": ("D", "ns=1;i=4853", {}),
        "CDTVideo": ("D", "ns=1;i=4856", {}),
        "CurrencyCode": ("D", "ns=1;i=4776", {}),
        "DateString": ("D", "ns=1;i=4773", {}),
        "Decimal": (
            "D",
            "ns=1;i=927",
            {
                "CDTAmountDecimal": ("D", "ns=1;i=4796", {}),
                "CDTMeasureDecimal": ("D", "ns=1;i=4809", {}),
                "CDTRateDecimal": ("D", "ns=1;i=4825", {}),
            },
        ),
        "DecimalString": ("D", "ns=1;i=4772", {}),
        "DurationString": ("D", "ns=1;i=4775", {}),
        "ISA95AssetAssignmentDataType": ("D", "ns=1;i=4956", {}),
        "ISA95EquipmentElementLevelEnum": (
            "D",
            "ns=1;i=4871",
            {"EnumStrings": ("V", "ns=1;i=4872", {})},
        ),
        "ISA95TestResultDataType": ("D", "ns=1;i=4873", {}),
        "ISA95TestResultMeasurementDataType": ("D", "ns=1;i=4862", {}),
        "NormalizedString": ("D", "ns=1;i=4929", {}),
        "TimeString": ("D", "ns=1;i=4774", {}),
    },
    "objects": {
        "<AssemblyClass>": ("O", "ns=1;i=5227", {}),
        "<AssemblyLot>": ("O", "ns=1;i=5269", {}),
        "<AssemblySublot>": ("O", "ns=1;i=5278", {}),
        "<Equipment>": (
            "O",
            "ns=1;i=5144",
            {"AssetAssignment": ("V", "ns=1;i=5318", {})},
        ),
        "<EquipmentClass>": ("O", "ns=1;i=5043", {}),
        "<MaterialClass>": ("O", "ns=1;i=5224", {}),
        "<MaterialDefinition>": ("O", "ns=1;i=5246", {}),
        "<PersonnelClass>": ("O", "ns=1;i=5302", {}),
        "<PhysicalAsset>": ("O", "ns=1;i=5093", {}),
        "<PropertyName>": ("V", "ns=1;i=5260", {}),
        "<Sublot>": ("O", "ns=1;i=5286", {}),
        "<TestResult>": ("V", "ns=1;i=5193", {}),
        "<TestSpecification>": ("O", "ns=1;i=5267", {}),
        "AssemblyRelationship": ("V", "ns=1;i=5288", {}),
        "AssemblyType": ("V", "ns=1;i=5287", {}),
        "AssignmentDescription": ("V", "ns=1;i=5330", {}),
        "BaseCurrency": ("V", "ns=1;i=4852", {}),
        "BaseMultiplier": ("V", "ns=1;i=4850", {}),
        "BaseUnit": ("V", "ns=1;i=4851", {}),
        "CharacterSet": ("V", "ns=1;i=4800", {}),
        "CharacterSetListAgencyId": ("V", "ns=1;i=4935", {}),
        "CharacterSetListId": ("V", "ns=1;i=4934", {}),
        "CharacterSetListVersionId": ("V", "ns=1;i=4936", {}),
        "Currency": ("V", "ns=1;i=4849", {}),
        "DaylightSavings": ("V", "ns=1;i=4805", {}),
        "Default Binary": ("O", "ns=1;i=4973", {}),
        "Default XML": ("O", "ns=1;i=4969", {}),
        "Encoding": ("V", "ns=1;i=4801", {}),
        "EncodingListAgencyId": ("V", "ns=1;i=4938", {}),
        "EncodingListId": ("V", "ns=1;i=4937", {}),
        "EncodingListVersionId": ("V", "ns=1;i=4939", {}),
        "EquipmentLevel": ("V", "ns=1;i=5047", {}),
        "Expiration": ("V", "ns=1;i=5266", {}),
        "FileName": ("V", "ns=1;i=4858", {}),
        "FixedAssetId": ("V", "ns=1;i=5153", {}),
        "Id": ("V", "ns=1;i=5261", {}),
        "Key": ("V", "ns=1;i=4887", {}),
        "ListAgencyId": ("V", "ns=1;i=4794", {}),
        "ListId": ("V", "ns=1;i=4793", {}),
        "ListVersionId": ("V", "ns=1;i=4795", {}),
        "MIMEListAgencyId": ("V", "ns=1;i=4954", {}),
        "MIMEListId": ("V", "ns=1;i=4953", {}),
        "MIMEListVersionId": ("V", "ns=1;i=4955", {}),
        "Manufacturer": ("V", "ns=1;i=5083", {}),
        "MimeContentType": ("V", "ns=1;i=4952", {}),
        "ModelNumber": ("V", "ns=1;i=5084", {}),
        "Multiplier": ("V", "ns=1;i=4847", {}),
        "Opc.ISA95": (
            "V",
            "ns=1;i=4765",
            {
                "CurrencyCode": ("V", "ns=1;i=4789", {}),
                "ISA95AssetAssignmentDataType": ("V", "ns=1;i=4974", {}),
                "ISA95TestResultDataType": ("V", "ns=1;i=4904", {}),
                "ISA95TestResultMeasurementDataType": ("V", "ns=1;i=4868", {}),
                "NamespaceUri": ("V", "ns=1;i=4767", {}),
            },
        ),
        "PhysicalAssetClass": ("O", "ns=1;i=5088", {}),
        "PhysicalLocation": ("V", "ns=1;i=5138", {}),
        "Quantity": ("V", "ns=1;i=5294", {}),
        "Result": ("V", "ns=1;i=5264", {}),
        "ResultDescription": ("V", "ns=1;i=5262", {}),
        "ResultUnitOfMeasure": ("V", "ns=1;i=5265", {}),
        "SchemeAgencyId": ("V", "ns=1;i=4780", {}),
        "SchemeId": ("V", "ns=1;i=4778", {}),
        "SchemeVersionId": ("V", "ns=1;i=4779", {}),
        "StartTime": ("V", "ns=1;i=5331", {}),
        "Status": ("V", "ns=1;i=5292", {}),
        "StopTime": ("V", "ns=1;i=5332", {}),
        "StorageLocation": ("V", "ns=1;i=5293", {}),
        "TestDate": ("V", "ns=1;i=5263", {}),
        "Timezone": ("V", "ns=1;i=4804", {}),
        "Unit": ("V", "ns=1;i=4848", {}),
        "VendorId": ("V", "ns=1;i=5154", {}),
        "Version": ("V", "ns=1;i=5268", {}),
    },
    "objtypes": {
        "ISA95ClassType": (
            "OT",
            "ns=1;i=4957",
            {
                "EquipmentClassType": ("OT", "ns=1;i=5034", {}),
                "MaterialClassType": ("OT", "ns=1;i=5209", {}),
                "MaterialDefinitionType": ("OT", "ns=1;i=5219", {}),
                "PersonnelClassType": ("OT", "ns=1;i=4996", {}),
                "PhysicalAssetClassType": ("OT", "ns=1;i=5078", {}),
            },
        ),
        "ISA95ObjectType": (
            "OT",
            "ns=1;i=4958",
            {
                "EquipmentType": (
                    "OT",
                    "ns=1;i=5040",
                    {"AssetAssignment": ("V", "ns=1;i=5328", {})},
                ),
                "MaterialLotType": ("OT", "ns=1;i=5232", {}),
                "MaterialSublotType": ("OT", "ns=1;i=5259", {}),
                "PersonType": ("OT", "ns=1;i=5131", {}),
                "PhysicalAssetType": (
                    "OT",
                    "ns=1;i=5085",
                    {"AssetAssignment": ("V", "ns=1;i=5308", {})},
                ),
            },
        ),
        "ISA95TestSpecificationType": (
            "OT",
            "ns=1;i=4959",
            {
                "EquipmentCapabilityTestSpecificationType": ("OT", "ns=1;i=5015", {}),
                "MaterialTestSpecificationType": ("OT", "ns=1;i=5172", {}),
                "PhysicalAssetCapabilityTestSpecificationType": (
                    "OT",
                    "ns=1;i=5057",
                    {},
                ),
                "QualificationTestSpecificationType": ("OT", "ns=1;i=4977", {}),
            },
        ),
    },
    "reftypes": {
        "AssembledFrom": (
            "RT",
            "ns=1;i=4925",
            {
                "AssembledFromClass": ("RT", "ns=1;i=4927", {}),
                "AssembledFromDefinition": ("RT", "ns=1;i=4926", {}),
                "AssembledFromLot": ("RT", "ns=1;i=4928", {}),
            },
        ),
        "DefinedBy": (
            "RT",
            "ns=1;i=4912",
            {
                "DefinedByEquipmentClass": ("RT", "ns=1;i=4919", {}),
                "DefinedByMaterialDefinition": ("RT", "ns=1;i=5301", {}),
                "DefinedByPersonnelClass": ("RT", "ns=1;i=4917", {}),
                "DefinedByPhysicalAssetClass": ("RT", "ns=1;i=4921", {}),
            },
        ),
        "HasCDTSupplemental": ("RT", "ns=1;i=4911", {}),
        "HasISA95Attribute": ("RT", "ns=1;i=4713", {}),
        "HasISA95ClassProperty": ("RT", "ns=1;i=4910", {}),
        "HasISA95Property": ("RT", "ns=1;i=2009", {}),
        "HasTestResult": ("RT", "ns=1;i=4915", {}),
        "ImplementedBy": ("RT", "ns=1;i=4914", {}),
        "LocatedIn": ("RT", "ns=1;i=5114", {}),
        "MadeUpOf": (
            "RT",
            "ns=1;i=4714",
            {
                "MadeUpOfEquipment": ("RT", "ns=1;i=5115", {}),
                "MadeUpOfMaterialSublot": ("RT", "ns=1;i=5117", {}),
                "MadeUpOfPhysicalAsset": ("RT", "ns=1;i=5116", {}),
            },
        ),
        "ResultsForSpecification": ("RT", "ns=1;i=4916", {}),
        "TestedBy": (
            "RT",
            "ns=1;i=4913",
            {
                "TestedByEquipmentTest": ("RT", "ns=1;i=4920", {}),
                "TestedByMaterialTest": ("RT", "ns=1;i=4924", {}),
                "TestedByPhysicalAssetTest": ("RT", "ns=1;i=4922", {}),
                "TestedByQualificationTest": ("RT", "ns=1;i=4918", {}),
            },
        ),
    },
    "vartypes": {
        "CompanyType": ("VT", "ns=1;i=5049", {}),
        "GeoSpatialLocationType": ("VT", "ns=1;i=5048", {}),
        "ISA95AssetAssignmentType": ("VT", "ns=1;i=5108", {}),
        "ISA95ClassPropertyType": (
            "VT",
            "ns=1;i=4885",
            {
                "EquipmentClassPropertyType": ("VT", "ns=1;i=5017", {}),
                "MaterialClassPropertyType": ("VT", "ns=1;i=5180", {}),
                "MaterialDefinitionPropertyType": ("VT", "ns=1;i=5174", {}),
                "PersonnelClassPropertyType": ("VT", "ns=1;i=1123", {}),
                "PhysicalAssetClassPropertyType": ("VT", "ns=1;i=5059", {}),
                "PhysicalAssetPropertyType": ("VT", "ns=1;i=5065", {}),
            },
        ),
        "ISA95PropertyType": (
            "VT",
            "ns=1;i=4263",
            {
                "EquipmentPropertyType": ("VT", "ns=1;i=954", {}),
                "PersonPropertyType": ("VT", "ns=1;i=5118", {}),
            },
        ),
        "ISA95TestResultType": (
            "VT",
            "ns=1;i=4878",
            {
                "EquipmentCapabilityTestResultType": ("VT", "ns=1;i=5008", {}),
                "ISA95TestResultEUType": ("VT", "ns=1;i=5101", {}),
                "ISA95TestResultNonEUType": ("VT", "ns=1;i=5094", {}),
                "MaterialTestResultType": (
                    "VT",
                    "ns=1;i=5165",
                    {"MaterialLotPropertyType": ("VT", "ns=1;i=5186", {})},
                ),
                "PhysicalAssetCapabilityTestResultType": ("VT", "ns=1;i=5050", {}),
                "QualificationTestResultType": ("VT", "ns=1;i=4961", {}),
            },
        ),
    },
}
