# AUTO-GENERATED — DO NOT EDIT
# source-sha256: 487243c1ec85e0b747c087ed96c0e1d824629789055e74854f07d19099c08803
# Run tools/update_ns.py to regenerate.
from __future__ import annotations

_URI: str = "http://opcfoundation.org/UA/Robotics/"
_VERSION: str = "1.02"
_REQUIRED: list = [
    {"uri": "http://opcfoundation.org/UA/", "version": "1.05.03"},
    {"uri": "http://opcfoundation.org/UA/DI/", "version": "1.04.0"},
    {"uri": "http://opcfoundation.org/UA/IA/", "version": "1.01.4"},
]
_STRUCTURES: list = []
_ENUMS: list = [
    (
        "ns=3;i=3008",
        "AxisMotionProfileEnumeration",
        {
            "fields": [
                {"name": "OTHER", "value": 0, "display_name": "OTHER"},
                {"name": "ROTARY", "value": 1, "display_name": "ROTARY"},
                {
                    "name": "ROTARY_ENDLESS",
                    "value": 2,
                    "display_name": "ROTARY_ENDLESS",
                },
                {"name": "LINEAR", "value": 3, "display_name": "LINEAR"},
                {
                    "name": "LINEAR_ENDLESS",
                    "value": 4,
                    "display_name": "LINEAR_ENDLESS",
                },
            ]
        },
    ),
    (
        "ns=3;i=18191",
        "ExecutionModeEnumeration",
        {
            "fields": [
                {"name": "CYCLE", "value": 0, "display_name": "CYCLE"},
                {"name": "CONTINUOUS", "value": 1, "display_name": "CONTINUOUS"},
                {"name": "STEP", "value": 2, "display_name": "STEP"},
            ]
        },
    ),
    (
        "ns=3;i=18193",
        "MotionDeviceCategoryEnumeration",
        {
            "fields": [
                {"name": "OTHER", "value": 0, "display_name": "OTHER"},
                {
                    "name": "ARTICULATED_ROBOT",
                    "value": 1,
                    "display_name": "ARTICULATED_ROBOT",
                },
                {"name": "SCARA_ROBOT", "value": 2, "display_name": "SCARA_ROBOT"},
                {
                    "name": "CARTESIAN_ROBOT",
                    "value": 3,
                    "display_name": "CARTESIAN_ROBOT",
                },
                {
                    "name": "SPHERICAL_ROBOT",
                    "value": 4,
                    "display_name": "SPHERICAL_ROBOT",
                },
                {
                    "name": "PARALLEL_ROBOT",
                    "value": 5,
                    "display_name": "PARALLEL_ROBOT",
                },
                {
                    "name": "CYLINDRICAL_ROBOT",
                    "value": 6,
                    "display_name": "CYLINDRICAL_ROBOT",
                },
            ]
        },
    ),
    (
        "ns=3;i=3006",
        "OperationalModeEnumeration",
        {
            "fields": [
                {"name": "OTHER", "value": 0, "display_name": "OTHER"},
                {
                    "name": "MANUAL_REDUCED_SPEED",
                    "value": 1,
                    "display_name": "MANUAL_REDUCED_SPEED",
                },
                {
                    "name": "MANUAL_HIGH_SPEED",
                    "value": 2,
                    "display_name": "MANUAL_HIGH_SPEED",
                },
                {"name": "AUTOMATIC", "value": 3, "display_name": "AUTOMATIC"},
                {
                    "name": "AUTOMATIC_EXTERNAL",
                    "value": 4,
                    "display_name": "AUTOMATIC_EXTERNAL",
                },
            ]
        },
    ),
]
_ORIGINAL_NODEIDS: tuple = (
    [],
    ["ns=3;i=3008", "ns=3;i=18191", "ns=3;i=18193", "ns=3;i=3006"],
)
_NODES: dict = {
    "datatypes": {
        "AxisMotionProfileEnumeration": (
            "D",
            "ns=3;i=3008",
            {"EnumStrings": ("V", "ns=3;i=6027", {})},
        ),
        "ExecutionModeEnumeration": (
            "D",
            "ns=3;i=18191",
            {"EnumStrings": ("V", "ns=3;i=18192", {})},
        ),
        "MotionDeviceCategoryEnumeration": (
            "D",
            "ns=3;i=18193",
            {"EnumStrings": ("V", "ns=3;i=18194", {})},
        ),
        "OperationalModeEnumeration": (
            "D",
            "ns=3;i=3006",
            {"EnumStrings": ("V", "ns=3;i=6022", {})},
        ),
    },
    "objects": {
        "<AcknowledgeableCondition>": ("O", "ns=3;i=5059", {}),
        "<AdditionalComponentIdentifier>": ("O", "ns=3;i=5003", {}),
        "<AxisIdentifier>": ("O", "ns=3;i=18536", {}),
        "<ComponentIdentifier>": ("O", "ns=3;i=18813", {}),
        "<ControllerIdentifier>": ("O", "ns=3;i=15405", {}),
        "<DriveIdentifier>": ("O", "ns=3;i=5060", {}),
        "<EmergencyStopFunctionIdentifier>": ("O", "ns=3;i=18806", {}),
        "<GearIdentifier>": ("O", "ns=3;i=16041", {}),
        "<MotionDeviceIdentifier>": ("O", "ns=3;i=19254", {}),
        "<MotorIdentifier>": ("O", "ns=3;i=15998", {}),
        "<PowerTrainIdentifier>": ("O", "ns=3;i=18613", {}),
        "<ProtectiveStopFunctionIdentifier>": ("O", "ns=3;i=18809", {}),
        "<SafetyStateIdentifier>": ("O", "ns=3;i=15697", {}),
        "<SafetyStatesIdentifier>": ("O", "ns=3;i=18918", {}),
        "<SoftwareIdentifier>": ("O", "ns=3;i=18847", {}),
        "<TaskControlIdentifier>": ("O", "ns=3;i=18881", {}),
        "<TaskModule>": ("O", "ns=3;i=5058", {}),
        "A": ("V", "ns=3;i=16137", {}),
        "AckedState": ("V", "ns=3;i=6185", {}),
        "Acknowledge": ("M", "ns=3;i=7019", {}),
        "Active": ("V", "ns=3;i=18812", {}),
        "ActualAcceleration": ("V", "ns=3;i=16674", {}),
        "ActualPosition": ("V", "ns=3;i=18595", {}),
        "ActualSpeed": ("V", "ns=3;i=16668", {}),
        "AddComment": ("M", "ns=3;i=7020", {}),
        "AdditionalComponents": ("O", "ns=3;i=16566", {}),
        "AdditionalLoad": ("O", "ns=3;i=16638", {}),
        "AssetId": ("V", "ns=3;i=6177", {}),
        "AtProgramStart": ("O", "ns=3;i=5023", {}),
        "Axes": ("O", "ns=3;i=19292", {}),
        "B": ("V", "ns=3;i=16138", {}),
        "BrakeReleased": ("V", "ns=3;i=17150", {}),
        "BranchId": ("V", "ns=3;i=6191", {}),
        "C": ("V", "ns=3;i=16139", {}),
        "CPUFanSpeed": ("V", "ns=3;i=17371", {}),
        "CabinetFanSpeed": ("V", "ns=3;i=17365", {}),
        "CartesianCoordinates": ("V", "ns=3;i=16130", {}),
        "CenterOfMass": ("V", "ns=3;i=6013", {}),
        "ClientUserId": ("V", "ns=3;i=6192", {}),
        "Comment": ("V", "ns=3;i=6193", {}),
        "ComponentName": ("V", "ns=3;i=17873", {}),
        "Components": ("O", "ns=3;i=17252", {}),
        "ConditionClassId": ("V", "ns=3;i=6195", {}),
        "ConditionClassName": ("V", "ns=3;i=6196", {}),
        "ConditionDescriptions": ("V", "ns=3;i=6140", {}),
        "ConditionName": ("V", "ns=3;i=6197", {}),
        "ConditionSubClassId": ("V", "ns=3;i=6198", {}),
        "ConditionSubClassName": ("V", "ns=3;i=6199", {}),
        "Conditions": ("O", "ns=3;i=5050", {}),
        "ConfiguredDefaultStopMode": ("V", "ns=3;i=6094", {}),
        "Controllers": ("O", "ns=3;i=5001", {}),
        "CreateDirectory": ("M", "ns=3;i=7015", {}),
        "CreateFile": ("M", "ns=3;i=7016", {}),
        "CurrentState": ("V", "ns=3;i=6148", {}),
        "CurrentUser": ("O", "ns=3;i=15440", {}),
        "DefaultInstanceBrowseName": ("V", "ns=3;i=6132", {}),
        "Delete": ("M", "ns=3;i=7017", {}),
        "Denominator": ("V", "ns=3;i=16078", {}),
        "DeviceManual": ("V", "ns=3;i=6174", {}),
        "Disable": ("M", "ns=3;i=7021", {}),
        "EffectiveLoadRate": ("V", "ns=3;i=6776", {}),
        "EmergencyStop": ("V", "ns=3;i=15882", {}),
        "EmergencyStopFunctions": ("O", "ns=3;i=17221", {}),
        "Enable": ("M", "ns=3;i=7022", {}),
        "Enabled": ("V", "ns=3;i=18811", {}),
        "EnabledState": ("V", "ns=3;i=6188", {}),
        "EngineeringUnits": ("V", "ns=3;i=16039", {}),
        "EnumValues": ("V", "ns=3;i=6153", {}),
        "EventId": ("V", "ns=3;i=6205", {}),
        "EventType": ("V", "ns=3;i=6206", {}),
        "Executing": ("O", "ns=3;i=5042", {}),
        "ExecutingSubstateMachine": ("O", "ns=3;i=5028", {}),
        "ExecutingToIdle": ("O", "ns=3;i=5048", {}),
        "ExecutingToReady": ("O", "ns=3;i=5047", {}),
        "ExecutionMode": ("V", "ns=3;i=17876", {}),
        "FlangeLoad": ("O", "ns=3;i=5091", {}),
        "GearRatio": ("V", "ns=3;i=16076", {}),
        "GetReady": ("M", "ns=3;i=7006", {}),
        "GettingReady": ("O", "ns=3;i=5017", {}),
        "GettingReadyToStandBy": ("O", "ns=3;i=5018", {}),
        "Id": ("V", "ns=3;i=6151", {}),
        "Idle": ("O", "ns=3;i=5040", {}),
        "IdleSubstateMachine": ("O", "ns=3;i=5027", {}),
        "IdleToIdle": ("O", "ns=3;i=5043", {}),
        "IdleToReady": ("O", "ns=3;i=5044", {}),
        "InControl": ("V", "ns=3;i=16364", {}),
        "Inertia": ("V", "ns=3;i=18170", {}),
        "InputArguments": ("V", "ns=3;i=6160", {}),
        "InputVoltage": ("V", "ns=3;i=17377", {}),
        "IsReferenced": ("V", "ns=3;i=6056", {}),
        "LastSeverity": ("V", "ns=3;i=6200", {}),
        "LastTransition": ("V", "ns=3;i=6150", {}),
        "LastTransitionReason": ("V", "ns=3;i=6152", {}),
        "Level": ("V", "ns=3;i=18176", {}),
        "LoadByName": ("M", "ns=3;i=7011", {}),
        "LoadByNodeId": ("M", "ns=3;i=7010", {}),
        "Manufacturer": ("V", "ns=3;i=19275", {}),
        "Mass": ("V", "ns=3;i=6624", {}),
        "Message": ("V", "ns=3;i=6207", {}),
        "Model": ("V", "ns=3;i=19277", {}),
        "MotionDeviceCategory": ("V", "ns=3;i=19288", {}),
        "MotionDevices": ("O", "ns=3;i=5002", {}),
        "MotionDevicesUnderControl": ("V", "ns=3;i=6131", {}),
        "MotionProfile": ("V", "ns=3;i=18570", {}),
        "MotorTemperature": ("V", "ns=3;i=16034", {}),
        "MoveOrCopy": ("M", "ns=3;i=7018", {}),
        "Name": ("V", "ns=3;i=18177", {}),
        "Numerator": ("V", "ns=3;i=16077", {}),
        "OnPath": ("V", "ns=3;i=16363", {}),
        "OperationalMode": ("V", "ns=3;i=15912", {}),
        "Orientation": ("V", "ns=3;i=16132", {}),
        "OutputArguments": ("V", "ns=3;i=6161", {}),
        "ParameterSet": ("O", "ns=3;i=15883", {}),
        "Pitch": ("V", "ns=3;i=17165", {}),
        "PossibleStopModes": ("V", "ns=3;i=6100", {}),
        "PowerTrains": ("O", "ns=3;i=19370", {}),
        "ProductCode": ("V", "ns=3;i=19283", {}),
        "ProgramStartToSuspended": ("O", "ns=3;i=5025", {}),
        "Programs": ("O", "ns=3;i=5054", {}),
        "ProtectiveStop": ("V", "ns=3;i=15913", {}),
        "ProtectiveStopFunctions": ("O", "ns=3;i=17225", {}),
        "Quality": ("V", "ns=3;i=6202", {}),
        "Ready": ("O", "ns=3;i=5041", {}),
        "ReadySubstateMachine": ("O", "ns=3;i=5039", {}),
        "ReadyToExecuting": ("O", "ns=3;i=5046", {}),
        "ReadyToIdle": ("O", "ns=3;i=5045", {}),
        "ReceiveTime": ("V", "ns=3;i=6208", {}),
        "ResetToProgramStart": ("M", "ns=3;i=7003", {}),
        "Retain": ("V", "ns=3;i=6204", {}),
        "Running": ("O", "ns=3;i=5020", {}),
        "RunningToStopping": ("O", "ns=3;i=5022", {}),
        "SafetyStates": ("O", "ns=3;i=5010", {}),
        "SerialNumber": ("V", "ns=3;i=19278", {}),
        "Severity": ("V", "ns=3;i=6209", {}),
        "Software": ("O", "ns=3;i=15483", {}),
        "SoftwareRevision": ("V", "ns=3;i=18873", {}),
        "SourceName": ("V", "ns=3;i=6210", {}),
        "SourceNode": ("V", "ns=3;i=6211", {}),
        "SourceTimestamp": ("V", "ns=3;i=6203", {}),
        "SpeedOverride": ("V", "ns=3;i=19291", {}),
        "StandBy": ("O", "ns=3;i=5015", {}),
        "StandByToGettingReady": ("O", "ns=3;i=5019", {}),
        "StandDown": ("M", "ns=3;i=7007", {}),
        "Start": ("M", "ns=3;i=7008", {}),
        "StartUpTime": ("V", "ns=3;i=15366", {}),
        "StateNumber": ("V", "ns=3;i=6050", {}),
        "Stop": ("M", "ns=3;i=7009", {}),
        "Stopping": ("O", "ns=3;i=5021", {}),
        "Suspended": ("O", "ns=3;i=5024", {}),
        "SuspendedToProgramStart": ("O", "ns=3;i=5026", {}),
        "SystemOperation": ("O", "ns=3;i=5055", {}),
        "SystemOperationStateMachine": ("O", "ns=3;i=5056", {}),
        "TaskControlOperation": ("O", "ns=3;i=5052", {}),
        "TaskControlReference": ("V", "ns=3;i=6004", {}),
        "TaskControlStateMachine": ("O", "ns=3;i=5053", {}),
        "TaskControls": ("O", "ns=3;i=15518", {}),
        "TaskModules": ("O", "ns=3;i=5057", {}),
        "TaskProgramLoaded": ("V", "ns=3;i=17875", {}),
        "TaskProgramName": ("V", "ns=3;i=17874", {}),
        "Temperature": ("V", "ns=3;i=17383", {}),
        "Time": ("V", "ns=3;i=6212", {}),
        "TotalEnergyConsumption": ("V", "ns=3;i=17359", {}),
        "TotalPowerOnTime": ("V", "ns=3;i=17358", {}),
        "TransitionNumber": ("V", "ns=3;i=6052", {}),
        "UnloadByName": ("M", "ns=3;i=7014", {}),
        "UnloadByNodeId": ("M", "ns=3;i=7013", {}),
        "UnloadProgram": ("M", "ns=3;i=7012", {}),
        "UpsState": ("V", "ns=3;i=15365", {}),
        "ValueAsText": ("V", "ns=3;i=6154", {}),
        "Version": ("V", "ns=3;i=6055", {}),
        "X": ("V", "ns=3;i=18171", {}),
        "Y": ("V", "ns=3;i=18172", {}),
        "Z": ("V", "ns=3;i=18173", {}),
        "http://opcfoundation.org/UA/Robotics/": (
            "O",
            "ns=3;i=15011",
            {
                "DefaultAccessRestrictions": ("V", "ns=3;i=15585", {}),
                "DefaultRolePermissions": ("V", "ns=3;i=15583", {}),
                "DefaultUserRolePermissions": ("V", "ns=3;i=15584", {}),
                "IsNamespaceSubset": ("V", "ns=3;i=15114", {}),
                "NamespacePublicationDate": ("V", "ns=3;i=15091", {}),
                "NamespaceUri": ("V", "ns=3;i=15034", {}),
                "NamespaceVersion": ("V", "ns=3;i=15064", {}),
                "StaticNodeIdTypes": ("V", "ns=3;i=15145", {}),
                "StaticNumericNodeIdRange": ("V", "ns=3;i=15173", {}),
                "StaticStringNodeIdPattern": ("V", "ns=3;i=15209", {}),
            },
        ),
    },
    "objtypes": {
        "AuxiliaryComponentType": ("OT", "ns=3;i=17725", {}),
        "AxisType": ("OT", "ns=3;i=16601", {}),
        "ControllerType": ("OT", "ns=3;i=1003", {}),
        "DriveType": ("OT", "ns=3;i=17793", {}),
        "EmergencyStopFunctionType": ("OT", "ns=3;i=17230", {}),
        "ExecutingSubstateMachineType": ("OT", "ns=3;i=1007", {}),
        "GearType": ("OT", "ns=3;i=1022", {}),
        "IdleSubstateMachineType": ("OT", "ns=3;i=1009", {}),
        "LoadType": ("OT", "ns=3;i=1018", {}),
        "MotionDeviceSystemType": ("OT", "ns=3;i=1002", {}),
        "MotionDeviceType": ("OT", "ns=3;i=1004", {}),
        "MotorType": ("OT", "ns=3;i=1019", {}),
        "MultiAcknowledgeableConditionType": ("OT", "ns=3;i=1015", {}),
        "OperationStateMachineType": (
            "OT",
            "ns=3;i=1006",
            {
                "SystemOperationStateMachineType": ("OT", "ns=3;i=1021", {}),
                "TaskControlStateMachineType": ("OT", "ns=3;i=1025", {}),
            },
        ),
        "PowerTrainType": ("OT", "ns=3;i=16794", {}),
        "ProtectiveStopFunctionType": ("OT", "ns=3;i=17233", {}),
        "ReadySubstateMachineType": ("OT", "ns=3;i=1012", {}),
        "SafetyStateType": ("OT", "ns=3;i=1013", {}),
        "SystemOperationType": ("OT", "ns=3;i=1028", {}),
        "TaskControlOperationType": ("OT", "ns=3;i=1008", {}),
        "TaskControlType": ("OT", "ns=3;i=1011", {}),
        "TaskModuleType": ("OT", "ns=3;i=1016", {}),
        "UserType": ("OT", "ns=3;i=18175", {}),
    },
    "reftypes": {
        "Controls": ("RT", "ns=3;i=4002", {}),
        "HasSafetyStates": ("RT", "ns=3;i=18182", {}),
        "HasSlave": ("RT", "ns=3;i=18183", {}),
        "IsConnectedTo": ("RT", "ns=3;i=18181", {}),
        "IsDrivenBy": ("RT", "ns=3;i=18180", {}),
        "Moves": ("RT", "ns=3;i=18178", {}),
        "Requires": ("RT", "ns=3;i=18179", {}),
    },
}
