# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.ia as ia

import o6.ns.isa95_jobcontrol_v2 as isa95_jobcontrol_v2

import o6.ns.machine_tool as machine_tool

import o6.ns.machinery as machinery

import o6.ns.machinery_jobs as machinery_jobs

import o6.ns.machinery_result as machinery_result

import o6.ns.ns0 as ns0

class RecipeIdDataType(ns0.datatypes.Structure):
    @property
    def name(self) -> o6.String | None: ...
    @name.setter
    def name(self, value: o6.String | None) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def type(self) -> o6.String | None: ...
    @type.setter
    def type(self, value: o6.String | None) -> None: ...
    @property
    def description(self) -> o6.String | None: ...
    @description.setter
    def description(self, value: o6.String | None) -> None: ...
    @property
    def comment(self) -> o6.String | None: ...
    @comment.setter
    def comment(self, value: o6.String | None) -> None: ...
    @property
    def modifiedDate(self) -> o6.DateTime | None: ...
    @modifiedDate.setter
    def modifiedDate(self, value: o6.DateTime | None) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...
    @property
    def validated(self) -> o6.Boolean | None: ...
    @validated.setter
    def validated(self, value: _Boolean | None) -> None: ...

class ExchangeablePartDataType(ns0.datatypes.Structure):
    @property
    def partType(self) -> o6.String: ...
    @partType.setter
    def partType(self, value: o6.String) -> None: ...
    @property
    def mounted(self) -> o6.Boolean: ...
    @mounted.setter
    def mounted(self, value: _Boolean) -> None: ...
    @property
    def traceable(self) -> o6.Boolean | None: ...
    @traceable.setter
    def traceable(self, value: _Boolean | None) -> None: ...
    @property
    def partId(self) -> o6.String | None: ...
    @partId.setter
    def partId(self, value: o6.String | None) -> None: ...
    @property
    def machineReadable(self) -> o6.Boolean | None: ...
    @machineReadable.setter
    def machineReadable(self, value: _Boolean | None) -> None: ...
    @property
    def lastCalibrationDate(self) -> o6.DateTime | None: ...
    @lastCalibrationDate.setter
    def lastCalibrationDate(self, value: o6.DateTime | None) -> None: ...

class OptionalModuleDataType(ns0.datatypes.Structure):
    @property
    def moduleName(self) -> o6.String: ...
    @moduleName.setter
    def moduleName(self, value: o6.String) -> None: ...
    @property
    def moduleType(self) -> o6.String: ...
    @moduleType.setter
    def moduleType(self, value: o6.String) -> None: ...
    @property
    def isInstalled(self) -> o6.Boolean: ...
    @isInstalled.setter
    def isInstalled(self, value: _Boolean) -> None: ...
    @property
    def version(self) -> o6.String | None: ...
    @version.setter
    def version(self, value: o6.String | None) -> None: ...

class StatisticResultContentDataType(ns0.datatypes.Structure):
    @property
    def resultKey(self) -> o6.String: ...
    @resultKey.setter
    def resultKey(self, value: o6.String) -> None: ...
    @property
    def itemCount(self) -> o6.UInt32: ...
    @itemCount.setter
    def itemCount(self, value: _Integer) -> None: ...
    @property
    def meanValue(self) -> o6.Double: ...
    @meanValue.setter
    def meanValue(self, value: SupportsFloat) -> None: ...
    @property
    def standardDeviation(self) -> o6.Double: ...
    @standardDeviation.setter
    def standardDeviation(self, value: SupportsFloat) -> None: ...
    @property
    def coefficientOfVariation(self) -> o6.Double: ...
    @coefficientOfVariation.setter
    def coefficientOfVariation(self, value: SupportsFloat) -> None: ...
    @property
    def minValue(self) -> o6.Double: ...
    @minValue.setter
    def minValue(self, value: SupportsFloat) -> None: ...
    @property
    def maxValue(self) -> o6.Double: ...
    @maxValue.setter
    def maxValue(self, value: SupportsFloat) -> None: ...
    @property
    def confidenceInterval95(self) -> o6.Double: ...
    @confidenceInterval95.setter
    def confidenceInterval95(self, value: SupportsFloat) -> None: ...

class StatisticResultContentWithUnitsDataType(StatisticResultContentDataType):
    @property
    def resultKey(self) -> o6.String: ...
    @resultKey.setter
    def resultKey(self, value: o6.String) -> None: ...
    @property
    def itemCount(self) -> o6.UInt32: ...
    @itemCount.setter
    def itemCount(self, value: _Integer) -> None: ...
    @property
    def meanValue(self) -> o6.Double: ...
    @meanValue.setter
    def meanValue(self, value: SupportsFloat) -> None: ...
    @property
    def standardDeviation(self) -> o6.Double: ...
    @standardDeviation.setter
    def standardDeviation(self, value: SupportsFloat) -> None: ...
    @property
    def coefficientOfVariation(self) -> o6.Double: ...
    @coefficientOfVariation.setter
    def coefficientOfVariation(self, value: SupportsFloat) -> None: ...
    @property
    def minValue(self) -> o6.Double: ...
    @minValue.setter
    def minValue(self, value: SupportsFloat) -> None: ...
    @property
    def maxValue(self) -> o6.Double: ...
    @maxValue.setter
    def maxValue(self, value: SupportsFloat) -> None: ...
    @property
    def confidenceInterval95(self) -> o6.Double: ...
    @confidenceInterval95.setter
    def confidenceInterval95(self, value: SupportsFloat) -> None: ...
    @property
    def unitItemCount(self) -> ns0.datatypes.EUInformation: ...
    @unitItemCount.setter
    def unitItemCount(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitMeanValue(self) -> ns0.datatypes.EUInformation: ...
    @unitMeanValue.setter
    def unitMeanValue(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitStandardDeviation(self) -> ns0.datatypes.EUInformation: ...
    @unitStandardDeviation.setter
    def unitStandardDeviation(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitCoefficientOfVariation(self) -> ns0.datatypes.EUInformation: ...
    @unitCoefficientOfVariation.setter
    def unitCoefficientOfVariation(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitMinValue(self) -> ns0.datatypes.EUInformation: ...
    @unitMinValue.setter
    def unitMinValue(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitMaxValue(self) -> ns0.datatypes.EUInformation: ...
    @unitMaxValue.setter
    def unitMaxValue(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def unitConfidenceInterval(self) -> ns0.datatypes.EUInformation: ...
    @unitConfidenceInterval.setter
    def unitConfidenceInterval(self, value: ns0.datatypes.EUInformation) -> None: ...

class RecipeDataType(ns0.datatypes.Structure):
    @property
    def recipeId(self) -> RecipeIdDataType: ...
    @recipeId.setter
    def recipeId(self, value: RecipeIdDataType) -> None: ...
    @property
    def recipeContent(self) -> o6.ByteString: ...
    @recipeContent.setter
    def recipeContent(self, value: o6.ByteString) -> None: ...
    @property
    def contentEncoding(self) -> o6.String: ...
    @contentEncoding.setter
    def contentEncoding(self, value: o6.String) -> None: ...

class TTDResultMetaDataType(machinery_result.datatypes.ResultMetaDataType):
    @property
    def resultId(self) -> o6.String: ...
    @resultId.setter
    def resultId(self, value: o6.String) -> None: ...
    @property
    def hasTransferableDataOnFile(self) -> o6.Boolean | None: ...
    @hasTransferableDataOnFile.setter
    def hasTransferableDataOnFile(self, value: _Boolean | None) -> None: ...
    @property
    def isPartial(self) -> o6.Boolean | None: ...
    @isPartial.setter
    def isPartial(self, value: _Boolean | None) -> None: ...
    @property
    def isSimulated(self) -> o6.Boolean | None: ...
    @isSimulated.setter
    def isSimulated(self, value: _Boolean | None) -> None: ...
    @property
    def resultState(self) -> o6.Int32 | None: ...
    @resultState.setter
    def resultState(self, value: _Integer | None) -> None: ...
    @property
    def stepId(self) -> o6.String | None: ...
    @stepId.setter
    def stepId(self, value: o6.String | None) -> None: ...
    @property
    def partId(self) -> o6.String | None: ...
    @partId.setter
    def partId(self, value: o6.String | None) -> None: ...
    @property
    def externalRecipeId(self) -> o6.String | None: ...
    @externalRecipeId.setter
    def externalRecipeId(self, value: o6.String | None) -> None: ...
    @property
    def internalRecipeId(self) -> o6.String | None: ...
    @internalRecipeId.setter
    def internalRecipeId(self, value: o6.String | None) -> None: ...
    @property
    def productId(self) -> o6.String | None: ...
    @productId.setter
    def productId(self, value: o6.String | None) -> None: ...
    @property
    def externalConfigurationId(self) -> o6.String | None: ...
    @externalConfigurationId.setter
    def externalConfigurationId(self, value: o6.String | None) -> None: ...
    @property
    def internalConfigurationId(self) -> o6.String | None: ...
    @internalConfigurationId.setter
    def internalConfigurationId(self, value: o6.String | None) -> None: ...
    @property
    def jobId(self) -> o6.String | None: ...
    @jobId.setter
    def jobId(self, value: o6.String | None) -> None: ...
    @property
    def creationTime(self) -> o6.DateTime | None: ...
    @creationTime.setter
    def creationTime(self, value: o6.DateTime | None) -> None: ...
    @property
    def processingTimes(self) -> machinery_result.datatypes.ProcessingTimesDataType | None: ...
    @processingTimes.setter
    def processingTimes(self, value: machinery_result.datatypes.ProcessingTimesDataType | None) -> None: ...
    @property
    def resultUri(self) -> list[o6.String] | None: ...
    @resultUri.setter
    def resultUri(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def resultEvaluation(self) -> machinery_result.datatypes.ResultEvaluationEnum | None: ...
    @resultEvaluation.setter
    def resultEvaluation(self, value: machinery_result.datatypes.ResultEvaluationEnum | None) -> None: ...
    @property
    def resultEvaluationCode(self) -> o6.Int64 | None: ...
    @resultEvaluationCode.setter
    def resultEvaluationCode(self, value: _Integer | None) -> None: ...
    @property
    def resultEvaluationDetails(self) -> o6.LocalizedText | None: ...
    @resultEvaluationDetails.setter
    def resultEvaluationDetails(self, value: o6.LocalizedText | None) -> None: ...
    @property
    def fileFormat(self) -> list[o6.String] | None: ...
    @fileFormat.setter
    def fileFormat(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def sampleId(self) -> o6.String: ...
    @sampleId.setter
    def sampleId(self, value: o6.String) -> None: ...
    @property
    def testerJobId(self) -> o6.String: ...
    @testerJobId.setter
    def testerJobId(self, value: o6.String) -> None: ...
    @property
    def testerSampleResultId(self) -> o6.String: ...
    @testerSampleResultId.setter
    def testerSampleResultId(self, value: o6.String) -> None: ...
    @property
    def productInstanceURI(self) -> o6.String: ...
    @productInstanceURI.setter
    def productInstanceURI(self, value: o6.String) -> None: ...
    @property
    def canBeDeleted(self) -> o6.Boolean: ...
    @canBeDeleted.setter
    def canBeDeleted(self, value: _Boolean) -> None: ...
    @property
    def jobOrder(self) -> isa95_jobcontrol_v2.datatypes.ISA95JobOrderDataType: ...
    @jobOrder.setter
    def jobOrder(self, value: isa95_jobcontrol_v2.datatypes.ISA95JobOrderDataType) -> None: ...

class TestNumDataType(ns0.datatypes.Structure):
    @property
    def testProcedureId(self) -> o6.String: ...
    @testProcedureId.setter
    def testProcedureId(self, value: o6.String) -> None: ...
    @property
    def numberOfTests(self) -> o6.UInt32: ...
    @numberOfTests.setter
    def numberOfTests(self, value: _Integer) -> None: ...

class SampleInfoDataType(ns0.datatypes.Structure):
    @property
    def sampleId(self) -> o6.String: ...
    @sampleId.setter
    def sampleId(self, value: o6.String) -> None: ...
    @property
    def nominalLinearDensity(self) -> o6.Double: ...
    @nominalLinearDensity.setter
    def nominalLinearDensity(self, value: SupportsFloat) -> None: ...
    @property
    def materialDensity(self) -> o6.Double | None: ...
    @materialDensity.setter
    def materialDensity(self, value: SupportsFloat | None) -> None: ...
    @property
    def materialType(self) -> o6.String | None: ...
    @materialType.setter
    def materialType(self, value: o6.String | None) -> None: ...
    @property
    def positionOnCarrier(self) -> o6.String: ...
    @positionOnCarrier.setter
    def positionOnCarrier(self, value: o6.String) -> None: ...

class JobOrderDataType(ns0.datatypes.Structure):
    @property
    def jobId(self) -> o6.String: ...
    @jobId.setter
    def jobId(self, value: o6.String) -> None: ...
    @property
    def recipeId(self) -> RecipeIdDataType: ...
    @recipeId.setter
    def recipeId(self, value: RecipeIdDataType) -> None: ...
    @property
    def numberOfTests(self) -> list[TestNumDataType]: ...
    @numberOfTests.setter
    def numberOfTests(self, value: Sequence[TestNumDataType]) -> None: ...
    @property
    def sampleInfos(self) -> list[SampleInfoDataType]: ...
    @sampleInfos.setter
    def sampleInfos(self, value: Sequence[SampleInfoDataType]) -> None: ...
    @property
    def carrierTypeId(self) -> o6.String: ...
    @carrierTypeId.setter
    def carrierTypeId(self, value: o6.String) -> None: ...
    @property
    def carrierId(self) -> o6.String: ...
    @carrierId.setter
    def carrierId(self, value: o6.String) -> None: ...
    @property
    def additionalInfo(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @additionalInfo.setter
    def additionalInfo(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...
    @property
    def scheduled(self) -> o6.Boolean: ...
    @scheduled.setter
    def scheduled(self, value: _Boolean) -> None: ...

class TestProcedureIdDataType(ns0.datatypes.Structure):
    @property
    def testProcedureId(self) -> o6.String: ...
    @testProcedureId.setter
    def testProcedureId(self, value: o6.String) -> None: ...
    @property
    def description(self) -> o6.String | None: ...
    @description.setter
    def description(self, value: o6.String | None) -> None: ...
    @property
    def procedureReferences(self) -> list[o6.String] | None: ...
    @procedureReferences.setter
    def procedureReferences(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def isProcedureLicensed(self) -> o6.Boolean | None: ...
    @isProcedureLicensed.setter
    def isProcedureLicensed(self, value: _Boolean | None) -> None: ...
