# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.ia as ia

import o6.ns.isa95_jobcontrol_v2 as isa95_jobcontrol_v2

import o6.ns.machinery as machinery

import o6.ns.machinery_jobs as machinery_jobs

import o6.ns.machinery_result as machinery_result

import o6.ns.ns0 as ns0

import o6.ns.wire_harness_vec as wire_harness_vec

class ProcessInputDataType(ns0.datatypes.Structure):
    @property
    def toolType(self) -> list[o6.String]: ...
    @toolType.setter
    def toolType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def processDescription(self) -> list[o6.String]: ...
    @processDescription.setter
    def processDescription(self, value: Sequence[o6.String]) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...

class CutInputDataType(ProcessInputDataType):
    @property
    def toolType(self) -> list[o6.String]: ...
    @toolType.setter
    def toolType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def processDescription(self) -> list[o6.String]: ...
    @processDescription.setter
    def processDescription(self, value: Sequence[o6.String]) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def referencedElement(self) -> wire_harness_vec.datatypes.WireElementReferenceIdDataType: ...
    @referencedElement.setter
    def referencedElement(self, value: wire_harness_vec.datatypes.WireElementReferenceIdDataType) -> None: ...
    @property
    def verifyWireLength(self) -> list[o6.Boolean]: ...
    @verifyWireLength.setter
    def verifyWireLength(self, value: Sequence[_Boolean]) -> None: ...

class ProcessOutputDataType(ns0.datatypes.Structure):
    @property
    def toolInstance(self) -> o6.String: ...
    @toolInstance.setter
    def toolInstance(self, value: o6.String) -> None: ...

class CutOutputDataType(ProcessOutputDataType):
    @property
    def toolInstance(self) -> o6.String: ...
    @toolInstance.setter
    def toolInstance(self, value: o6.String) -> None: ...
    @property
    def actualLength(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualLength.setter
    def actualLength(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...

class ForceCurvePointDataType(ns0.datatypes.Structure):
    @property
    def x(self) -> list[o6.UInt32]: ...
    @x.setter
    def x(self, value: Sequence[_Integer]) -> None: ...
    @property
    def value(self) -> list[o6.UInt32]: ...
    @value.setter
    def value(self, value: Sequence[_Integer]) -> None: ...

class CrimpInputDataType(ProcessInputDataType):
    @property
    def toolType(self) -> list[o6.String]: ...
    @toolType.setter
    def toolType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def processDescription(self) -> list[o6.String]: ...
    @processDescription.setter
    def processDescription(self, value: Sequence[o6.String]) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def referencedElement(self) -> wire_harness_vec.datatypes.WireMountingIdDataType: ...
    @referencedElement.setter
    def referencedElement(self, value: wire_harness_vec.datatypes.WireMountingIdDataType) -> None: ...
    @property
    def verifyCrimpHeight(self) -> list[o6.Boolean]: ...
    @verifyCrimpHeight.setter
    def verifyCrimpHeight(self, value: Sequence[_Boolean]) -> None: ...
    @property
    def verifyCrimpWidth(self) -> list[o6.Boolean]: ...
    @verifyCrimpWidth.setter
    def verifyCrimpWidth(self, value: Sequence[_Boolean]) -> None: ...
    @property
    def verifyInsulationCrimpHeight(self) -> list[o6.Boolean]: ...
    @verifyInsulationCrimpHeight.setter
    def verifyInsulationCrimpHeight(self, value: Sequence[_Boolean]) -> None: ...
    @property
    def verifyInsulationCrimpWidth(self) -> list[o6.Boolean]: ...
    @verifyInsulationCrimpWidth.setter
    def verifyInsulationCrimpWidth(self, value: Sequence[_Boolean]) -> None: ...
    @property
    def verifyPullOutForce(self) -> list[o6.Boolean]: ...
    @verifyPullOutForce.setter
    def verifyPullOutForce(self, value: Sequence[_Boolean]) -> None: ...
    @property
    def crimpForceMonitoring(self) -> list[o6.Boolean]: ...
    @crimpForceMonitoring.setter
    def crimpForceMonitoring(self, value: Sequence[_Boolean]) -> None: ...

class StripInputDataType(ProcessInputDataType):
    @property
    def toolType(self) -> list[o6.String]: ...
    @toolType.setter
    def toolType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def processDescription(self) -> list[o6.String]: ...
    @processDescription.setter
    def processDescription(self, value: Sequence[o6.String]) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def referencedElement(self) -> wire_harness_vec.datatypes.WireEndIdDataType: ...
    @referencedElement.setter
    def referencedElement(self, value: wire_harness_vec.datatypes.WireEndIdDataType) -> None: ...
    @property
    def strippingLengthMonitoring(self) -> list[o6.Boolean]: ...
    @strippingLengthMonitoring.setter
    def strippingLengthMonitoring(self, value: Sequence[_Boolean]) -> None: ...

class StripOutputDataType(ProcessOutputDataType):
    @property
    def toolInstance(self) -> o6.String: ...
    @toolInstance.setter
    def toolInstance(self, value: o6.String) -> None: ...
    @property
    def actualStrippingLength(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualStrippingLength.setter
    def actualStrippingLength(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...

class ForceCurveDataType(ns0.datatypes.Structure):
    @property
    def points(self) -> list[ForceCurvePointDataType]: ...
    @points.setter
    def points(self, value: Sequence[ForceCurvePointDataType]) -> None: ...
    @property
    def engineeringUnitsX(self) -> ns0.datatypes.EUInformation: ...
    @engineeringUnitsX.setter
    def engineeringUnitsX(self, value: ns0.datatypes.EUInformation) -> None: ...
    @property
    def engineeringUnitsValue(self) -> ns0.datatypes.EUInformation: ...
    @engineeringUnitsValue.setter
    def engineeringUnitsValue(self, value: ns0.datatypes.EUInformation) -> None: ...

class CrimpOutputDataType(ProcessOutputDataType):
    @property
    def toolInstance(self) -> o6.String: ...
    @toolInstance.setter
    def toolInstance(self, value: o6.String) -> None: ...
    @property
    def actualCrimpHeight(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualCrimpHeight.setter
    def actualCrimpHeight(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...
    @property
    def actualCrimpWidth(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualCrimpWidth.setter
    def actualCrimpWidth(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...
    @property
    def actualInsulationCrimpHeight(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualInsulationCrimpHeight.setter
    def actualInsulationCrimpHeight(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...
    @property
    def actualCrimpForceCurve(self) -> list[ForceCurveDataType]: ...
    @actualCrimpForceCurve.setter
    def actualCrimpForceCurve(self, value: Sequence[ForceCurveDataType]) -> None: ...
    @property
    def actualCrimpPullOutForce(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualCrimpPullOutForce.setter
    def actualCrimpPullOutForce(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...

class SealInputDataType(ProcessInputDataType):
    @property
    def toolType(self) -> list[o6.String]: ...
    @toolType.setter
    def toolType(self, value: Sequence[o6.String]) -> None: ...
    @property
    def processDescription(self) -> list[o6.String]: ...
    @processDescription.setter
    def processDescription(self, value: Sequence[o6.String]) -> None: ...
    @property
    def id(self) -> o6.String: ...
    @id.setter
    def id(self, value: o6.String) -> None: ...
    @property
    def referencedElement(self) -> wire_harness_vec.datatypes.WireMountingIdDataType: ...
    @referencedElement.setter
    def referencedElement(self, value: wire_harness_vec.datatypes.WireMountingIdDataType) -> None: ...
    @property
    def monitorSealPosition(self) -> list[o6.Boolean]: ...
    @monitorSealPosition.setter
    def monitorSealPosition(self, value: Sequence[_Boolean]) -> None: ...

class SealOutputDataType(ProcessOutputDataType):
    @property
    def toolInstance(self) -> o6.String: ...
    @toolInstance.setter
    def toolInstance(self, value: o6.String) -> None: ...
    @property
    def actualPosition(self) -> list[wire_harness_vec.datatypes.NumericalValue]: ...
    @actualPosition.setter
    def actualPosition(self, value: Sequence[wire_harness_vec.datatypes.NumericalValue]) -> None: ...
