# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Generate src_gen/src_nodeids.c and src_gen/src_nodeids.h from NodeIds.csv.

The CSV is the standard OPC UA namespace-zero node id table shipped with
open62541 (deps/open62541/tools/schema/NodeIds.csv).  Each row has the form:

    Name,NumericId,NodeKind

The generator produces a single C function ``add_all_nodeids`` that registers
every entry as ``NS0ID_<NAME> = <id>`` integer constant on the ``o6._o6.types``
Python module.

Usage:
    python tools/generate_nodeids.py deps/open62541/tools/schema/NodeIds.csv src_gen
"""

import argparse
import csv
import os
import re
import subprocess
import sys


def _sanitise(name: str) -> str:
    """Turn a NodeIds.csv name into a valid C/Python identifier."""
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


def _camel_to_upper_snake(name: str) -> str:
    """Convert a PascalCase/CamelCase identifier to UPPER_SNAKE_CASE.

    Examples:
        Boolean            -> BOOLEAN
        SByte              -> S_BYTE
        UInt32             -> U_INT32
        HasTypeDefinition  -> HAS_TYPE_DEFINITION
        OPCBinarySchema    -> OPC_BINARY_SCHEMA
        ModellingRule_Mandatory -> MODELLING_RULE_MANDATORY
    """
    # Insert underscore between a lowercase/digit and an uppercase letter
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name)
    # Insert underscore between a run of uppercase letters and an uppercase+lowercase pair
    # e.g. "OPCBinary" -> "OPC_Binary", "UInt" -> "U_Int"
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', s)
    return s.upper()


def generate(csv_path: str, output_dir: str, pyi_path: str | None = None) -> None:
    entries: list[tuple[str, int]] = []
    with open(csv_path, newline='') as f:
        for row in csv.reader(f):
            if len(row) < 2:
                continue
            name, numeric_id = row[0], row[1]
            try:
                nid = int(numeric_id)
            except ValueError:
                continue
            entries.append((_camel_to_upper_snake(_sanitise(name)), nid))

    # -- .h ----------------------------------------------------------------
    h_lines = [
        '/**********************************',
        ' * Autogenerated -- do not modify *',
        ' **********************************/',
        '',
        '#ifndef SRC_NODEIDS_H_',
        '#define SRC_NODEIDS_H_',
        '',
        '#include <Python.h>',
        '',
        '/* Add all namespace-0 node ids as NS0ID_<NAME> integer constants',
        ' * to the given module. */',
        'int add_all_nodeids(PyObject *module);',
        '',
        '#endif /* SRC_NODEIDS_H_ */',
        '',
    ]

    # -- .c ----------------------------------------------------------------
    c_lines = [
        '/**********************************',
        ' * Autogenerated -- do not modify *',
        ' **********************************/',
        '',
        '#include "src_nodeids.h"',
        '',
        'int add_all_nodeids(PyObject *module) {',
    ]
    for name, nid in entries:
        c_lines.append(
            f'    if (PyModule_AddIntConstant(module, "NS0ID_{name}", {nid}) < 0) return -1;'
        )
    c_lines.append('    return 0;')
    c_lines.append('}')
    c_lines.append('')

    os.makedirs(output_dir, exist_ok=True)
    h_path = os.path.join(output_dir, 'src_nodeids.h')
    c_path = os.path.join(output_dir, 'src_nodeids.c')

    with open(h_path, 'w') as f:
        f.write('\n'.join(h_lines))
    with open(c_path, 'w') as f:
        f.write('\n'.join(c_lines))

    print(f'Generated {h_path}  ({len(entries)} node ids)')
    print(f'Generated {c_path}')

    if pyi_path is not None:
        pyi_lines = [
            '# This file is auto-generated by tools/generate_python_nodeids.py',
            '# Do not edit manually.',
            '',
        ]
        for name, nid in entries:
            pyi_lines.append(f'NS0ID_{name}: int')
        pyi_lines.append('')
        with open(pyi_path, 'w') as f:
            f.write('\n'.join(pyi_lines))
        print(f'Generated {pyi_path}')
        try:
            subprocess.run([sys.executable, '-m', 'black', '--fast', '-q', pyi_path], check=True)
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass  # black is optional


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate C code that exposes OPC UA namespace-0 node ids '
                    'as integer constants on the o6._o6.types module.')
    parser.add_argument('csv_file',
                        help='Path to NodeIds.csv '
                             '(e.g. deps/open62541/tools/schema/NodeIds.csv)')
    parser.add_argument('output_dir',
                        help='Directory for generated .c/.h '
                             '(e.g. src_gen)')
    parser.add_argument('-p', '--pyi',
                        metavar='FILE',
                        help='Optional path for the generated .pyi stub '
                             '(e.g. o6/_o6/consts_gen.pyi)')
    args = parser.parse_args()
    generate(args.csv_file, args.output_dir, pyi_path=args.pyi)


if __name__ == '__main__':
    main()
