# Copyright (c) 2026 o6 Automation GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Any, Sequence, SupportsFloat

import numpy as np

_Integer = int | np.integer[Any]

_Boolean = bool | np.bool_

import enum

from o6.node import ObjectNode as _ObjectNode, VariableNode as _VariableNode

import uuid

import o6

import o6.ns.di as di

import o6.ns.fx_data as fx_data

import o6.ns.ns0 as ns0

class PortableKeyValuePair(ns0.datatypes.Structure):
    @property
    def key(self) -> ns0.datatypes.PortableQualifiedName: ...
    @key.setter
    def key(self, value: ns0.datatypes.PortableQualifiedName) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class ServerAddressDataType(ns0.datatypes.Structure):
    @property
    def address(self) -> o6.String: ...
    @address.setter
    def address(self, value: o6.String) -> None: ...
    @property
    def securityMode(self) -> ns0.datatypes.MessageSecurityMode: ...
    @securityMode.setter
    def securityMode(self, value: ns0.datatypes.MessageSecurityMode) -> None: ...
    @property
    def securityPolicyUri(self) -> o6.String: ...
    @securityPolicyUri.setter
    def securityPolicyUri(self, value: o6.String) -> None: ...
    @property
    def serverUri(self) -> o6.String: ...
    @serverUri.setter
    def serverUri(self, value: o6.String) -> None: ...

class PortableRelativePathElement(ns0.datatypes.Structure):
    @property
    def referenceTypeId(self) -> ns0.datatypes.PortableNodeId: ...
    @referenceTypeId.setter
    def referenceTypeId(self, value: ns0.datatypes.PortableNodeId) -> None: ...
    @property
    def isInverse(self) -> o6.Boolean: ...
    @isInverse.setter
    def isInverse(self, value: _Boolean) -> None: ...
    @property
    def includeSubtypes(self) -> o6.Boolean: ...
    @includeSubtypes.setter
    def includeSubtypes(self, value: _Boolean) -> None: ...
    @property
    def targetName(self) -> ns0.datatypes.PortableQualifiedName: ...
    @targetName.setter
    def targetName(self, value: ns0.datatypes.PortableQualifiedName) -> None: ...

class PortableRelativePath(ns0.datatypes.Structure):
    @property
    def elements(self) -> list[PortableRelativePathElement]: ...
    @elements.setter
    def elements(self, value: Sequence[PortableRelativePathElement]) -> None: ...

class FxEditEnum(enum.IntFlag):
    START_EDITING = 0
    COMMIT_UPDATES = 1
    DISCARD_UPDATES = 2

class FxProcessEnum(enum.IntFlag):
    ACTION_ESTABLISH_CONNECTIONS_ENABLED = 0
    ACTION_ESTABLISH_CONNECTIONS_DISABLED = 1
    ACTION_ESTABLISH_CONNECTIONS = 2
    ACTION_REMOVE_CONNECTIONS = 3
    ACTION_ENABLE_CONNECTIONS = 4
    ACTION_DISABLE_CONNECTIONS = 5

class CommunicationFlowQosDataType(ns0.datatypes.Structure):
    @property
    def qosCategory(self) -> o6.String: ...
    @qosCategory.setter
    def qosCategory(self, value: o6.String) -> None: ...
    @property
    def transmitQos(self) -> list[ns0.datatypes.TransmitQosDataType]: ...
    @transmitQos.setter
    def transmitQos(self, value: Sequence[ns0.datatypes.TransmitQosDataType]) -> None: ...
    @property
    def receiveQos(self) -> list[ns0.datatypes.ReceiveQosDataType]: ...
    @receiveQos.setter
    def receiveQos(self, value: Sequence[ns0.datatypes.ReceiveQosDataType]) -> None: ...

class LastActivityMask(enum.IntFlag):
    ESTABLISH_ENABLED = 0
    ESTABLISH_DISABLED = 1
    ESTABLISH = 2
    REMOVE = 3
    ENABLE = 4
    DISABLE = 5
    ERROR = 15

class ConnectionStateEnum(enum.IntFlag):
    CONNECTION_NOT_MONITORED = 0
    CONNECTION_NOT_ESTABLISHED = 1
    CONNECTION_INITIAL = 2
    CONNECTION_READY = 3
    CONNECTION_PRE_OPERATIONAL = 4
    CONNECTION_OPERATIONAL = 5
    CONNECTION_ERROR = 6

class PortableNodeIdentifier(ns0.datatypes.Union):
    @property
    def node(self) -> ns0.datatypes.PortableNodeId: ...
    @node.setter
    def node(self, value: ns0.datatypes.PortableNodeId) -> None: ...
    @property
    def alias(self) -> o6.String: ...
    @alias.setter
    def alias(self, value: o6.String) -> None: ...
    @property
    def identifierBrowsePath(self) -> PortableRelativePath: ...
    @identifierBrowsePath.setter
    def identifierBrowsePath(self, value: PortableRelativePath) -> None: ...

class PortableNodeIdentifierValuePair(ns0.datatypes.Structure):
    @property
    def key(self) -> PortableNodeIdentifier: ...
    @key.setter
    def key(self, value: PortableNodeIdentifier) -> None: ...
    @property
    def arrayIndex(self) -> list[o6.UInt32]: ...
    @arrayIndex.setter
    def arrayIndex(self, value: Sequence[_Integer]) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class NodeIdTranslationDataType(ns0.datatypes.Structure):
    @property
    def nodePlaceholder(self) -> o6.NodeId: ...
    @nodePlaceholder.setter
    def nodePlaceholder(self, value: o6.NodeId) -> None: ...
    @property
    def portableNode(self) -> PortableNodeIdentifier: ...
    @portableNode.setter
    def portableNode(self, value: PortableNodeIdentifier) -> None: ...

class FxErrorEnum(enum.IntFlag):
    NO_ERROR = 0
    UNKNOWN_STATUS = 1
    ROLLBACK = 2
    PROCESSING_STOPPED = 3
    CONNECTION_CONFIGURATION_SET_INVALID = 4
    GDS_CONNECTION_ERROR = 5
    GDS_PROCESSING_ERROR = 6
    ALIAS_NAME_PROCESSING_ERROR = 7
    EXTERNAL_SKS_CONNECTION_ERROR = 8
    EXTERNAL_SKS_PROCESSING_ERROR = 9
    TARGET_SERVER_CONNECTION_ERROR = 10
    RESOLVING_NAMESPACES_ERROR = 11
    RESOLVING_PATHS_ERROR = 12
    VERIFY_ASSET_ERROR = 13
    VERIFY_FUNCTIONAL_ENTITY_ERROR = 14
    CREATE_CONNECTION_ENDPOINT_ERROR = 15
    ESTABLISH_CONTROL_ERROR = 16
    SET_CONFIGURATION_DATA_ERROR = 17
    REASSIGN_CONTROL_ERROR = 18
    RESERVE_COMMUNICATION_IDS_ERROR = 19
    SET_COMMUNICATION_CONFIGURATION_ERROR = 20
    ENABLE_COMMUNICATION_ERROR = 21
    CLOSE_CONNECTION_ERROR = 22
    LOCAL_SKS_KEY_PUSH_ERROR = 23
    RUNTIME_ERROR = 24

class ConnectionDiagnosticsDataType(ns0.datatypes.Structure):
    @property
    def name(self) -> o6.QualifiedName: ...
    @name.setter
    def name(self, value: o6.QualifiedName) -> None: ...
    @property
    def lastActivity(self) -> LastActivityMask: ...
    @lastActivity.setter
    def lastActivity(self, value: _Integer) -> None: ...
    @property
    def connectionState(self) -> ConnectionStateEnum: ...
    @connectionState.setter
    def connectionState(self, value: _Integer) -> None: ...
    @property
    def errorEndpoint1(self) -> FxErrorEnum: ...
    @errorEndpoint1.setter
    def errorEndpoint1(self, value: _Integer) -> None: ...
    @property
    def endpoint1Status(self) -> o6.StatusCode: ...
    @endpoint1Status.setter
    def endpoint1Status(self, value: _Integer) -> None: ...
    @property
    def errorEndpoint2(self) -> FxErrorEnum: ...
    @errorEndpoint2.setter
    def errorEndpoint2(self, value: _Integer) -> None: ...
    @property
    def endpoint2Status(self) -> o6.StatusCode: ...
    @endpoint2Status.setter
    def endpoint2Status(self, value: _Integer) -> None: ...

class SecurityKeyServerAddressDataType(ns0.datatypes.Structure):
    @property
    def address(self) -> o6.String: ...
    @address.setter
    def address(self, value: o6.String) -> None: ...
    @property
    def securityPolicyUri(self) -> o6.String: ...
    @securityPolicyUri.setter
    def securityPolicyUri(self, value: o6.String) -> None: ...
    @property
    def serverUri(self) -> o6.String: ...
    @serverUri.setter
    def serverUri(self, value: o6.String) -> None: ...
    @property
    def usePushModel(self) -> o6.Boolean: ...
    @usePushModel.setter
    def usePushModel(self, value: _Boolean) -> None: ...

class CommunicationFlowConfigurationConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def flowProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @flowProperties.setter
    def flowProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...

class SecurityKeyServerAddressConfDataType(ns0.datatypes.Structure):
    @property
    def address(self) -> o6.String: ...
    @address.setter
    def address(self, value: o6.String) -> None: ...
    @property
    def addressSelection(self) -> list[o6.String] | None: ...
    @addressSelection.setter
    def addressSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def addressModify(self) -> o6.Boolean | None: ...
    @addressModify.setter
    def addressModify(self, value: _Boolean | None) -> None: ...
    @property
    def securityPolicyUri(self) -> o6.String: ...
    @securityPolicyUri.setter
    def securityPolicyUri(self, value: o6.String) -> None: ...
    @property
    def securityPolicyUriSelection(self) -> list[o6.String] | None: ...
    @securityPolicyUriSelection.setter
    def securityPolicyUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def securityPolicyUriModify(self) -> o6.Boolean | None: ...
    @securityPolicyUriModify.setter
    def securityPolicyUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def serverUri(self) -> o6.String: ...
    @serverUri.setter
    def serverUri(self, value: o6.String) -> None: ...
    @property
    def serverUriSelection(self) -> list[o6.String] | None: ...
    @serverUriSelection.setter
    def serverUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def serverUriModify(self) -> o6.Boolean | None: ...
    @serverUriModify.setter
    def serverUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def usePushModel(self) -> o6.Boolean: ...
    @usePushModel.setter
    def usePushModel(self, value: _Boolean) -> None: ...
    @property
    def securityGroups(self) -> list[ns0.datatypes.SecurityGroupDataType] | None: ...
    @securityGroups.setter
    def securityGroups(self, value: Sequence[ns0.datatypes.SecurityGroupDataType] | None) -> None: ...
    @property
    def pubSubKeyPushTargets(self) -> list[ns0.datatypes.PubSubKeyPushTargetDataType] | None: ...
    @pubSubKeyPushTargets.setter
    def pubSubKeyPushTargets(self, value: Sequence[ns0.datatypes.PubSubKeyPushTargetDataType] | None) -> None: ...
    @property
    def sksProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @sksProperties.setter
    def sksProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...

class ServerAddressConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def address(self) -> o6.String: ...
    @address.setter
    def address(self, value: o6.String) -> None: ...
    @property
    def addressSelection(self) -> list[o6.String] | None: ...
    @addressSelection.setter
    def addressSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def addressModify(self) -> o6.Boolean | None: ...
    @addressModify.setter
    def addressModify(self, value: _Boolean | None) -> None: ...
    @property
    def securityMode(self) -> ns0.datatypes.MessageSecurityMode: ...
    @securityMode.setter
    def securityMode(self, value: ns0.datatypes.MessageSecurityMode) -> None: ...
    @property
    def securityModeSelection(self) -> list[ns0.datatypes.MessageSecurityMode] | None: ...
    @securityModeSelection.setter
    def securityModeSelection(self, value: Sequence[ns0.datatypes.MessageSecurityMode] | None) -> None: ...
    @property
    def securityModeModify(self) -> o6.Boolean | None: ...
    @securityModeModify.setter
    def securityModeModify(self, value: _Boolean | None) -> None: ...
    @property
    def securityPolicyUri(self) -> o6.String: ...
    @securityPolicyUri.setter
    def securityPolicyUri(self, value: o6.String) -> None: ...
    @property
    def securityPolicyUriSelection(self) -> list[o6.String] | None: ...
    @securityPolicyUriSelection.setter
    def securityPolicyUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def securityPolicyUriModify(self) -> o6.Boolean | None: ...
    @securityPolicyUriModify.setter
    def securityPolicyUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def serverUri(self) -> o6.String: ...
    @serverUri.setter
    def serverUri(self, value: o6.String) -> None: ...
    @property
    def serverUriSelection(self) -> list[o6.String] | None: ...
    @serverUriSelection.setter
    def serverUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def serverUriModify(self) -> o6.Boolean | None: ...
    @serverUriModify.setter
    def serverUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def serverProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @serverProperties.setter
    def serverProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...
    @property
    def namespaces(self) -> list[o6.String]: ...
    @namespaces.setter
    def namespaces(self, value: Sequence[o6.String]) -> None: ...

class CommunicationModelConfigurationDataType(ns0.datatypes.Structure):
    pass

class PubSubCommunicationModelConfigurationDataType(CommunicationModelConfigurationDataType):
    @property
    def pubSubConfiguration(self) -> ns0.datatypes.PubSubConfiguration2DataType: ...
    @pubSubConfiguration.setter
    def pubSubConfiguration(self, value: ns0.datatypes.PubSubConfiguration2DataType) -> None: ...
    @property
    def translationTable(self) -> list[NodeIdTranslationDataType]: ...
    @translationTable.setter
    def translationTable(self, value: Sequence[NodeIdTranslationDataType]) -> None: ...
    @property
    def configurationReferences(self) -> list[ns0.datatypes.PubSubConfigurationRefDataType]: ...
    @configurationReferences.setter
    def configurationReferences(self, value: Sequence[ns0.datatypes.PubSubConfigurationRefDataType]) -> None: ...

class NodeIdentifier(ns0.datatypes.Union):
    @property
    def node(self) -> o6.NodeId: ...
    @node.setter
    def node(self, value: o6.NodeId) -> None: ...
    @property
    def alias(self) -> o6.String: ...
    @alias.setter
    def alias(self, value: o6.String) -> None: ...
    @property
    def identifierBrowsePath(self) -> ns0.datatypes.RelativePath: ...
    @identifierBrowsePath.setter
    def identifierBrowsePath(self, value: ns0.datatypes.RelativePath) -> None: ...

class NodeIdentifierValuePair(ns0.datatypes.Structure):
    @property
    def key(self) -> NodeIdentifier: ...
    @key.setter
    def key(self, value: NodeIdentifier) -> None: ...
    @property
    def arrayIndex(self) -> list[o6.UInt32]: ...
    @arrayIndex.setter
    def arrayIndex(self, value: Sequence[_Integer]) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...

class ConnectionEndpointConfigurationConfDataType(ns0.datatypes.Structure):
    @property
    def functionalEntityNode(self) -> NodeIdentifier: ...
    @functionalEntityNode.setter
    def functionalEntityNode(self, value: NodeIdentifier) -> None: ...
    @property
    def functionalEntityNodeSelection(self) -> list[NodeIdentifier] | None: ...
    @functionalEntityNodeSelection.setter
    def functionalEntityNodeSelection(self, value: Sequence[NodeIdentifier] | None) -> None: ...
    @property
    def functionalEntityNodeModify(self) -> o6.Boolean | None: ...
    @functionalEntityNodeModify.setter
    def functionalEntityNodeModify(self, value: _Boolean | None) -> None: ...
    @property
    def name(self) -> o6.String: ...
    @name.setter
    def name(self, value: o6.String) -> None: ...
    @property
    def nameSelection(self) -> list[o6.String] | None: ...
    @nameSelection.setter
    def nameSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def nameModify(self) -> o6.Boolean | None: ...
    @nameModify.setter
    def nameModify(self, value: _Boolean | None) -> None: ...
    @property
    def connectionEndpointTypeId(self) -> o6.NodeId: ...
    @connectionEndpointTypeId.setter
    def connectionEndpointTypeId(self, value: o6.NodeId) -> None: ...
    @property
    def inputVariableIds(self) -> list[NodeIdentifier] | None: ...
    @inputVariableIds.setter
    def inputVariableIds(self, value: Sequence[NodeIdentifier] | None) -> None: ...
    @property
    def outputVariableIds(self) -> list[NodeIdentifier] | None: ...
    @outputVariableIds.setter
    def outputVariableIds(self, value: Sequence[NodeIdentifier] | None) -> None: ...
    @property
    def isPersistent(self) -> o6.Boolean: ...
    @isPersistent.setter
    def isPersistent(self, value: _Boolean) -> None: ...
    @property
    def cleanupTimeout(self) -> o6.Double: ...
    @cleanupTimeout.setter
    def cleanupTimeout(self, value: SupportsFloat) -> None: ...
    @property
    def isPreconfigured(self) -> o6.Boolean: ...
    @isPreconfigured.setter
    def isPreconfigured(self, value: _Boolean) -> None: ...
    @property
    def communicationLinks(self) -> o6.ExtensionObject | None: ...
    @communicationLinks.setter
    def communicationLinks(self, value: Any | None) -> None: ...
    @property
    def preconfiguredPublishedDataSet(self) -> o6.String | None: ...
    @preconfiguredPublishedDataSet.setter
    def preconfiguredPublishedDataSet(self, value: o6.String | None) -> None: ...
    @property
    def publishedDataSetData(self) -> ns0.datatypes.PublishedDataSetDataType | None: ...
    @publishedDataSetData.setter
    def publishedDataSetData(self, value: ns0.datatypes.PublishedDataSetDataType | None) -> None: ...
    @property
    def preconfiguredSubscribedDataSet(self) -> o6.String | None: ...
    @preconfiguredSubscribedDataSet.setter
    def preconfiguredSubscribedDataSet(self, value: o6.String | None) -> None: ...
    @property
    def subscribedDataSetData(self) -> ns0.datatypes.StandaloneSubscribedDataSetDataType | None: ...
    @subscribedDataSetData.setter
    def subscribedDataSetData(self, value: ns0.datatypes.StandaloneSubscribedDataSetDataType | None) -> None: ...
    @property
    def expectedVerificationVariables(self) -> list[NodeIdentifierValuePair] | None: ...
    @expectedVerificationVariables.setter
    def expectedVerificationVariables(self, value: Sequence[NodeIdentifierValuePair] | None) -> None: ...
    @property
    def controlGroups(self) -> list[NodeIdentifier] | None: ...
    @controlGroups.setter
    def controlGroups(self, value: Sequence[NodeIdentifier] | None) -> None: ...
    @property
    def configurationData(self) -> list[NodeIdentifierValuePair] | None: ...
    @configurationData.setter
    def configurationData(self, value: Sequence[NodeIdentifierValuePair] | None) -> None: ...
    @property
    def endpointProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @endpointProperties.setter
    def endpointProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...
    @property
    def automationComponentIndex(self) -> o6.Int32: ...
    @automationComponentIndex.setter
    def automationComponentIndex(self, value: _Integer) -> None: ...
    @property
    def outboundFlowIndex(self) -> o6.Int32 | None: ...
    @outboundFlowIndex.setter
    def outboundFlowIndex(self, value: _Integer | None) -> None: ...
    @property
    def inboundFlowIndex(self) -> list[o6.Int32] | None: ...
    @inboundFlowIndex.setter
    def inboundFlowIndex(self, value: Sequence[_Integer] | None) -> None: ...

class ConnectionConfigurationConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def endpoint1(self) -> ConnectionEndpointConfigurationConfDataType: ...
    @endpoint1.setter
    def endpoint1(self, value: ConnectionEndpointConfigurationConfDataType) -> None: ...
    @property
    def endpoint2(self) -> ConnectionEndpointConfigurationConfDataType | None: ...
    @endpoint2.setter
    def endpoint2(self, value: ConnectionEndpointConfigurationConfDataType | None) -> None: ...
    @property
    def connectionProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @connectionProperties.setter
    def connectionProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...

class AssetVerificationConfDataType(ns0.datatypes.Structure):
    @property
    def assetToVerify(self) -> NodeIdentifier: ...
    @assetToVerify.setter
    def assetToVerify(self, value: NodeIdentifier) -> None: ...
    @property
    def verificationMode(self) -> fx_data.datatypes.AssetVerificationModeEnum: ...
    @verificationMode.setter
    def verificationMode(self, value: fx_data.datatypes.AssetVerificationModeEnum) -> None: ...
    @property
    def expectedVerificationResult(self) -> fx_data.datatypes.AssetVerificationResultEnum: ...
    @expectedVerificationResult.setter
    def expectedVerificationResult(self, value: fx_data.datatypes.AssetVerificationResultEnum) -> None: ...
    @property
    def expectedVerificationVariables(self) -> list[NodeIdentifierValuePair]: ...
    @expectedVerificationVariables.setter
    def expectedVerificationVariables(self, value: Sequence[NodeIdentifierValuePair]) -> None: ...
    @property
    def expectedAdditionalVerificationVariables(self) -> list[NodeIdentifierValuePair]: ...
    @expectedAdditionalVerificationVariables.setter
    def expectedAdditionalVerificationVariables(self, value: Sequence[NodeIdentifierValuePair]) -> None: ...
    @property
    def assetProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @assetProperties.setter
    def assetProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...

class AutomationComponentConfigurationConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def automationComponentNode(self) -> NodeIdentifier: ...
    @automationComponentNode.setter
    def automationComponentNode(self, value: NodeIdentifier) -> None: ...
    @property
    def automationComponentNodeSelection(self) -> list[NodeIdentifier]: ...
    @automationComponentNodeSelection.setter
    def automationComponentNodeSelection(self, value: Sequence[NodeIdentifier]) -> None: ...
    @property
    def automationComponentNodeModify(self) -> o6.Boolean: ...
    @automationComponentNodeModify.setter
    def automationComponentNodeModify(self, value: _Boolean) -> None: ...
    @property
    def commandBundleRequired(self) -> o6.Boolean: ...
    @commandBundleRequired.setter
    def commandBundleRequired(self, value: _Boolean) -> None: ...
    @property
    def assetVerification(self) -> list[AssetVerificationConfDataType]: ...
    @assetVerification.setter
    def assetVerification(self, value: Sequence[AssetVerificationConfDataType]) -> None: ...
    @property
    def communicationModelConfig(self) -> CommunicationModelConfigurationDataType: ...
    @communicationModelConfig.setter
    def communicationModelConfig(self, value: CommunicationModelConfigurationDataType) -> None: ...
    @property
    def automationComponentProperties(self) -> list[ns0.datatypes.KeyValuePair]: ...
    @automationComponentProperties.setter
    def automationComponentProperties(self, value: Sequence[ns0.datatypes.KeyValuePair]) -> None: ...
    @property
    def serverAddressIndex(self) -> o6.Int32: ...
    @serverAddressIndex.setter
    def serverAddressIndex(self, value: _Integer) -> None: ...

class ConnectionConfigurationSetConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def connectionConfigurationSetFolder(self) -> list[o6.String]: ...
    @connectionConfigurationSetFolder.setter
    def connectionConfigurationSetFolder(self, value: Sequence[o6.String]) -> None: ...
    @property
    def connections(self) -> list[ConnectionConfigurationConfDataType]: ...
    @connections.setter
    def connections(self, value: Sequence[ConnectionConfigurationConfDataType]) -> None: ...
    @property
    def communicationFlows(self) -> list[CommunicationFlowConfigurationConfDataType]: ...
    @communicationFlows.setter
    def communicationFlows(self, value: Sequence[CommunicationFlowConfigurationConfDataType]) -> None: ...
    @property
    def serverAddresses(self) -> list[ServerAddressConfDataType]: ...
    @serverAddresses.setter
    def serverAddresses(self, value: Sequence[ServerAddressConfDataType]) -> None: ...
    @property
    def automationComponentConfigurations(self) -> list[AutomationComponentConfigurationConfDataType]: ...
    @automationComponentConfigurations.setter
    def automationComponentConfigurations(self, value: Sequence[AutomationComponentConfigurationConfDataType]) -> None: ...
    @property
    def rollbackOnError(self) -> o6.Boolean: ...
    @rollbackOnError.setter
    def rollbackOnError(self, value: _Boolean) -> None: ...
    @property
    def securityKeyServer(self) -> SecurityKeyServerAddressConfDataType: ...
    @securityKeyServer.setter
    def securityKeyServer(self, value: SecurityKeyServerAddressConfDataType) -> None: ...
    @property
    def version(self) -> o6.UInt32: ...
    @version.setter
    def version(self, value: _Integer) -> None: ...
    @property
    def connectionConfigurationSetProperties(self) -> list[ns0.datatypes.KeyValuePair]: ...
    @connectionConfigurationSetProperties.setter
    def connectionConfigurationSetProperties(self, value: Sequence[ns0.datatypes.KeyValuePair]) -> None: ...

class NodeIdTranslationConfDataType(ns0.datatypes.Structure):
    @property
    def nodePlaceholder(self) -> o6.NodeId: ...
    @nodePlaceholder.setter
    def nodePlaceholder(self, value: o6.NodeId) -> None: ...
    @property
    def node(self) -> NodeIdentifier: ...
    @node.setter
    def node(self, value: NodeIdentifier) -> None: ...

class AddressSelectionDataType(ns0.datatypes.Structure):
    @property
    def address(self) -> ns0.datatypes.NetworkAddressDataType: ...
    @address.setter
    def address(self, value: ns0.datatypes.NetworkAddressDataType) -> None: ...
    @property
    def addressSelection(self) -> list[ns0.datatypes.NetworkAddressDataType]: ...
    @addressSelection.setter
    def addressSelection(self, value: Sequence[ns0.datatypes.NetworkAddressDataType]) -> None: ...
    @property
    def addressModify(self) -> o6.Boolean: ...
    @addressModify.setter
    def addressModify(self, value: _Boolean) -> None: ...

class ReceiveQosSelectionDataType(ns0.datatypes.Structure):
    @property
    def receiveQos(self) -> list[ns0.datatypes.ReceiveQosDataType]: ...
    @receiveQos.setter
    def receiveQos(self, value: Sequence[ns0.datatypes.ReceiveQosDataType]) -> None: ...
    @property
    def receiveQosSelection(self) -> Any: ...
    @receiveQosSelection.setter
    def receiveQosSelection(self, value: Any) -> None: ...
    @property
    def receiveQosModify(self) -> o6.Boolean: ...
    @receiveQosModify.setter
    def receiveQosModify(self, value: _Boolean) -> None: ...

class SubscriberConfigurationConfDataType(ns0.datatypes.Structure):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def address(self) -> AddressSelectionDataType | None: ...
    @address.setter
    def address(self, value: AddressSelectionDataType | None) -> None: ...
    @property
    def messageReceiveTimeout(self) -> o6.Double: ...
    @messageReceiveTimeout.setter
    def messageReceiveTimeout(self, value: SupportsFloat) -> None: ...
    @property
    def messageReceiveTimeoutSelection(self) -> list[o6.Double] | None: ...
    @messageReceiveTimeoutSelection.setter
    def messageReceiveTimeoutSelection(self, value: Sequence[SupportsFloat] | None) -> None: ...
    @property
    def messageReceiveTimeoutModify(self) -> o6.Boolean | None: ...
    @messageReceiveTimeoutModify.setter
    def messageReceiveTimeoutModify(self, value: _Boolean | None) -> None: ...
    @property
    def receiveQos(self) -> ReceiveQosSelectionDataType | None: ...
    @receiveQos.setter
    def receiveQos(self, value: ReceiveQosSelectionDataType | None) -> None: ...
    @property
    def subscriberProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @subscriberProperties.setter
    def subscriberProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...

class PubSubCommunicationFlowConfigurationConfDataType(CommunicationFlowConfigurationConfDataType):
    @property
    def browseName(self) -> o6.String: ...
    @browseName.setter
    def browseName(self, value: o6.String) -> None: ...
    @property
    def flowProperties(self) -> list[ns0.datatypes.KeyValuePair] | None: ...
    @flowProperties.setter
    def flowProperties(self, value: Sequence[ns0.datatypes.KeyValuePair] | None) -> None: ...
    @property
    def address(self) -> AddressSelectionDataType | None: ...
    @address.setter
    def address(self, value: AddressSelectionDataType | None) -> None: ...
    @property
    def transportProfileUri(self) -> o6.String | None: ...
    @transportProfileUri.setter
    def transportProfileUri(self, value: o6.String | None) -> None: ...
    @property
    def transportProfileUriSelection(self) -> list[o6.String] | None: ...
    @transportProfileUriSelection.setter
    def transportProfileUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def transportProfileUriModify(self) -> o6.Boolean | None: ...
    @transportProfileUriModify.setter
    def transportProfileUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def headerLayoutUri(self) -> o6.String | None: ...
    @headerLayoutUri.setter
    def headerLayoutUri(self, value: o6.String | None) -> None: ...
    @property
    def headerLayoutUriSelection(self) -> list[o6.String] | None: ...
    @headerLayoutUriSelection.setter
    def headerLayoutUriSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def headerLayoutUriModify(self) -> o6.Boolean | None: ...
    @headerLayoutUriModify.setter
    def headerLayoutUriModify(self, value: _Boolean | None) -> None: ...
    @property
    def publishingInterval(self) -> o6.Double | None: ...
    @publishingInterval.setter
    def publishingInterval(self, value: SupportsFloat | None) -> None: ...
    @property
    def publishingIntervalSelection(self) -> list[o6.Double] | None: ...
    @publishingIntervalSelection.setter
    def publishingIntervalSelection(self, value: Sequence[SupportsFloat] | None) -> None: ...
    @property
    def publishingIntervalModify(self) -> o6.Boolean | None: ...
    @publishingIntervalModify.setter
    def publishingIntervalModify(self, value: _Boolean | None) -> None: ...
    @property
    def qos(self) -> CommunicationFlowQosDataType | None: ...
    @qos.setter
    def qos(self, value: CommunicationFlowQosDataType | None) -> None: ...
    @property
    def qosSelection(self) -> list[CommunicationFlowQosDataType] | None: ...
    @qosSelection.setter
    def qosSelection(self, value: Sequence[CommunicationFlowQosDataType] | None) -> None: ...
    @property
    def qosModify(self) -> o6.Boolean | None: ...
    @qosModify.setter
    def qosModify(self, value: _Boolean | None) -> None: ...
    @property
    def securityMode(self) -> ns0.datatypes.MessageSecurityMode | None: ...
    @securityMode.setter
    def securityMode(self, value: ns0.datatypes.MessageSecurityMode | None) -> None: ...
    @property
    def securityModeSelection(self) -> list[ns0.datatypes.MessageSecurityMode] | None: ...
    @securityModeSelection.setter
    def securityModeSelection(self, value: Sequence[ns0.datatypes.MessageSecurityMode] | None) -> None: ...
    @property
    def securityModeModify(self) -> o6.Boolean | None: ...
    @securityModeModify.setter
    def securityModeModify(self, value: _Boolean | None) -> None: ...
    @property
    def securityGroupId(self) -> o6.String | None: ...
    @securityGroupId.setter
    def securityGroupId(self, value: o6.String | None) -> None: ...
    @property
    def securityGroupIdSelection(self) -> list[o6.String] | None: ...
    @securityGroupIdSelection.setter
    def securityGroupIdSelection(self, value: Sequence[o6.String] | None) -> None: ...
    @property
    def securityGroupIdModify(self) -> o6.Boolean | None: ...
    @securityGroupIdModify.setter
    def securityGroupIdModify(self, value: _Boolean | None) -> None: ...
    @property
    def subscriberConfigurations(self) -> list[SubscriberConfigurationConfDataType] | None: ...
    @subscriberConfigurations.setter
    def subscriberConfigurations(self, value: Sequence[SubscriberConfigurationConfDataType] | None) -> None: ...

class ConnectionConfigurationSetOperation(enum.IntFlag):
    ELEMENT_ADD = 0
    ELEMENT_REMOVE = 1
    ELEMENT_REPLACE = 2
